version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Accra"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Africa/Accra"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(go)"
