// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeDashboardFailedSMS = `-- name: BackofficeDashboardFailedSMS :many
SELECT s.id, t.name AS team_name, s.to_number, s.status,
       coalesce(s.error_message, '') AS error_message, s.created_at
FROM sms_messages s
JOIN teams t ON t.id = s.team_id
WHERE s.created_at >= now() - interval '24 hours'
  AND s.status IN ('failed', 'undelivered', 'rejected', 'expired')
ORDER BY s.created_at DESC
LIMIT 8
`

type BackofficeDashboardFailedSMSRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TeamName     string             `db:"team_name" json:"team_name"`
	ToNumber     string             `db:"to_number" json:"to_number"`
	Status       string             `db:"status" json:"status"`
	ErrorMessage string             `db:"error_message" json:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeDashboardFailedSMS(ctx context.Context) ([]BackofficeDashboardFailedSMSRow, error) {
	rows, err := q.db.Query(ctx, backofficeDashboardFailedSMS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeDashboardFailedSMSRow{}
	for rows.Next() {
		var i BackofficeDashboardFailedSMSRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamName,
			&i.ToNumber,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeDashboardPendingDomains = `-- name: BackofficeDashboardPendingDomains :many
SELECT d.id, coalesce(t.name, '') AS team_name, d.normalized_name AS name, d.created_at
FROM domains d
LEFT JOIN teams t ON t.id = d.team_id
WHERE d.status = 'pending'
ORDER BY d.created_at ASC
LIMIT 6
`

type BackofficeDashboardPendingDomainsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TeamName  string             `db:"team_name" json:"team_name"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeDashboardPendingDomains(ctx context.Context) ([]BackofficeDashboardPendingDomainsRow, error) {
	rows, err := q.db.Query(ctx, backofficeDashboardPendingDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeDashboardPendingDomainsRow{}
	for rows.Next() {
		var i BackofficeDashboardPendingDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamName,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeDashboardPendingSenderIDs = `-- name: BackofficeDashboardPendingSenderIDs :many
SELECT s.id, t.name AS team_name, s.name, s.country_code, s.created_at
FROM sender_ids s
JOIN teams t ON t.id = s.team_id
WHERE s.status = 'pending'
ORDER BY s.created_at ASC
LIMIT 6
`

type BackofficeDashboardPendingSenderIDsRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamName    string             `db:"team_name" json:"team_name"`
	Name        string             `db:"name" json:"name"`
	CountryCode string             `db:"country_code" json:"country_code"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeDashboardPendingSenderIDs(ctx context.Context) ([]BackofficeDashboardPendingSenderIDsRow, error) {
	rows, err := q.db.Query(ctx, backofficeDashboardPendingSenderIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeDashboardPendingSenderIDsRow{}
	for rows.Next() {
		var i BackofficeDashboardPendingSenderIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamName,
			&i.Name,
			&i.CountryCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeDashboardRecentActivity = `-- name: BackofficeDashboardRecentActivity :many
SELECT action, resource_type, resource_id, outcome, actor_type, created_at
FROM audit_events
ORDER BY created_at DESC, id DESC
LIMIT 8
`

type BackofficeDashboardRecentActivityRow struct {
	Action       string             `db:"action" json:"action"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   string             `db:"resource_id" json:"resource_id"`
	Outcome      string             `db:"outcome" json:"outcome"`
	ActorType    string             `db:"actor_type" json:"actor_type"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeDashboardRecentActivity(ctx context.Context) ([]BackofficeDashboardRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, backofficeDashboardRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeDashboardRecentActivityRow{}
	for rows.Next() {
		var i BackofficeDashboardRecentActivityRow
		if err := rows.Scan(
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.ActorType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeDashboardStats = `-- name: BackofficeDashboardStats :one
SELECT
 (SELECT count(*) FROM users) AS users,
 (SELECT count(*) FROM teams) AS teams,
 (SELECT count(*) FROM sms_messages WHERE created_at >= date_trunc('day', now())) AS sms_today,
 (SELECT count(*) FROM sms_messages WHERE created_at >= now() - interval '24 hours' AND status IN ('failed','undelivered','rejected','expired')) AS failed_sms_24_hours,
 (SELECT count(*) FROM sender_ids WHERE status = 'pending') AS pending_sender_ids,
 (SELECT count(*) FROM domains WHERE status = 'pending') AS pending_domains
`

type BackofficeDashboardStatsRow struct {
	Users            int64 `db:"users" json:"users"`
	Teams            int64 `db:"teams" json:"teams"`
	SmsToday         int64 `db:"sms_today" json:"sms_today"`
	FailedSms24Hours int64 `db:"failed_sms_24_hours" json:"failed_sms_24_hours"`
	PendingSenderIds int64 `db:"pending_sender_ids" json:"pending_sender_ids"`
	PendingDomains   int64 `db:"pending_domains" json:"pending_domains"`
}

func (q *Queries) BackofficeDashboardStats(ctx context.Context) (BackofficeDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, backofficeDashboardStats)
	var i BackofficeDashboardStatsRow
	err := row.Scan(
		&i.Users,
		&i.Teams,
		&i.SmsToday,
		&i.FailedSms24Hours,
		&i.PendingSenderIds,
		&i.PendingDomains,
	)
	return i, err
}
