// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeListAuditEvents = `-- name: BackofficeListAuditEvents :many
SELECT a.id, a.action, a.resource_type, a.resource_id, a.outcome,
       a.actor_type, coalesce(u.email, '') AS actor_email,
       coalesce(t.name, '') AS team_name, a.request_id, a.ip_address,
       a.metadata, a.created_at
FROM audit_events a
LEFT JOIN users u ON u.id = a.actor_user_id
LEFT JOIN teams t ON t.id = a.team_id
WHERE ($1::text = ''
       OR a.action ILIKE '%' || $1::text || '%'
       OR a.resource_type ILIKE '%' || $1::text || '%'
       OR a.resource_id ILIKE '%' || $1::text || '%'
       OR u.email ILIKE '%' || $1::text || '%'
       OR t.name ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR a.outcome = $2)
  AND ($3::text = '' OR a.actor_type = $3)
ORDER BY a.created_at DESC, a.id DESC
LIMIT $5::int OFFSET $4::int
`

type BackofficeListAuditEventsParams struct {
	Search     string `db:"search" json:"search"`
	Outcome    string `db:"outcome" json:"outcome"`
	ActorType  string `db:"actor_type" json:"actor_type"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageLimit  int32  `db:"page_limit" json:"page_limit"`
}

type BackofficeListAuditEventsRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Action       string             `db:"action" json:"action"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   string             `db:"resource_id" json:"resource_id"`
	Outcome      string             `db:"outcome" json:"outcome"`
	ActorType    string             `db:"actor_type" json:"actor_type"`
	ActorEmail   string             `db:"actor_email" json:"actor_email"`
	TeamName     string             `db:"team_name" json:"team_name"`
	RequestID    *string            `db:"request_id" json:"request_id"`
	IpAddress    *string            `db:"ip_address" json:"ip_address"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeListAuditEvents(ctx context.Context, arg BackofficeListAuditEventsParams) ([]BackofficeListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, backofficeListAuditEvents,
		arg.Search,
		arg.Outcome,
		arg.ActorType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListAuditEventsRow{}
	for rows.Next() {
		var i BackofficeListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.ActorType,
			&i.ActorEmail,
			&i.TeamName,
			&i.RequestID,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
