// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeGetTeam = `-- name: BackofficeGetTeam :one
SELECT id,name,status,created_at FROM teams WHERE id=$1
`

type BackofficeGetTeamParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

type BackofficeGetTeamRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeGetTeam(ctx context.Context, arg BackofficeGetTeamParams) (BackofficeGetTeamRow, error) {
	row := q.db.QueryRow(ctx, backofficeGetTeam, arg.ID)
	var i BackofficeGetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeListTeamMembers = `-- name: BackofficeListTeamMembers :many
SELECT u.id AS user_id,u.email,u.name,tm.role,tm.status,tm.created_at FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=$1 ORDER BY tm.created_at DESC
`

type BackofficeListTeamMembersParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

type BackofficeListTeamMembersRow struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	Name      string             `db:"name" json:"name"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeListTeamMembers(ctx context.Context, arg BackofficeListTeamMembersParams) ([]BackofficeListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, backofficeListTeamMembers, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListTeamMembersRow{}
	for rows.Next() {
		var i BackofficeListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListTeamSMS = `-- name: BackofficeListTeamSMS :many
SELECT s.id,t.name AS team_name,s.to_number,s.from_name,s.status,coalesce(s.provider_id,''),coalesce(s.error_message,''),s.created_at FROM sms_messages s JOIN teams t ON t.id=s.team_id WHERE s.team_id=$1 ORDER BY s.created_at DESC LIMIT 25
`

type BackofficeListTeamSMSParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

type BackofficeListTeamSMSRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TeamName     string             `db:"team_name" json:"team_name"`
	ToNumber     string             `db:"to_number" json:"to_number"`
	FromName     string             `db:"from_name" json:"from_name"`
	Status       string             `db:"status" json:"status"`
	ProviderID   string             `db:"provider_id" json:"provider_id"`
	ErrorMessage string             `db:"error_message" json:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeListTeamSMS(ctx context.Context, arg BackofficeListTeamSMSParams) ([]BackofficeListTeamSMSRow, error) {
	rows, err := q.db.Query(ctx, backofficeListTeamSMS, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListTeamSMSRow{}
	for rows.Next() {
		var i BackofficeListTeamSMSRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamName,
			&i.ToNumber,
			&i.FromName,
			&i.Status,
			&i.ProviderID,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListTeams = `-- name: BackofficeListTeams :many
SELECT id, name, status, created_at
FROM teams
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4::int
OFFSET $3::int
`

type BackofficeListTeamsParams struct {
	Search     string `db:"search" json:"search"`
	Status     string `db:"status" json:"status"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageLimit  int32  `db:"page_limit" json:"page_limit"`
}

type BackofficeListTeamsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeListTeams(ctx context.Context, arg BackofficeListTeamsParams) ([]BackofficeListTeamsRow, error) {
	rows, err := q.db.Query(ctx, backofficeListTeams,
		arg.Search,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListTeamsRow{}
	for rows.Next() {
		var i BackofficeListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeUpdateTeamStatus = `-- name: BackofficeUpdateTeamStatus :execrows
UPDATE teams SET status=$1,updated_at=now() WHERE id=$2
`

type BackofficeUpdateTeamStatusParams struct {
	Status string    `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) BackofficeUpdateTeamStatus(ctx context.Context, arg BackofficeUpdateTeamStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, backofficeUpdateTeamStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
