// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_email.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeGetEmailMessage = `-- name: BackofficeGetEmailMessage :one
SELECT m.id, m.team_id, t.name AS team_name, m.sender_domain_id,
       m.message_type, m.from_email, m.from_name, m.reply_to_email,
       m.to_email, m.to_name, m.subject, m.html_body, m.text_body,
       m.status, m.delivery_provider, m.provider_region, m.provider,
       m.provider_message_id, m.error_code, m.error_message,
       m.metadata, m.recipients, m.headers, m.attachments, m.tags,
       m.scheduled_at, m.queued_at, m.processing_at, m.submitted_at,
       m.delivered_at, m.failed_at, m.created_at, m.updated_at
FROM email_messages m JOIN teams t ON t.id = m.team_id
WHERE m.id = $1
`

type BackofficeGetEmailMessageParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

type BackofficeGetEmailMessageRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	TeamName          string             `db:"team_name" json:"team_name"`
	SenderDomainID    *uuid.UUID         `db:"sender_domain_id" json:"sender_domain_id"`
	MessageType       string             `db:"message_type" json:"message_type"`
	FromEmail         string             `db:"from_email" json:"from_email"`
	FromName          *string            `db:"from_name" json:"from_name"`
	ReplyToEmail      *string            `db:"reply_to_email" json:"reply_to_email"`
	ToEmail           string             `db:"to_email" json:"to_email"`
	ToName            *string            `db:"to_name" json:"to_name"`
	Subject           string             `db:"subject" json:"subject"`
	HtmlBody          *string            `db:"html_body" json:"html_body"`
	TextBody          *string            `db:"text_body" json:"text_body"`
	Status            string             `db:"status" json:"status"`
	DeliveryProvider  string             `db:"delivery_provider" json:"delivery_provider"`
	ProviderRegion    string             `db:"provider_region" json:"provider_region"`
	Provider          *string            `db:"provider" json:"provider"`
	ProviderMessageID *string            `db:"provider_message_id" json:"provider_message_id"`
	ErrorCode         *string            `db:"error_code" json:"error_code"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	Recipients        []byte             `db:"recipients" json:"recipients"`
	Headers           []byte             `db:"headers" json:"headers"`
	Attachments       []byte             `db:"attachments" json:"attachments"`
	Tags              []byte             `db:"tags" json:"tags"`
	ScheduledAt       pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	QueuedAt          pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	ProcessingAt      pgtype.Timestamptz `db:"processing_at" json:"processing_at"`
	SubmittedAt       pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt          pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) BackofficeGetEmailMessage(ctx context.Context, arg BackofficeGetEmailMessageParams) (BackofficeGetEmailMessageRow, error) {
	row := q.db.QueryRow(ctx, backofficeGetEmailMessage, arg.ID)
	var i BackofficeGetEmailMessageRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.TeamName,
		&i.SenderDomainID,
		&i.MessageType,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.DeliveryProvider,
		&i.ProviderRegion,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.Recipients,
		&i.Headers,
		&i.Attachments,
		&i.Tags,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backofficeListEmailMessages = `-- name: BackofficeListEmailMessages :many
SELECT m.id, t.name AS team_name, m.from_email, m.to_email, m.subject,
       m.status, coalesce(m.provider, m.delivery_provider) AS provider,
       coalesce(m.error_message, '') AS error_message, m.created_at
FROM email_messages m
JOIN teams t ON t.id = m.team_id
WHERE ($1::text = '' OR t.name ILIKE '%' || $1::text || '%'
       OR m.from_email ILIKE '%' || $1::text || '%'
       OR m.to_email ILIKE '%' || $1::text || '%'
       OR m.subject ILIKE '%' || $1::text || '%'
       OR m.id::text = $1::text)
  AND ($2::text = '' OR m.status = $2)
ORDER BY m.created_at DESC
LIMIT 100
`

type BackofficeListEmailMessagesParams struct {
	Search string `db:"search" json:"search"`
	Status string `db:"status" json:"status"`
}

type BackofficeListEmailMessagesRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TeamName     string             `db:"team_name" json:"team_name"`
	FromEmail    string             `db:"from_email" json:"from_email"`
	ToEmail      string             `db:"to_email" json:"to_email"`
	Subject      string             `db:"subject" json:"subject"`
	Status       string             `db:"status" json:"status"`
	Provider     string             `db:"provider" json:"provider"`
	ErrorMessage string             `db:"error_message" json:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeListEmailMessages(ctx context.Context, arg BackofficeListEmailMessagesParams) ([]BackofficeListEmailMessagesRow, error) {
	rows, err := q.db.Query(ctx, backofficeListEmailMessages, arg.Search, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListEmailMessagesRow{}
	for rows.Next() {
		var i BackofficeListEmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamName,
			&i.FromEmail,
			&i.ToEmail,
			&i.Subject,
			&i.Status,
			&i.Provider,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListEmailRecipients = `-- name: BackofficeListEmailRecipients :many
SELECT recipient_email, recipient_type, status, last_event_type, last_event_at,
       error_code, error_message, delivered_at, failed_at
FROM email_recipients WHERE email_message_id = $1
ORDER BY recipient_type, recipient_email
`

type BackofficeListEmailRecipientsParams struct {
	MessageID uuid.UUID `db:"message_id" json:"message_id"`
}

type BackofficeListEmailRecipientsRow struct {
	RecipientEmail string             `db:"recipient_email" json:"recipient_email"`
	RecipientType  string             `db:"recipient_type" json:"recipient_type"`
	Status         string             `db:"status" json:"status"`
	LastEventType  *string            `db:"last_event_type" json:"last_event_type"`
	LastEventAt    pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	ErrorCode      *string            `db:"error_code" json:"error_code"`
	ErrorMessage   *string            `db:"error_message" json:"error_message"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt       pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
}

func (q *Queries) BackofficeListEmailRecipients(ctx context.Context, arg BackofficeListEmailRecipientsParams) ([]BackofficeListEmailRecipientsRow, error) {
	rows, err := q.db.Query(ctx, backofficeListEmailRecipients, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListEmailRecipientsRow{}
	for rows.Next() {
		var i BackofficeListEmailRecipientsRow
		if err := rows.Scan(
			&i.RecipientEmail,
			&i.RecipientType,
			&i.Status,
			&i.LastEventType,
			&i.LastEventAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.DeliveredAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
