// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_rates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeCloseAllowancePolicy = `-- name: BackofficeCloseAllowancePolicy :one
UPDATE allowance_policies SET effective_until=$1,updated_at=now() WHERE id=$2 AND $1>effective_from AND (effective_until IS NULL OR $1<effective_until) RETURNING id, product, meter, billing_market, tier, included_quantity, cadence, effective_from, effective_until, created_at, updated_at
`

type BackofficeCloseAllowancePolicyParams struct {
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) BackofficeCloseAllowancePolicy(ctx context.Context, arg BackofficeCloseAllowancePolicyParams) (AllowancePolicy, error) {
	row := q.db.QueryRow(ctx, backofficeCloseAllowancePolicy, arg.EffectiveUntil, arg.ID)
	var i AllowancePolicy
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.IncludedQuantity,
		&i.Cadence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backofficeCloseFXRate = `-- name: BackofficeCloseFXRate :one
UPDATE fx_rates
SET effective_until = $1
WHERE id = $2
  AND $1 > effective_from
  AND (effective_until IS NULL OR $1 < effective_until)
RETURNING id, base_currency, quote_currency, rate, effective_from, effective_until, created_at
`

type BackofficeCloseFXRateParams struct {
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) BackofficeCloseFXRate(ctx context.Context, arg BackofficeCloseFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, backofficeCloseFXRate, arg.EffectiveUntil, arg.ID)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeCloseProductRate = `-- name: BackofficeCloseProductRate :one
UPDATE product_rates SET effective_until=$1 WHERE id=$2 AND $1>effective_from AND (effective_until IS NULL OR $1<effective_until) RETURNING id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at
`

type BackofficeCloseProductRateParams struct {
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) BackofficeCloseProductRate(ctx context.Context, arg BackofficeCloseProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, backofficeCloseProductRate, arg.EffectiveUntil, arg.ID)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeCloseSMSRate = `-- name: BackofficeCloseSMSRate :one
UPDATE sms_rates SET effective_until=$1 WHERE id=$2 AND $1>effective_from AND (effective_until IS NULL OR $1<effective_until) RETURNING id, destination_country, route_type, tier, currency, cost_units, effective_from, effective_until, created_at
`

type BackofficeCloseSMSRateParams struct {
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) BackofficeCloseSMSRate(ctx context.Context, arg BackofficeCloseSMSRateParams) (SmsRate, error) {
	row := q.db.QueryRow(ctx, backofficeCloseSMSRate, arg.EffectiveUntil, arg.ID)
	var i SmsRate
	err := row.Scan(
		&i.ID,
		&i.DestinationCountry,
		&i.RouteType,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeCreateAllowancePolicy = `-- name: BackofficeCreateAllowancePolicy :one
INSERT INTO allowance_policies (product,meter,billing_market,tier,included_quantity,cadence,effective_from,effective_until) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, product, meter, billing_market, tier, included_quantity, cadence, effective_from, effective_until, created_at, updated_at
`

type BackofficeCreateAllowancePolicyParams struct {
	Product          string             `db:"product" json:"product"`
	Meter            string             `db:"meter" json:"meter"`
	BillingMarket    string             `db:"billing_market" json:"billing_market"`
	Tier             string             `db:"tier" json:"tier"`
	IncludedQuantity int64              `db:"included_quantity" json:"included_quantity"`
	Cadence          string             `db:"cadence" json:"cadence"`
	EffectiveFrom    pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil   pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
}

func (q *Queries) BackofficeCreateAllowancePolicy(ctx context.Context, arg BackofficeCreateAllowancePolicyParams) (AllowancePolicy, error) {
	row := q.db.QueryRow(ctx, backofficeCreateAllowancePolicy,
		arg.Product,
		arg.Meter,
		arg.BillingMarket,
		arg.Tier,
		arg.IncludedQuantity,
		arg.Cadence,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
	)
	var i AllowancePolicy
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.IncludedQuantity,
		&i.Cadence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backofficeCreateFXRate = `-- name: BackofficeCreateFXRate :one
INSERT INTO fx_rates (
    base_currency,
    quote_currency,
    rate,
    effective_from,
    effective_until
)
VALUES (
    upper($1)::char(3),
    upper($2)::char(3),
    $3,
    $4,
    $5
)
RETURNING id, base_currency, quote_currency, rate, effective_from, effective_until, created_at
`

type BackofficeCreateFXRateParams struct {
	BaseCurrency   interface{}        `db:"base_currency" json:"base_currency"`
	QuoteCurrency  interface{}        `db:"quote_currency" json:"quote_currency"`
	Rate           pgtype.Numeric     `db:"rate" json:"rate"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
}

func (q *Queries) BackofficeCreateFXRate(ctx context.Context, arg BackofficeCreateFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, backofficeCreateFXRate,
		arg.BaseCurrency,
		arg.QuoteCurrency,
		arg.Rate,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeCreateProductRate = `-- name: BackofficeCreateProductRate :one
INSERT INTO product_rates (product,meter,billing_market,tier,currency,cost_units,effective_from,effective_until) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at
`

type BackofficeCreateProductRateParams struct {
	Product        string             `db:"product" json:"product"`
	Meter          string             `db:"meter" json:"meter"`
	BillingMarket  string             `db:"billing_market" json:"billing_market"`
	Tier           string             `db:"tier" json:"tier"`
	Currency       string             `db:"currency" json:"currency"`
	CostUnits      int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
}

func (q *Queries) BackofficeCreateProductRate(ctx context.Context, arg BackofficeCreateProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, backofficeCreateProductRate,
		arg.Product,
		arg.Meter,
		arg.BillingMarket,
		arg.Tier,
		arg.Currency,
		arg.CostUnits,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
	)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeCreateSMSRate = `-- name: BackofficeCreateSMSRate :one
INSERT INTO sms_rates (destination_country,route_type,tier,currency,cost_units,effective_from,effective_until) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, destination_country, route_type, tier, currency, cost_units, effective_from, effective_until, created_at
`

type BackofficeCreateSMSRateParams struct {
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
	RouteType          string             `db:"route_type" json:"route_type"`
	Tier               string             `db:"tier" json:"tier"`
	Currency           string             `db:"currency" json:"currency"`
	CostUnits          int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom      pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil     pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
}

func (q *Queries) BackofficeCreateSMSRate(ctx context.Context, arg BackofficeCreateSMSRateParams) (SmsRate, error) {
	row := q.db.QueryRow(ctx, backofficeCreateSMSRate,
		arg.DestinationCountry,
		arg.RouteType,
		arg.Tier,
		arg.Currency,
		arg.CostUnits,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
	)
	var i SmsRate
	err := row.Scan(
		&i.ID,
		&i.DestinationCountry,
		&i.RouteType,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeGetAllowancePolicy = `-- name: BackofficeGetAllowancePolicy :one
SELECT id, product, meter, billing_market, tier, included_quantity, cadence, effective_from, effective_until, created_at, updated_at FROM allowance_policies WHERE id=$1
`

type BackofficeGetAllowancePolicyParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) BackofficeGetAllowancePolicy(ctx context.Context, arg BackofficeGetAllowancePolicyParams) (AllowancePolicy, error) {
	row := q.db.QueryRow(ctx, backofficeGetAllowancePolicy, arg.ID)
	var i AllowancePolicy
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.IncludedQuantity,
		&i.Cadence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backofficeGetFXRate = `-- name: BackofficeGetFXRate :one
SELECT id, base_currency, quote_currency, rate, effective_from, effective_until, created_at
FROM fx_rates
WHERE id = $1
`

type BackofficeGetFXRateParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) BackofficeGetFXRate(ctx context.Context, arg BackofficeGetFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, backofficeGetFXRate, arg.ID)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeGetProductRate = `-- name: BackofficeGetProductRate :one
SELECT id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at FROM product_rates WHERE id=$1
`

type BackofficeGetProductRateParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) BackofficeGetProductRate(ctx context.Context, arg BackofficeGetProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, backofficeGetProductRate, arg.ID)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeGetSMSRate = `-- name: BackofficeGetSMSRate :one
SELECT id, destination_country, route_type, tier, currency, cost_units, effective_from, effective_until, created_at FROM sms_rates WHERE id=$1
`

type BackofficeGetSMSRateParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) BackofficeGetSMSRate(ctx context.Context, arg BackofficeGetSMSRateParams) (SmsRate, error) {
	row := q.db.QueryRow(ctx, backofficeGetSMSRate, arg.ID)
	var i SmsRate
	err := row.Scan(
		&i.ID,
		&i.DestinationCountry,
		&i.RouteType,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeListAllowancePolicies = `-- name: BackofficeListAllowancePolicies :many
SELECT id, product, meter, billing_market, tier, included_quantity, cadence, effective_from, effective_until, created_at, updated_at FROM allowance_policies ORDER BY effective_from DESC,created_at DESC LIMIT $2::int OFFSET $1::int
`

type BackofficeListAllowancePoliciesParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) BackofficeListAllowancePolicies(ctx context.Context, arg BackofficeListAllowancePoliciesParams) ([]AllowancePolicy, error) {
	rows, err := q.db.Query(ctx, backofficeListAllowancePolicies, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllowancePolicy{}
	for rows.Next() {
		var i AllowancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.Product,
			&i.Meter,
			&i.BillingMarket,
			&i.Tier,
			&i.IncludedQuantity,
			&i.Cadence,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListFXRates = `-- name: BackofficeListFXRates :many
SELECT id, base_currency, quote_currency, rate, effective_from, effective_until, created_at
FROM fx_rates
ORDER BY effective_from DESC, created_at DESC
LIMIT $2::int
OFFSET $1::int
`

type BackofficeListFXRatesParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) BackofficeListFXRates(ctx context.Context, arg BackofficeListFXRatesParams) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, backofficeListFXRates, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxRate{}
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.QuoteCurrency,
			&i.Rate,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListProductRates = `-- name: BackofficeListProductRates :many
SELECT id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at FROM product_rates ORDER BY effective_from DESC,created_at DESC LIMIT $2::int OFFSET $1::int
`

type BackofficeListProductRatesParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) BackofficeListProductRates(ctx context.Context, arg BackofficeListProductRatesParams) ([]ProductRate, error) {
	rows, err := q.db.Query(ctx, backofficeListProductRates, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductRate{}
	for rows.Next() {
		var i ProductRate
		if err := rows.Scan(
			&i.ID,
			&i.Product,
			&i.Meter,
			&i.BillingMarket,
			&i.Tier,
			&i.Currency,
			&i.CostUnits,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListSMSRates = `-- name: BackofficeListSMSRates :many
SELECT id, destination_country, route_type, tier, currency, cost_units, effective_from, effective_until, created_at FROM sms_rates ORDER BY effective_from DESC,created_at DESC LIMIT $2::int OFFSET $1::int
`

type BackofficeListSMSRatesParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) BackofficeListSMSRates(ctx context.Context, arg BackofficeListSMSRatesParams) ([]SmsRate, error) {
	rows, err := q.db.Query(ctx, backofficeListSMSRates, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsRate{}
	for rows.Next() {
		var i SmsRate
		if err := rows.Scan(
			&i.ID,
			&i.DestinationCountry,
			&i.RouteType,
			&i.Tier,
			&i.Currency,
			&i.CostUnits,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeReplaceAllowancePolicy = `-- name: BackofficeReplaceAllowancePolicy :one
WITH closed AS (
  UPDATE allowance_policies AS current SET effective_until=$2,updated_at=now()
  WHERE current.id=$4 AND $2>current.effective_from AND (current.effective_until IS NULL OR $2<current.effective_until)
  RETURNING product,meter,billing_market,tier,cadence
)
INSERT INTO allowance_policies (product,meter,billing_market,tier,included_quantity,cadence,effective_from,effective_until)
SELECT product,meter,billing_market,tier,$1,cadence,$2,$3 FROM closed
RETURNING id, product, meter, billing_market, tier, included_quantity, cadence, effective_from, effective_until, created_at, updated_at
`

type BackofficeReplaceAllowancePolicyParams struct {
	IncludedQuantity int64              `db:"included_quantity" json:"included_quantity"`
	EffectiveFrom    pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil   pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	TargetID         uuid.UUID          `db:"target_id" json:"target_id"`
}

func (q *Queries) BackofficeReplaceAllowancePolicy(ctx context.Context, arg BackofficeReplaceAllowancePolicyParams) (AllowancePolicy, error) {
	row := q.db.QueryRow(ctx, backofficeReplaceAllowancePolicy,
		arg.IncludedQuantity,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.TargetID,
	)
	var i AllowancePolicy
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.IncludedQuantity,
		&i.Cadence,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backofficeReplaceFXRate = `-- name: BackofficeReplaceFXRate :one
WITH closed_rate AS (
    UPDATE fx_rates AS current
    SET effective_until = $2
    WHERE current.id = $3
      AND current.effective_from < $2
      AND (
          current.effective_until IS NULL
          OR current.effective_until > $2
      )
    RETURNING base_currency, quote_currency
)
INSERT INTO fx_rates (
    base_currency,
    quote_currency,
    rate,
    effective_from
)
SELECT
    base_currency,
    quote_currency,
    $1,
    $2
FROM closed_rate
RETURNING id, base_currency, quote_currency, rate, effective_from, effective_until, created_at
`

type BackofficeReplaceFXRateParams struct {
	Rate          pgtype.Numeric     `db:"rate" json:"rate"`
	EffectiveFrom pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	TargetID      uuid.UUID          `db:"target_id" json:"target_id"`
}

func (q *Queries) BackofficeReplaceFXRate(ctx context.Context, arg BackofficeReplaceFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, backofficeReplaceFXRate, arg.Rate, arg.EffectiveFrom, arg.TargetID)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.QuoteCurrency,
		&i.Rate,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeReplaceProductRate = `-- name: BackofficeReplaceProductRate :one
WITH closed AS (
  UPDATE product_rates AS current SET effective_until=$2
  WHERE current.id=$4 AND $2>current.effective_from AND (current.effective_until IS NULL OR $2<current.effective_until)
  RETURNING product,meter,billing_market,tier,currency
)
INSERT INTO product_rates (product,meter,billing_market,tier,currency,cost_units,effective_from,effective_until)
SELECT product,meter,billing_market,tier,currency,$1,$2,$3 FROM closed
RETURNING id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at
`

type BackofficeReplaceProductRateParams struct {
	CostUnits      int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	TargetID       uuid.UUID          `db:"target_id" json:"target_id"`
}

func (q *Queries) BackofficeReplaceProductRate(ctx context.Context, arg BackofficeReplaceProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, backofficeReplaceProductRate,
		arg.CostUnits,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.TargetID,
	)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeReplaceSMSRate = `-- name: BackofficeReplaceSMSRate :one
WITH closed AS (
  UPDATE sms_rates AS current SET effective_until=$2
  WHERE current.id=$4 AND $2>current.effective_from AND (current.effective_until IS NULL OR $2<current.effective_until)
  RETURNING destination_country,route_type,tier,currency
)
INSERT INTO sms_rates (destination_country,route_type,tier,currency,cost_units,effective_from,effective_until)
SELECT destination_country,route_type,tier,currency,$1,$2,$3 FROM closed
RETURNING id, destination_country, route_type, tier, currency, cost_units, effective_from, effective_until, created_at
`

type BackofficeReplaceSMSRateParams struct {
	CostUnits      int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	TargetID       uuid.UUID          `db:"target_id" json:"target_id"`
}

func (q *Queries) BackofficeReplaceSMSRate(ctx context.Context, arg BackofficeReplaceSMSRateParams) (SmsRate, error) {
	row := q.db.QueryRow(ctx, backofficeReplaceSMSRate,
		arg.CostUnits,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.TargetID,
	)
	var i SmsRate
	err := row.Scan(
		&i.ID,
		&i.DestinationCountry,
		&i.RouteType,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}
