// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_wallets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeAdjustWallet = `-- name: BackofficeAdjustWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT team_id, billing_market, currency, balance_units, created_at, updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (team_id, amount_units, transaction_type, reference_id)
    SELECT team_id, $2, 'adjustment', $3
    FROM locked_wallet
    WHERE $2::bigint <> 0
      AND balance_units::numeric + $2::numeric
          BETWEEN 0 AND 9223372036854775807
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
)
UPDATE team_wallets AS wallet
SET balance_units = wallet.balance_units + ledger.amount_units,
    updated_at = now()
FROM inserted_ledger AS ledger
WHERE wallet.team_id = ledger.team_id
RETURNING wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at
`

type BackofficeAdjustWalletParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits int64     `db:"amount_units" json:"amount_units"`
	ReferenceID string    `db:"reference_id" json:"reference_id"`
}

func (q *Queries) BackofficeAdjustWallet(ctx context.Context, arg BackofficeAdjustWalletParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, backofficeAdjustWallet, arg.TeamID, arg.AmountUnits, arg.ReferenceID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backofficeGetWallet = `-- name: BackofficeGetWallet :one
SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at, subscription.plan_code AS tier, team.name AS team_name
FROM team_wallets AS wallet
JOIN teams AS team ON team.id = wallet.team_id
JOIN team_subscriptions AS subscription ON subscription.team_id = wallet.team_id
WHERE wallet.team_id = $1
`

type BackofficeGetWalletParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

type BackofficeGetWalletRow struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Tier          string             `db:"tier" json:"tier"`
	TeamName      string             `db:"team_name" json:"team_name"`
}

func (q *Queries) BackofficeGetWallet(ctx context.Context, arg BackofficeGetWalletParams) (BackofficeGetWalletRow, error) {
	row := q.db.QueryRow(ctx, backofficeGetWallet, arg.TeamID)
	var i BackofficeGetWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.TeamName,
	)
	return i, err
}

const backofficeGetWalletTransaction = `-- name: BackofficeGetWalletTransaction :one
SELECT ledger.id, ledger.team_id, ledger.usage_authorization_id, ledger.subscription_charge_id, ledger.payment_transaction_id, ledger.amount_units, ledger.transaction_type, ledger.reference_id, ledger.created_at, team.name AS team_name, wallet.currency
FROM wallet_ledger AS ledger
JOIN teams AS team ON team.id = ledger.team_id
JOIN team_wallets AS wallet ON wallet.team_id = ledger.team_id
WHERE ledger.team_id = $1 AND ledger.id = $2
`

type BackofficeGetWalletTransactionParams struct {
	TeamID        uuid.UUID `db:"team_id" json:"team_id"`
	TransactionID uuid.UUID `db:"transaction_id" json:"transaction_id"`
}

type BackofficeGetWalletTransactionRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	UsageAuthorizationID *uuid.UUID         `db:"usage_authorization_id" json:"usage_authorization_id"`
	SubscriptionChargeID *uuid.UUID         `db:"subscription_charge_id" json:"subscription_charge_id"`
	PaymentTransactionID *uuid.UUID         `db:"payment_transaction_id" json:"payment_transaction_id"`
	AmountUnits          int64              `db:"amount_units" json:"amount_units"`
	TransactionType      string             `db:"transaction_type" json:"transaction_type"`
	ReferenceID          string             `db:"reference_id" json:"reference_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	TeamName             string             `db:"team_name" json:"team_name"`
	Currency             string             `db:"currency" json:"currency"`
}

func (q *Queries) BackofficeGetWalletTransaction(ctx context.Context, arg BackofficeGetWalletTransactionParams) (BackofficeGetWalletTransactionRow, error) {
	row := q.db.QueryRow(ctx, backofficeGetWalletTransaction, arg.TeamID, arg.TransactionID)
	var i BackofficeGetWalletTransactionRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UsageAuthorizationID,
		&i.SubscriptionChargeID,
		&i.PaymentTransactionID,
		&i.AmountUnits,
		&i.TransactionType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.TeamName,
		&i.Currency,
	)
	return i, err
}

const backofficeListWalletTransactions = `-- name: BackofficeListWalletTransactions :many
SELECT ledger.id, ledger.team_id, ledger.usage_authorization_id, ledger.subscription_charge_id, ledger.payment_transaction_id, ledger.amount_units, ledger.transaction_type, ledger.reference_id, ledger.created_at, team.name AS team_name, wallet.currency
FROM wallet_ledger AS ledger
JOIN teams AS team ON team.id = ledger.team_id
JOIN team_wallets AS wallet ON wallet.team_id = ledger.team_id
WHERE $1::uuid IS NULL
   OR ledger.team_id = $1::uuid
ORDER BY ledger.created_at DESC, ledger.id DESC
LIMIT $3
OFFSET $2
`

type BackofficeListWalletTransactionsParams struct {
	TeamID     *uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32      `db:"page_offset" json:"page_offset"`
	PageLimit  int32      `db:"page_limit" json:"page_limit"`
}

type BackofficeListWalletTransactionsRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	UsageAuthorizationID *uuid.UUID         `db:"usage_authorization_id" json:"usage_authorization_id"`
	SubscriptionChargeID *uuid.UUID         `db:"subscription_charge_id" json:"subscription_charge_id"`
	PaymentTransactionID *uuid.UUID         `db:"payment_transaction_id" json:"payment_transaction_id"`
	AmountUnits          int64              `db:"amount_units" json:"amount_units"`
	TransactionType      string             `db:"transaction_type" json:"transaction_type"`
	ReferenceID          string             `db:"reference_id" json:"reference_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	TeamName             string             `db:"team_name" json:"team_name"`
	Currency             string             `db:"currency" json:"currency"`
}

func (q *Queries) BackofficeListWalletTransactions(ctx context.Context, arg BackofficeListWalletTransactionsParams) ([]BackofficeListWalletTransactionsRow, error) {
	rows, err := q.db.Query(ctx, backofficeListWalletTransactions, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListWalletTransactionsRow{}
	for rows.Next() {
		var i BackofficeListWalletTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UsageAuthorizationID,
			&i.SubscriptionChargeID,
			&i.PaymentTransactionID,
			&i.AmountUnits,
			&i.TransactionType,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.TeamName,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListWallets = `-- name: BackofficeListWallets :many
SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at, subscription.plan_code AS tier, team.name AS team_name
FROM team_wallets AS wallet
JOIN teams AS team ON team.id = wallet.team_id
JOIN team_subscriptions AS subscription ON subscription.team_id = wallet.team_id
ORDER BY wallet.updated_at DESC, wallet.team_id
LIMIT $2
OFFSET $1
`

type BackofficeListWalletsParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

type BackofficeListWalletsRow struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Tier          string             `db:"tier" json:"tier"`
	TeamName      string             `db:"team_name" json:"team_name"`
}

func (q *Queries) BackofficeListWallets(ctx context.Context, arg BackofficeListWalletsParams) ([]BackofficeListWalletsRow, error) {
	rows, err := q.db.Query(ctx, backofficeListWallets, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListWalletsRow{}
	for rows.Next() {
		var i BackofficeListWalletsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.BillingMarket,
			&i.Currency,
			&i.BalanceUnits,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
