// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backoffice_users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backofficeGetUser = `-- name: BackofficeGetUser :one
SELECT
    id,
    email,
    name,
    email_verified,
    created_at
FROM users
WHERE id = $1
`

type BackofficeGetUserParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

type BackofficeGetUserRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         string             `db:"email" json:"email"`
	Name          string             `db:"name" json:"name"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeGetUser(ctx context.Context, arg BackofficeGetUserParams) (BackofficeGetUserRow, error) {
	row := q.db.QueryRow(ctx, backofficeGetUser, arg.ID)
	var i BackofficeGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const backofficeListUserTeams = `-- name: BackofficeListUserTeams :many
SELECT
    team.id,
    team.name,
    membership.role,
    membership.status
FROM team_members AS membership
JOIN teams AS team ON team.id = membership.team_id
WHERE membership.user_id = $1
ORDER BY team.created_at DESC
`

type BackofficeListUserTeamsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type BackofficeListUserTeamsRow struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Role   string    `db:"role" json:"role"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) BackofficeListUserTeams(ctx context.Context, arg BackofficeListUserTeamsParams) ([]BackofficeListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, backofficeListUserTeams, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListUserTeamsRow{}
	for rows.Next() {
		var i BackofficeListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backofficeListUsers = `-- name: BackofficeListUsers :many
SELECT
    id,
    email,
    name,
    email_verified,
    created_at
FROM users
WHERE
    $1::text = ''
    OR email ILIKE '%' || $1::text || '%'
    OR name ILIKE '%' || $1::text || '%'
ORDER BY created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type BackofficeListUsersParams struct {
	Search     string `db:"search" json:"search"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageLimit  int32  `db:"page_limit" json:"page_limit"`
}

type BackofficeListUsersRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         string             `db:"email" json:"email"`
	Name          string             `db:"name" json:"name"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) BackofficeListUsers(ctx context.Context, arg BackofficeListUsersParams) ([]BackofficeListUsersRow, error) {
	rows, err := q.db.Query(ctx, backofficeListUsers, arg.Search, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackofficeListUsersRow{}
	for rows.Next() {
		var i BackofficeListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.EmailVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
