// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeSMSCharge = `-- name: AuthorizeSMSCharge :one
WITH clock AS MATERIALIZED (
    SELECT now() AS priced_at
),
team_record AS MATERIALIZED (
    SELECT team.id, team.status, team.market_code FROM teams AS team
    WHERE team.id = $2
),
pricing_context AS MATERIALIZED (
    SELECT team.id AS team_id,
      CASE WHEN team.market_code = $3::char(2) THEN 'local' ELSE 'intl' END::text AS route_type
    FROM team_record AS team
),
market_record AS MATERIALIZED (
    SELECT market.code, market.currency FROM billing_markets AS market
    JOIN team_record AS team ON team.market_code = market.code
    WHERE market.is_enabled = true
),
entitlement_record AS MATERIALIZED (
    SELECT subscription.id, subscription.team_id, subscription.plan_code AS tier,
      subscription.current_period_start, subscription.current_period_end
    FROM team_subscriptions AS subscription
    WHERE subscription.team_id = $2
      AND subscription.status = 'active'
      AND subscription.current_period_start <= now()
      AND subscription.current_period_end > now()
),
wallet_record AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at, entitlement.tier FROM team_wallets AS wallet
    JOIN entitlement_record AS entitlement ON entitlement.team_id = wallet.team_id
    WHERE wallet.team_id = $2
    FOR UPDATE OF wallet
),
existing_authorization AS MATERIALIZED (
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, fx_rate_id, product_rate_id, billing_market, destination_country, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, subscription_credit_id, full_cost_units, credit_consumed_units, wallet_debit_units, currency, tier, priced_at, created_at FROM usage_authorizations AS usage_auth
    WHERE usage_auth.team_id = $2
      AND usage_auth.product = 'sms' AND usage_auth.meter = 'sms_segment'
      AND usage_auth.reference_id = $4
),
credit_record AS MATERIALIZED (
    SELECT credit.id, credit.subscription_id, credit.subscription_charge_id, credit.team_id, credit.plan_code, credit.billing_market, credit.currency, credit.period_start, credit.period_end, credit.granted_units, credit.consumed_units, credit.created_at, credit.updated_at FROM subscription_credits AS credit
    JOIN entitlement_record AS entitlement
      ON entitlement.id = credit.subscription_id AND entitlement.team_id = credit.team_id
     AND entitlement.current_period_start = credit.period_start
     AND entitlement.current_period_end = credit.period_end
    JOIN wallet_record AS wallet ON wallet.currency = credit.currency
    WHERE credit.consumed_units < credit.granted_units
    LIMIT 1 FOR UPDATE OF credit
),
rate_record AS MATERIALIZED (
    SELECT rate.id, rate.destination_country, rate.route_type, rate.tier, rate.currency, rate.cost_units, rate.effective_from, rate.effective_until, rate.created_at FROM sms_rates AS rate
    CROSS JOIN clock CROSS JOIN pricing_context AS pricing
    JOIN wallet_record AS wallet ON wallet.tier = rate.tier
    WHERE rate.destination_country = $3
      AND rate.route_type = pricing.route_type
      AND rate.effective_from <= clock.priced_at
      AND (rate.effective_until IS NULL OR rate.effective_until > clock.priced_at)
    ORDER BY rate.effective_from DESC LIMIT 1
),
fx_record AS MATERIALIZED (
    SELECT fx.id, fx.base_currency, fx.quote_currency, fx.rate, fx.effective_from, fx.effective_until, fx.created_at FROM fx_rates AS fx CROSS JOIN clock
    JOIN rate_record AS rate ON fx.base_currency = rate.currency
    JOIN wallet_record AS wallet ON fx.quote_currency = wallet.currency
    WHERE rate.currency <> wallet.currency
      AND fx.effective_from <= clock.priced_at
      AND (fx.effective_until IS NULL OR fx.effective_until > clock.priced_at)
    ORDER BY fx.effective_from DESC LIMIT 1
),
priced_plan AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.tier,
      wallet.balance_units, pricing.route_type, rate.id AS sms_rate_id,
      CASE WHEN rate.currency <> wallet.currency THEN fx.id END AS fx_rate_id,
      (rate.id IS NOT NULL AND rate.currency <> wallet.currency AND fx.id IS NULL) AS fx_missing,
      CASE WHEN rate.id IS NULL THEN 0::bigint
           WHEN rate.currency = wallet.currency THEN rate.cost_units::bigint
           WHEN fx.id IS NOT NULL THEN round(rate.cost_units::numeric * fx.rate)::bigint
           ELSE 0::bigint END AS unit_cost_units,
      credit.id AS subscription_credit_id,
      GREATEST(COALESCE(credit.granted_units-credit.consumed_units,0),0)::bigint AS available_credit_units,
      clock.priced_at
    FROM wallet_record AS wallet CROSS JOIN clock CROSS JOIN pricing_context AS pricing
    LEFT JOIN rate_record AS rate ON true LEFT JOIN fx_record AS fx ON true LEFT JOIN credit_record AS credit ON true
),
full_cost_plan AS MATERIALIZED (
    SELECT plan.team_id, plan.billing_market, plan.currency, plan.tier, plan.balance_units, plan.route_type, plan.sms_rate_id, plan.fx_rate_id, plan.fx_missing, plan.unit_cost_units, plan.subscription_credit_id, plan.available_credit_units, plan.priced_at, CASE
      WHEN plan.unit_cost_units > 9223372036854775807 / NULLIF($1::bigint,0) THEN NULL::bigint
      ELSE plan.unit_cost_units * $1::bigint END AS full_cost_units
    FROM priced_plan AS plan
),
charge_plan AS MATERIALIZED (
    SELECT plan.team_id, plan.billing_market, plan.currency, plan.tier, plan.balance_units, plan.route_type, plan.sms_rate_id, plan.fx_rate_id, plan.fx_missing, plan.unit_cost_units, plan.subscription_credit_id, plan.available_credit_units, plan.priced_at, plan.full_cost_units,
      LEAST(COALESCE(plan.full_cost_units,0),plan.available_credit_units)::bigint AS credit_consumed_units,
      GREATEST(COALESCE(plan.full_cost_units,0)-plan.available_credit_units,0)::bigint AS wallet_debit_units
    FROM full_cost_plan AS plan
),
inserted_authorization AS (
    INSERT INTO usage_authorizations (
      team_id,product,meter,reference_id,sms_rate_id,fx_rate_id,billing_market,destination_country,route_type,
      total_quantity,allowance_quantity,billable_quantity,unit_cost_units,amount_units,subscription_credit_id,
      full_cost_units,credit_consumed_units,wallet_debit_units,currency,tier,priced_at
    )
    SELECT plan.team_id,'sms','sms_segment',$4,plan.sms_rate_id,plan.fx_rate_id,
      plan.billing_market,$3,plan.route_type,$1,0,$1,
      plan.unit_cost_units,plan.wallet_debit_units,
      CASE WHEN plan.credit_consumed_units>0 THEN plan.subscription_credit_id END,
      plan.full_cost_units,plan.credit_consumed_units,plan.wallet_debit_units,plan.currency,plan.tier,plan.priced_at
    FROM charge_plan AS plan
    JOIN team_record AS team ON team.id=plan.team_id AND team.status='active'
    JOIN market_record AS market ON market.code=plan.billing_market AND market.currency=plan.currency
    WHERE $1::bigint>0 AND NOT EXISTS(SELECT 1 FROM existing_authorization)
      AND plan.full_cost_units IS NOT NULL AND plan.sms_rate_id IS NOT NULL AND NOT plan.fx_missing
      AND plan.unit_cost_units>0 AND plan.wallet_debit_units<=plan.balance_units
    ON CONFLICT(team_id,product,meter,reference_id) DO NOTHING RETURNING id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, fx_rate_id, product_rate_id, billing_market, destination_country, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, subscription_credit_id, full_cost_units, credit_consumed_units, wallet_debit_units, currency, tier, priced_at, created_at
),
updated_credit AS (
    UPDATE subscription_credits AS credit
    SET consumed_units=credit.consumed_units+usage_auth.credit_consumed_units,updated_at=now()
    FROM inserted_authorization AS usage_auth
    WHERE credit.id=usage_auth.subscription_credit_id AND usage_auth.credit_consumed_units>0
      AND credit.consumed_units+usage_auth.credit_consumed_units<=credit.granted_units
    RETURNING credit.granted_units,credit.consumed_units
),
inserted_ledger AS (
    INSERT INTO wallet_ledger(team_id,usage_authorization_id,amount_units,transaction_type,reference_id)
    SELECT usage_auth.team_id,usage_auth.id,-usage_auth.wallet_debit_units,'usage',usage_auth.reference_id
    FROM inserted_authorization AS usage_auth WHERE usage_auth.wallet_debit_units>0
    RETURNING team_id,amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet SET balance_units=wallet.balance_units+ledger.amount_units,updated_at=now()
    FROM inserted_ledger AS ledger WHERE wallet.team_id=ledger.team_id RETURNING wallet.balance_units
),
resolved_authorization AS MATERIALIZED (
    SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, fx_rate_id, product_rate_id, billing_market, destination_country, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, subscription_credit_id, full_cost_units, credit_consumed_units, wallet_debit_units, currency, tier, priced_at, created_at FROM existing_authorization UNION ALL SELECT id, team_id, product, meter, reference_id, usage_allowance_id, sms_rate_id, fx_rate_id, product_rate_id, billing_market, destination_country, route_type, total_quantity, allowance_quantity, billable_quantity, unit_cost_units, amount_units, subscription_credit_id, full_cost_units, credit_consumed_units, wallet_debit_units, currency, tier, priced_at, created_at FROM inserted_authorization LIMIT 1
)
SELECT CASE
    WHEN NOT EXISTS(SELECT 1 FROM team_record) THEN 'team_not_found'
    WHEN EXISTS(SELECT 1 FROM team_record WHERE status<>'active') THEN 'team_inactive'
    WHEN NOT EXISTS(SELECT 1 FROM market_record) THEN 'unsupported_market'
    WHEN NOT EXISTS(SELECT 1 FROM entitlement_record) THEN 'subscription_unavailable'
    WHEN NOT EXISTS(SELECT 1 FROM wallet_record) THEN 'wallet_not_found'
    WHEN EXISTS(SELECT 1 FROM existing_authorization) THEN 'already_applied'
    WHEN EXISTS(SELECT 1 FROM priced_plan WHERE sms_rate_id IS NULL) THEN 'rate_not_found'
    WHEN EXISTS(SELECT 1 FROM priced_plan WHERE fx_missing) THEN 'fx_rate_not_found'
    WHEN EXISTS(SELECT 1 FROM full_cost_plan WHERE full_cost_units IS NULL) THEN 'amount_overflow'
    WHEN EXISTS(SELECT 1 FROM charge_plan WHERE wallet_debit_units>balance_units) THEN 'insufficient_balance'
    WHEN EXISTS(SELECT 1 FROM inserted_authorization WHERE credit_consumed_units=full_cost_units) THEN 'credit_applied'
    WHEN EXISTS(SELECT 1 FROM inserted_authorization) THEN 'applied' ELSE 'already_applied' END AS outcome,
  COALESCE((SELECT billing_market FROM resolved_authorization),(SELECT billing_market FROM wallet_record),'')::text AS market_code,
  COALESCE((SELECT currency FROM resolved_authorization),(SELECT currency FROM wallet_record),'')::text AS currency,
  COALESCE((SELECT tier FROM resolved_authorization),(SELECT tier FROM wallet_record),'')::text AS tier,
  'sms'::text AS product,
  COALESCE((SELECT unit_cost_units FROM resolved_authorization),0)::bigint AS unit_cost_units,
  $1::bigint AS quantity,
  COALESCE((SELECT amount_units FROM resolved_authorization),0)::bigint AS amount_units,
  COALESCE((SELECT balance_units FROM updated_wallet),(SELECT balance_units FROM wallet_record),0)::bigint AS balance_units,
  (SELECT subscription_credit_id FROM resolved_authorization) AS subscription_credit_id,
  COALESCE((SELECT full_cost_units FROM resolved_authorization),0)::bigint AS full_cost_units,
  COALESCE((SELECT credit_consumed_units FROM resolved_authorization),0)::bigint AS credit_consumed_units,
  COALESCE((SELECT wallet_debit_units FROM resolved_authorization),0)::bigint AS wallet_debit_units,
  COALESCE((SELECT granted_units-consumed_units FROM updated_credit),(SELECT granted_units-consumed_units FROM credit_record),0)::bigint AS remaining_credit_units
`

type AuthorizeSMSChargeParams struct {
	Quantity           int64     `db:"quantity" json:"quantity"`
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
	DestinationCountry string    `db:"destination_country" json:"destination_country"`
	ReferenceID        string    `db:"reference_id" json:"reference_id"`
}

type AuthorizeSMSChargeRow struct {
	Outcome              string     `db:"outcome" json:"outcome"`
	MarketCode           string     `db:"market_code" json:"market_code"`
	Currency             string     `db:"currency" json:"currency"`
	Tier                 string     `db:"tier" json:"tier"`
	Product              string     `db:"product" json:"product"`
	UnitCostUnits        int64      `db:"unit_cost_units" json:"unit_cost_units"`
	Quantity             int64      `db:"quantity" json:"quantity"`
	AmountUnits          int64      `db:"amount_units" json:"amount_units"`
	BalanceUnits         int64      `db:"balance_units" json:"balance_units"`
	SubscriptionCreditID *uuid.UUID `db:"subscription_credit_id" json:"subscription_credit_id"`
	FullCostUnits        int64      `db:"full_cost_units" json:"full_cost_units"`
	CreditConsumedUnits  int64      `db:"credit_consumed_units" json:"credit_consumed_units"`
	WalletDebitUnits     int64      `db:"wallet_debit_units" json:"wallet_debit_units"`
	RemainingCreditUnits int64      `db:"remaining_credit_units" json:"remaining_credit_units"`
}

func (q *Queries) AuthorizeSMSCharge(ctx context.Context, arg AuthorizeSMSChargeParams) (AuthorizeSMSChargeRow, error) {
	row := q.db.QueryRow(ctx, authorizeSMSCharge,
		arg.Quantity,
		arg.TeamID,
		arg.DestinationCountry,
		arg.ReferenceID,
	)
	var i AuthorizeSMSChargeRow
	err := row.Scan(
		&i.Outcome,
		&i.MarketCode,
		&i.Currency,
		&i.Tier,
		&i.Product,
		&i.UnitCostUnits,
		&i.Quantity,
		&i.AmountUnits,
		&i.BalanceUnits,
		&i.SubscriptionCreditID,
		&i.FullCostUnits,
		&i.CreditConsumedUnits,
		&i.WalletDebitUnits,
		&i.RemainingCreditUnits,
	)
	return i, err
}

const creditTeamWallet = `-- name: CreditTeamWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        wallet.team_id,
        $2,
        $3,
        $4
    FROM locked_wallet AS wallet
    WHERE $2::bigint > 0
      AND $3::text <> 'usage'
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at
)
SELECT team_id, billing_market, currency, balance_units, created_at, updated_at
FROM updated_wallet
`

type CreditTeamWalletParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
	TransactionType string    `db:"transaction_type" json:"transaction_type"`
	ReferenceID     string    `db:"reference_id" json:"reference_id"`
}

type CreditTeamWalletRow struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreditTeamWallet(ctx context.Context, arg CreditTeamWalletParams) (CreditTeamWalletRow, error) {
	row := q.db.QueryRow(ctx, creditTeamWallet,
		arg.TeamID,
		arg.AmountUnits,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i CreditTeamWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitTeamWallet = `-- name: DebitTeamWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        wallet.team_id,
        -$2::bigint,
        $3,
        $4
    FROM locked_wallet AS wallet
    WHERE $2::bigint > 0
      AND $3::text <> 'usage'
      AND wallet.balance_units >= $2
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.team_id, wallet.billing_market, wallet.currency, wallet.balance_units, wallet.created_at, wallet.updated_at
)
SELECT team_id, billing_market, currency, balance_units, created_at, updated_at
FROM updated_wallet
`

type DebitTeamWalletParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
	TransactionType string    `db:"transaction_type" json:"transaction_type"`
	ReferenceID     string    `db:"reference_id" json:"reference_id"`
}

type DebitTeamWalletRow struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DebitTeamWallet(ctx context.Context, arg DebitTeamWalletParams) (DebitTeamWalletRow, error) {
	row := q.db.QueryRow(ctx, debitTeamWallet,
		arg.TeamID,
		arg.AmountUnits,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i DebitTeamWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProductRate = `-- name: GetActiveProductRate :one
SELECT id, product, meter, billing_market, tier, currency, cost_units, effective_from, effective_until, created_at
FROM product_rates
WHERE product = $1
  AND meter = $2
  AND billing_market = $3
  AND tier = $4
  AND effective_from <= $5
  AND (effective_until IS NULL OR effective_until > $5)
ORDER BY effective_from DESC
LIMIT 1
`

type GetActiveProductRateParams struct {
	Product       string             `db:"product" json:"product"`
	Meter         string             `db:"meter" json:"meter"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Tier          string             `db:"tier" json:"tier"`
	PricedAt      pgtype.Timestamptz `db:"priced_at" json:"priced_at"`
}

func (q *Queries) GetActiveProductRate(ctx context.Context, arg GetActiveProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, getActiveProductRate,
		arg.Product,
		arg.Meter,
		arg.BillingMarket,
		arg.Tier,
		arg.PricedAt,
	)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Meter,
		&i.BillingMarket,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamWallet = `-- name: GetTeamWallet :one
SELECT team_id, billing_market, currency, balance_units, created_at, updated_at
FROM team_wallets
WHERE team_id = $1
`

type GetTeamWalletParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetTeamWallet(ctx context.Context, arg GetTeamWalletParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, getTeamWallet, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.BillingMarket,
		&i.Currency,
		&i.BalanceUnits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletLedger = `-- name: ListWalletLedger :many
SELECT id, team_id, usage_authorization_id, subscription_charge_id, payment_transaction_id, amount_units, transaction_type, reference_id, created_at
FROM wallet_ledger
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListWalletLedgerParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWalletLedger(ctx context.Context, arg ListWalletLedgerParams) ([]WalletLedger, error) {
	rows, err := q.db.Query(ctx, listWalletLedger, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletLedger{}
	for rows.Next() {
		var i WalletLedger
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UsageAuthorizationID,
			&i.SubscriptionChargeID,
			&i.PaymentTransactionID,
			&i.AmountUnits,
			&i.TransactionType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
