// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcast_recipients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextBroadcastRecipientForFanout = `-- name: ClaimNextBroadcastRecipientForFanout :one
SELECT
    recipient.id, recipient.team_id, recipient.broadcast_id, recipient.contact_id, recipient.email, recipient.normalized_email, recipient.first_name, recipient.last_name, recipient.contact_snapshot, recipient.status, recipient.exclusion_reason, recipient.email_message_id, recipient.attempt_count, recipient.next_attempt_at, recipient.last_error_code, recipient.last_error_message, recipient.failed_at, recipient.created_at, recipient.queued_at,
    broadcast.template_id,
    broadcast.template_version_id,
    broadcast.variable_bindings
FROM broadcast_recipients AS recipient
JOIN broadcasts AS broadcast
  ON broadcast.id = recipient.broadcast_id
 AND broadcast.team_id = recipient.team_id
WHERE recipient.status = 'pending'
  AND (recipient.next_attempt_at IS NULL OR recipient.next_attempt_at <= now())
  AND broadcast.status = 'queued'
  AND broadcast.recipients_materialized_at IS NOT NULL
  AND broadcast.template_version_id IS NOT NULL
  AND broadcast.deleted_at IS NULL
ORDER BY recipient.next_attempt_at NULLS FIRST, recipient.broadcast_id, recipient.id
FOR UPDATE OF recipient SKIP LOCKED
LIMIT 1
`

type ClaimNextBroadcastRecipientForFanoutRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	BroadcastID       uuid.UUID          `db:"broadcast_id" json:"broadcast_id"`
	ContactID         *uuid.UUID         `db:"contact_id" json:"contact_id"`
	Email             string             `db:"email" json:"email"`
	NormalizedEmail   string             `db:"normalized_email" json:"normalized_email"`
	FirstName         *string            `db:"first_name" json:"first_name"`
	LastName          *string            `db:"last_name" json:"last_name"`
	ContactSnapshot   []byte             `db:"contact_snapshot" json:"contact_snapshot"`
	Status            string             `db:"status" json:"status"`
	ExclusionReason   *string            `db:"exclusion_reason" json:"exclusion_reason"`
	EmailMessageID    *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	AttemptCount      int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt     pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastErrorCode     *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage  *string            `db:"last_error_message" json:"last_error_message"`
	FailedAt          pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	QueuedAt          pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	TemplateID        uuid.UUID          `db:"template_id" json:"template_id"`
	TemplateVersionID *uuid.UUID         `db:"template_version_id" json:"template_version_id"`
	VariableBindings  []byte             `db:"variable_bindings" json:"variable_bindings"`
}

func (q *Queries) ClaimNextBroadcastRecipientForFanout(ctx context.Context) (ClaimNextBroadcastRecipientForFanoutRow, error) {
	row := q.db.QueryRow(ctx, claimNextBroadcastRecipientForFanout)
	var i ClaimNextBroadcastRecipientForFanoutRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.FailedAt,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.TemplateID,
		&i.TemplateVersionID,
		&i.VariableBindings,
	)
	return i, err
}

const countBroadcastRecipientFanoutState = `-- name: CountBroadcastRecipientFanoutState :one
SELECT
    count(*) FILTER (WHERE status = 'pending') AS pending_count,
    count(*) FILTER (WHERE status = 'queued') AS queued_count,
    count(*) FILTER (WHERE status = 'failed') AS failed_count
FROM broadcast_recipients
WHERE team_id = $1
  AND broadcast_id = $2
`

type CountBroadcastRecipientFanoutStateParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	BroadcastID uuid.UUID `db:"broadcast_id" json:"broadcast_id"`
}

type CountBroadcastRecipientFanoutStateRow struct {
	PendingCount int64 `db:"pending_count" json:"pending_count"`
	QueuedCount  int64 `db:"queued_count" json:"queued_count"`
	FailedCount  int64 `db:"failed_count" json:"failed_count"`
}

func (q *Queries) CountBroadcastRecipientFanoutState(ctx context.Context, arg CountBroadcastRecipientFanoutStateParams) (CountBroadcastRecipientFanoutStateRow, error) {
	row := q.db.QueryRow(ctx, countBroadcastRecipientFanoutState, arg.TeamID, arg.BroadcastID)
	var i CountBroadcastRecipientFanoutStateRow
	err := row.Scan(&i.PendingCount, &i.QueuedCount, &i.FailedCount)
	return i, err
}

const createBroadcastRecipient = `-- name: CreateBroadcastRecipient :one
INSERT INTO broadcast_recipients (
    team_id, broadcast_id, contact_id, email, normalized_email,
    first_name, last_name, contact_snapshot, status, exclusion_reason
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
RETURNING id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, attempt_count, next_attempt_at, last_error_code, last_error_message, failed_at, created_at, queued_at
`

type CreateBroadcastRecipientParams struct {
	TeamID          uuid.UUID  `db:"team_id" json:"team_id"`
	BroadcastID     uuid.UUID  `db:"broadcast_id" json:"broadcast_id"`
	ContactID       *uuid.UUID `db:"contact_id" json:"contact_id"`
	Email           string     `db:"email" json:"email"`
	NormalizedEmail string     `db:"normalized_email" json:"normalized_email"`
	FirstName       *string    `db:"first_name" json:"first_name"`
	LastName        *string    `db:"last_name" json:"last_name"`
	ContactSnapshot []byte     `db:"contact_snapshot" json:"contact_snapshot"`
	Status          string     `db:"status" json:"status"`
	ExclusionReason *string    `db:"exclusion_reason" json:"exclusion_reason"`
}

func (q *Queries) CreateBroadcastRecipient(ctx context.Context, arg CreateBroadcastRecipientParams) (BroadcastRecipient, error) {
	row := q.db.QueryRow(ctx, createBroadcastRecipient,
		arg.TeamID,
		arg.BroadcastID,
		arg.ContactID,
		arg.Email,
		arg.NormalizedEmail,
		arg.FirstName,
		arg.LastName,
		arg.ContactSnapshot,
		arg.Status,
		arg.ExclusionReason,
	)
	var i BroadcastRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.FailedAt,
		&i.CreatedAt,
		&i.QueuedAt,
	)
	return i, err
}

const failBroadcastRecipientFanout = `-- name: FailBroadcastRecipientFanout :one
UPDATE broadcast_recipients
SET status = 'failed',
    attempt_count = attempt_count + 1,
    next_attempt_at = NULL,
    last_error_code = $1,
    last_error_message = $2,
    failed_at = now()
WHERE id = $3
  AND team_id = $4
  AND broadcast_id = $5
  AND status = 'pending'
RETURNING id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, attempt_count, next_attempt_at, last_error_code, last_error_message, failed_at, created_at, queued_at
`

type FailBroadcastRecipientFanoutParams struct {
	ErrorCode    *string   `db:"error_code" json:"error_code"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	BroadcastID  uuid.UUID `db:"broadcast_id" json:"broadcast_id"`
}

func (q *Queries) FailBroadcastRecipientFanout(ctx context.Context, arg FailBroadcastRecipientFanoutParams) (BroadcastRecipient, error) {
	row := q.db.QueryRow(ctx, failBroadcastRecipientFanout,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.TeamID,
		arg.BroadcastID,
	)
	var i BroadcastRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.FailedAt,
		&i.CreatedAt,
		&i.QueuedAt,
	)
	return i, err
}

const getBroadcastExclusionSummary = `-- name: GetBroadcastExclusionSummary :many
SELECT COALESCE(NULLIF(btrim(exclusion_reason), ''), 'unknown')::text AS reason,
       count(*) AS recipient_count
FROM broadcast_recipients
WHERE team_id = $1
  AND broadcast_id = $2
  AND status = 'excluded'
GROUP BY reason
ORDER BY reason
`

type GetBroadcastExclusionSummaryParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	BroadcastID uuid.UUID `db:"broadcast_id" json:"broadcast_id"`
}

type GetBroadcastExclusionSummaryRow struct {
	Reason         string `db:"reason" json:"reason"`
	RecipientCount int64  `db:"recipient_count" json:"recipient_count"`
}

func (q *Queries) GetBroadcastExclusionSummary(ctx context.Context, arg GetBroadcastExclusionSummaryParams) ([]GetBroadcastExclusionSummaryRow, error) {
	rows, err := q.db.Query(ctx, getBroadcastExclusionSummary, arg.TeamID, arg.BroadcastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBroadcastExclusionSummaryRow{}
	for rows.Next() {
		var i GetBroadcastExclusionSummaryRow
		if err := rows.Scan(&i.Reason, &i.RecipientCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcastRecipients = `-- name: ListBroadcastRecipients :many
SELECT id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, attempt_count, next_attempt_at, last_error_code, last_error_message, failed_at, created_at, queued_at
FROM broadcast_recipients
WHERE team_id = $1
  AND broadcast_id = $2
ORDER BY created_at ASC, id ASC
LIMIT $4
OFFSET $3
`

type ListBroadcastRecipientsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	BroadcastID uuid.UUID `db:"broadcast_id" json:"broadcast_id"`
	PageOffset  int32     `db:"page_offset" json:"page_offset"`
	PageLimit   int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListBroadcastRecipients(ctx context.Context, arg ListBroadcastRecipientsParams) ([]BroadcastRecipient, error) {
	rows, err := q.db.Query(ctx, listBroadcastRecipients,
		arg.TeamID,
		arg.BroadcastID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BroadcastRecipient{}
	for rows.Next() {
		var i BroadcastRecipient
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BroadcastID,
			&i.ContactID,
			&i.Email,
			&i.NormalizedEmail,
			&i.FirstName,
			&i.LastName,
			&i.ContactSnapshot,
			&i.Status,
			&i.ExclusionReason,
			&i.EmailMessageID,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.FailedAt,
			&i.CreatedAt,
			&i.QueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materializeBroadcastRecipients = `-- name: MaterializeBroadcastRecipients :exec
WITH candidates AS (
    SELECT
        contact.id AS contact_id,
        contact.email,
        lower(btrim(contact.email)) AS normalized_email,
        contact.first_name,
        contact.last_name,
        jsonb_build_object(
            'id', contact.id,
            'email', contact.email,
            'first_name', contact.first_name,
            'last_name', contact.last_name,
            'properties', COALESCE(properties.values, '{}'::jsonb)
        ) AS contact_snapshot,
        CASE
            WHEN contact.email !~* '^[A-Z0-9.!#$%&''*+/=?^_{|}~-]+@[A-Z0-9]([A-Z0-9-]{0,61}[A-Z0-9])?(\.[A-Z0-9]([A-Z0-9-]{0,61}[A-Z0-9])?)+$'
                THEN 'invalid_email'
            WHEN contact.unsubscribed THEN 'global_unsubscribe'
            WHEN EXISTS (
                SELECT 1
                FROM channel_suppressions AS suppression
                WHERE suppression.team_id = contact.team_id
                  AND suppression.channel = 'email'
                  AND suppression.normalized_address = lower(btrim(contact.email))
            ) THEN 'suppressed'
            WHEN $3::uuid IS NOT NULL
             AND COALESCE(subscription.subscription, topic.default_subscription) = 'opt_out'
                THEN 'topic_unsubscribed'
            ELSE NULL
        END AS exclusion_reason
    FROM contact_segments AS membership
    JOIN contacts AS contact
      ON contact.id = membership.contact_id
     AND contact.team_id = membership.team_id
    LEFT JOIN topics AS topic
      ON topic.id = $3
     AND topic.team_id = contact.team_id
    LEFT JOIN contact_topic_subscriptions AS subscription
      ON subscription.contact_id = contact.id
     AND subscription.topic_id = $3
     AND subscription.team_id = contact.team_id
    LEFT JOIN LATERAL (
        SELECT jsonb_object_agg(
            property.key,
            CASE property_value.value_type
                WHEN 'string' THEN to_jsonb(property_value.string_value)
                WHEN 'number' THEN to_jsonb(property_value.number_value)
            END
        ) AS values
        FROM contact_property_values AS property_value
        JOIN contact_properties AS property
          ON property.id = property_value.contact_property_id
         AND property.team_id = property_value.team_id
        WHERE property_value.contact_id = contact.id
          AND property_value.team_id = contact.team_id
    ) AS properties ON true
    WHERE membership.team_id = $1
      AND membership.segment_id = $4
)
INSERT INTO broadcast_recipients (
    team_id, broadcast_id, contact_id, email, normalized_email,
    first_name, last_name, contact_snapshot, status, exclusion_reason
)
SELECT
    $1,
    $2,
    contact_id,
    email,
    normalized_email,
    first_name,
    last_name,
    contact_snapshot,
    CASE WHEN exclusion_reason IS NULL THEN 'pending' ELSE 'excluded' END,
    exclusion_reason
FROM candidates
ON CONFLICT DO NOTHING
`

type MaterializeBroadcastRecipientsParams struct {
	TeamID      uuid.UUID  `db:"team_id" json:"team_id"`
	BroadcastID uuid.UUID  `db:"broadcast_id" json:"broadcast_id"`
	TopicID     *uuid.UUID `db:"topic_id" json:"topic_id"`
	SegmentID   uuid.UUID  `db:"segment_id" json:"segment_id"`
}

func (q *Queries) MaterializeBroadcastRecipients(ctx context.Context, arg MaterializeBroadcastRecipientsParams) error {
	_, err := q.db.Exec(ctx, materializeBroadcastRecipients,
		arg.TeamID,
		arg.BroadcastID,
		arg.TopicID,
		arg.SegmentID,
	)
	return err
}

const recheckBroadcastRecipientEligibility = `-- name: RecheckBroadcastRecipientEligibility :one
WITH eligibility AS (
    SELECT CASE
        WHEN contact.id IS NULL THEN 'contact_unavailable'
        WHEN contact.unsubscribed THEN 'global_unsubscribe'
        WHEN EXISTS (
            SELECT 1 FROM channel_suppressions AS suppression
            WHERE suppression.team_id = recipient.team_id
              AND suppression.channel = 'email'
              AND suppression.normalized_address = recipient.normalized_email
        ) THEN 'suppressed'
        WHEN broadcast.topic_id IS NOT NULL
         AND COALESCE(subscription.subscription, topic.default_subscription) = 'opt_out'
            THEN 'topic_unsubscribed'
        ELSE NULL
    END AS reason
    FROM broadcast_recipients AS recipient
    JOIN broadcasts AS broadcast ON broadcast.id = recipient.broadcast_id AND broadcast.team_id = recipient.team_id
    LEFT JOIN contacts AS contact ON contact.id = recipient.contact_id AND contact.team_id = recipient.team_id
    LEFT JOIN topics AS topic ON topic.id = broadcast.topic_id AND topic.team_id = recipient.team_id
    LEFT JOIN contact_topic_subscriptions AS subscription
      ON subscription.contact_id = contact.id
     AND subscription.topic_id = broadcast.topic_id
     AND subscription.team_id = recipient.team_id
    WHERE recipient.id = $3
      AND recipient.team_id = $2
      AND recipient.broadcast_id = $1
      AND recipient.status = 'pending'
), excluded AS (
    UPDATE broadcast_recipients
    SET status = 'excluded', exclusion_reason = eligibility.reason, next_attempt_at = NULL
    FROM eligibility
    WHERE id = $3
      AND team_id = $2
      AND broadcast_id = $1
      AND status = 'pending'
      AND eligibility.reason IS NOT NULL
    RETURNING exclusion_reason
)
UPDATE broadcasts AS broadcast
SET eligible_count = GREATEST(broadcast.eligible_count - 1, 0),
    suppressed_count = broadcast.suppressed_count + 1,
    updated_at = now()
FROM excluded
WHERE broadcast.id = $1
  AND broadcast.team_id = $2
  AND broadcast.status = 'queued'
RETURNING excluded.exclusion_reason
`

type RecheckBroadcastRecipientEligibilityParams struct {
	BroadcastID uuid.UUID `db:"broadcast_id" json:"broadcast_id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	ID          uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) RecheckBroadcastRecipientEligibility(ctx context.Context, arg RecheckBroadcastRecipientEligibilityParams) (*string, error) {
	row := q.db.QueryRow(ctx, recheckBroadcastRecipientEligibility, arg.BroadcastID, arg.TeamID, arg.ID)
	var exclusion_reason *string
	err := row.Scan(&exclusion_reason)
	return exclusion_reason, err
}

const retryBroadcastRecipientFanout = `-- name: RetryBroadcastRecipientFanout :one
UPDATE broadcast_recipients
SET attempt_count = attempt_count + 1,
    next_attempt_at = $1,
    last_error_code = $2,
    last_error_message = $3
WHERE id = $4
  AND team_id = $5
  AND broadcast_id = $6
  AND status = 'pending'
RETURNING id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, attempt_count, next_attempt_at, last_error_code, last_error_message, failed_at, created_at, queued_at
`

type RetryBroadcastRecipientFanoutParams struct {
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	ErrorCode     *string            `db:"error_code" json:"error_code"`
	ErrorMessage  *string            `db:"error_message" json:"error_message"`
	ID            uuid.UUID          `db:"id" json:"id"`
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BroadcastID   uuid.UUID          `db:"broadcast_id" json:"broadcast_id"`
}

func (q *Queries) RetryBroadcastRecipientFanout(ctx context.Context, arg RetryBroadcastRecipientFanoutParams) (BroadcastRecipient, error) {
	row := q.db.QueryRow(ctx, retryBroadcastRecipientFanout,
		arg.NextAttemptAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.TeamID,
		arg.BroadcastID,
	)
	var i BroadcastRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.FailedAt,
		&i.CreatedAt,
		&i.QueuedAt,
	)
	return i, err
}

const setBroadcastRecipientQueued = `-- name: SetBroadcastRecipientQueued :one
UPDATE broadcast_recipients
SET status = 'queued',
    email_message_id = $1,
    queued_at = now(),
    next_attempt_at = NULL,
    last_error_code = NULL,
    last_error_message = NULL
WHERE id = $2
  AND team_id = $3
  AND broadcast_id = $4
  AND status = 'pending'
RETURNING id, team_id, broadcast_id, contact_id, email, normalized_email, first_name, last_name, contact_snapshot, status, exclusion_reason, email_message_id, attempt_count, next_attempt_at, last_error_code, last_error_message, failed_at, created_at, queued_at
`

type SetBroadcastRecipientQueuedParams struct {
	EmailMessageID *uuid.UUID `db:"email_message_id" json:"email_message_id"`
	ID             uuid.UUID  `db:"id" json:"id"`
	TeamID         uuid.UUID  `db:"team_id" json:"team_id"`
	BroadcastID    uuid.UUID  `db:"broadcast_id" json:"broadcast_id"`
}

func (q *Queries) SetBroadcastRecipientQueued(ctx context.Context, arg SetBroadcastRecipientQueuedParams) (BroadcastRecipient, error) {
	row := q.db.QueryRow(ctx, setBroadcastRecipientQueued,
		arg.EmailMessageID,
		arg.ID,
		arg.TeamID,
		arg.BroadcastID,
	)
	var i BroadcastRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BroadcastID,
		&i.ContactID,
		&i.Email,
		&i.NormalizedEmail,
		&i.FirstName,
		&i.LastName,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.EmailMessageID,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.FailedAt,
		&i.CreatedAt,
		&i.QueuedAt,
	)
	return i, err
}
