// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_properties.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const contactPropertyCursorExists = `-- name: ContactPropertyCursorExists :one
SELECT EXISTS (
    SELECT 1
    FROM contact_properties
    WHERE id = $1
      AND team_id = $2
)
`

type ContactPropertyCursorExistsParams struct {
	CursorID uuid.UUID `db:"cursor_id" json:"cursor_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ContactPropertyCursorExists(ctx context.Context, arg ContactPropertyCursorExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactPropertyCursorExists, arg.CursorID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createContactProperty = `-- name: CreateContactProperty :one
INSERT INTO contact_properties (
    team_id,
    key,
    value_type,
    fallback_string,
    fallback_number
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
`

type CreateContactPropertyParams struct {
	TeamID         uuid.UUID      `db:"team_id" json:"team_id"`
	Key            string         `db:"key" json:"key"`
	ValueType      string         `db:"value_type" json:"value_type"`
	FallbackString *string        `db:"fallback_string" json:"fallback_string"`
	FallbackNumber pgtype.Numeric `db:"fallback_number" json:"fallback_number"`
}

func (q *Queries) CreateContactProperty(ctx context.Context, arg CreateContactPropertyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, createContactProperty,
		arg.TeamID,
		arg.Key,
		arg.ValueType,
		arg.FallbackString,
		arg.FallbackNumber,
	)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContactProperty = `-- name: DeleteContactProperty :one
DELETE FROM contact_properties
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
`

type DeleteContactPropertyParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteContactProperty(ctx context.Context, arg DeleteContactPropertyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, deleteContactProperty, arg.ID, arg.TeamID)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactProperty = `-- name: GetContactProperty :one
SELECT id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
FROM contact_properties
WHERE id = $1
  AND team_id = $2
`

type GetContactPropertyParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetContactProperty(ctx context.Context, arg GetContactPropertyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, getContactProperty, arg.ID, arg.TeamID)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactPropertyByKey = `-- name: GetContactPropertyByKey :one
SELECT id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
FROM contact_properties
WHERE key = $1
  AND team_id = $2
`

type GetContactPropertyByKeyParams struct {
	Key    string    `db:"key" json:"key"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetContactPropertyByKey(ctx context.Context, arg GetContactPropertyByKeyParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, getContactPropertyByKey, arg.Key, arg.TeamID)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactProperties = `-- name: ListContactProperties :many
SELECT id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
FROM contact_properties
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListContactPropertiesParams struct {
	TeamID    uuid.UUID `db:"team_id" json:"team_id"`
	PageLimit int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListContactProperties(ctx context.Context, arg ListContactPropertiesParams) ([]ContactProperty, error) {
	rows, err := q.db.Query(ctx, listContactProperties, arg.TeamID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactProperty{}
	for rows.Next() {
		var i ContactProperty
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.ValueType,
			&i.FallbackString,
			&i.FallbackNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactPropertiesAfter = `-- name: ListContactPropertiesAfter :many
SELECT property.id, property.team_id, property.key, property.value_type, property.fallback_string, property.fallback_number, property.created_at, property.updated_at
FROM contact_properties AS property
WHERE property.team_id = $1
  AND (property.created_at, property.id) < (
      SELECT cursor_property.created_at, cursor_property.id
      FROM contact_properties AS cursor_property
      WHERE cursor_property.id = $2
        AND cursor_property.team_id = $1
  )
ORDER BY property.created_at DESC, property.id DESC
LIMIT $3
`

type ListContactPropertiesAfterParams struct {
	ScopeTeamID uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	CursorID    uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit   int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListContactPropertiesAfter(ctx context.Context, arg ListContactPropertiesAfterParams) ([]ContactProperty, error) {
	rows, err := q.db.Query(ctx, listContactPropertiesAfter, arg.ScopeTeamID, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactProperty{}
	for rows.Next() {
		var i ContactProperty
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.ValueType,
			&i.FallbackString,
			&i.FallbackNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactPropertiesBefore = `-- name: ListContactPropertiesBefore :many
SELECT property.id, property.team_id, property.key, property.value_type, property.fallback_string, property.fallback_number, property.created_at, property.updated_at
FROM contact_properties AS property
WHERE property.team_id = $1
  AND (property.created_at, property.id) > (
      SELECT cursor_property.created_at, cursor_property.id
      FROM contact_properties AS cursor_property
      WHERE cursor_property.id = $2
        AND cursor_property.team_id = $1
  )
ORDER BY property.created_at ASC, property.id ASC
LIMIT $3
`

type ListContactPropertiesBeforeParams struct {
	ScopeTeamID uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	CursorID    uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit   int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListContactPropertiesBefore(ctx context.Context, arg ListContactPropertiesBeforeParams) ([]ContactProperty, error) {
	rows, err := q.db.Query(ctx, listContactPropertiesBefore, arg.ScopeTeamID, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactProperty{}
	for rows.Next() {
		var i ContactProperty
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.ValueType,
			&i.FallbackString,
			&i.FallbackNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactPropertyFallback = `-- name: UpdateContactPropertyFallback :one
UPDATE contact_properties
SET fallback_string = $1,
    fallback_number = $2,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
RETURNING id, team_id, key, value_type, fallback_string, fallback_number, created_at, updated_at
`

type UpdateContactPropertyFallbackParams struct {
	FallbackString *string        `db:"fallback_string" json:"fallback_string"`
	FallbackNumber pgtype.Numeric `db:"fallback_number" json:"fallback_number"`
	ID             uuid.UUID      `db:"id" json:"id"`
	TeamID         uuid.UUID      `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateContactPropertyFallback(ctx context.Context, arg UpdateContactPropertyFallbackParams) (ContactProperty, error) {
	row := q.db.QueryRow(ctx, updateContactPropertyFallback,
		arg.FallbackString,
		arg.FallbackNumber,
		arg.ID,
		arg.TeamID,
	)
	var i ContactProperty
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.ValueType,
		&i.FallbackString,
		&i.FallbackNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
