// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const contactTopicCursorExists = `-- name: ContactTopicCursorExists :one
SELECT EXISTS (
    SELECT 1
    FROM topics
    WHERE id = $1
      AND team_id = $2
)
`

type ContactTopicCursorExistsParams struct {
	CursorID uuid.UUID `db:"cursor_id" json:"cursor_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ContactTopicCursorExists(ctx context.Context, arg ContactTopicCursorExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactTopicCursorExists, arg.CursorID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    team_id,
    email,
    phone,
    normalized_phone,
    phone_country,
    first_name,
    last_name,
    unsubscribed,
    sms_consent_status,
    sms_consent_updated_at,
    sms_consent_source
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    CASE WHEN $9 = 'unknown' THEN NULL ELSE now() END,
    $10
)
RETURNING id, team_id, email, first_name, last_name, unsubscribed, phone, normalized_phone, phone_country, sms_consent_status, sms_consent_updated_at, sms_consent_source, created_at, updated_at
`

type CreateContactParams struct {
	TeamID           uuid.UUID `db:"team_id" json:"team_id"`
	Email            string    `db:"email" json:"email"`
	Phone            *string   `db:"phone" json:"phone"`
	NormalizedPhone  *string   `db:"normalized_phone" json:"normalized_phone"`
	PhoneCountry     *string   `db:"phone_country" json:"phone_country"`
	FirstName        *string   `db:"first_name" json:"first_name"`
	LastName         *string   `db:"last_name" json:"last_name"`
	Unsubscribed     bool      `db:"unsubscribed" json:"unsubscribed"`
	SmsConsentStatus string    `db:"sms_consent_status" json:"sms_consent_status"`
	SmsConsentSource *string   `db:"sms_consent_source" json:"sms_consent_source"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.TeamID,
		arg.Email,
		arg.Phone,
		arg.NormalizedPhone,
		arg.PhoneCountry,
		arg.FirstName,
		arg.LastName,
		arg.Unsubscribed,
		arg.SmsConsentStatus,
		arg.SmsConsentSource,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.Phone,
		&i.NormalizedPhone,
		&i.PhoneCountry,
		&i.SmsConsentStatus,
		&i.SmsConsentUpdatedAt,
		&i.SmsConsentSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :one
DELETE FROM contacts
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, email, first_name, last_name, unsubscribed, phone, normalized_phone, phone_country, sms_consent_status, sms_consent_updated_at, sms_consent_source, created_at, updated_at
`

type DeleteContactParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, deleteContact, arg.ID, arg.TeamID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.Phone,
		&i.NormalizedPhone,
		&i.PhoneCountry,
		&i.SmsConsentStatus,
		&i.SmsConsentUpdatedAt,
		&i.SmsConsentSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContactPropertyValues = `-- name: DeleteContactPropertyValues :exec
DELETE FROM contact_property_values
WHERE team_id = $1
  AND contact_id = $2
`

type DeleteContactPropertyValuesParams struct {
	TeamID    uuid.UUID `db:"team_id" json:"team_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
}

func (q *Queries) DeleteContactPropertyValues(ctx context.Context, arg DeleteContactPropertyValuesParams) error {
	_, err := q.db.Exec(ctx, deleteContactPropertyValues, arg.TeamID, arg.ContactID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, team_id, email, first_name, last_name, unsubscribed, phone, normalized_phone, phone_country, sms_consent_status, sms_consent_updated_at, sms_consent_source, created_at, updated_at
FROM contacts
WHERE id = $1
  AND team_id = $2
`

type GetContactParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.TeamID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.Phone,
		&i.NormalizedPhone,
		&i.PhoneCountry,
		&i.SmsConsentStatus,
		&i.SmsConsentUpdatedAt,
		&i.SmsConsentSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByEmail = `-- name: GetContactByEmail :one
SELECT id, team_id, email, first_name, last_name, unsubscribed, phone, normalized_phone, phone_country, sms_consent_status, sms_consent_updated_at, sms_consent_source, created_at, updated_at
FROM contacts
WHERE team_id = $1
  AND lower(email) = lower($2)
`

type GetContactByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) GetContactByEmail(ctx context.Context, arg GetContactByEmailParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByEmail, arg.TeamID, arg.Email)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.Phone,
		&i.NormalizedPhone,
		&i.PhoneCountry,
		&i.SmsConsentStatus,
		&i.SmsConsentUpdatedAt,
		&i.SmsConsentSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactPropertyValues = `-- name: ListContactPropertyValues :many
SELECT
    cpv.contact_id,
    cp.key,
    cp.value_type,
    cpv.string_value,
    cpv.number_value
FROM contact_property_values AS cpv
JOIN contact_properties AS cp
  ON cp.id = cpv.contact_property_id
 AND cp.team_id = cpv.team_id
WHERE cpv.team_id = $1
  AND cpv.contact_id = $2
ORDER BY cp.key
`

type ListContactPropertyValuesParams struct {
	TeamID    uuid.UUID `db:"team_id" json:"team_id"`
	ContactID uuid.UUID `db:"contact_id" json:"contact_id"`
}

type ListContactPropertyValuesRow struct {
	ContactID   uuid.UUID      `db:"contact_id" json:"contact_id"`
	Key         string         `db:"key" json:"key"`
	ValueType   string         `db:"value_type" json:"value_type"`
	StringValue *string        `db:"string_value" json:"string_value"`
	NumberValue pgtype.Numeric `db:"number_value" json:"number_value"`
}

func (q *Queries) ListContactPropertyValues(ctx context.Context, arg ListContactPropertyValuesParams) ([]ListContactPropertyValuesRow, error) {
	rows, err := q.db.Query(ctx, listContactPropertyValues, arg.TeamID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactPropertyValuesRow{}
	for rows.Next() {
		var i ListContactPropertyValuesRow
		if err := rows.Scan(
			&i.ContactID,
			&i.Key,
			&i.ValueType,
			&i.StringValue,
			&i.NumberValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactTopics = `-- name: ListContactTopics :many
SELECT
    topic.id,
    topic.name,
    topic.description,
    COALESCE(subscription.subscription, topic.default_subscription) AS subscription
FROM topics AS topic
LEFT JOIN contact_topic_subscriptions AS subscription
  ON subscription.team_id = topic.team_id
 AND subscription.topic_id = topic.id
 AND subscription.contact_id = $1
WHERE topic.team_id = $2
ORDER BY topic.created_at DESC, topic.id DESC
LIMIT $3
`

type ListContactTopicsParams struct {
	ScopeContactID uuid.UUID `db:"scope_contact_id" json:"scope_contact_id"`
	ScopeTeamID    uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

type ListContactTopicsRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) ListContactTopics(ctx context.Context, arg ListContactTopicsParams) ([]ListContactTopicsRow, error) {
	rows, err := q.db.Query(ctx, listContactTopics, arg.ScopeContactID, arg.ScopeTeamID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTopicsRow{}
	for rows.Next() {
		var i ListContactTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Subscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactTopicsAfter = `-- name: ListContactTopicsAfter :many
SELECT
    topic.id,
    topic.name,
    topic.description,
    COALESCE(subscription.subscription, topic.default_subscription) AS subscription
FROM topics AS topic
LEFT JOIN contact_topic_subscriptions AS subscription
  ON subscription.team_id = topic.team_id
 AND subscription.topic_id = topic.id
 AND subscription.contact_id = $1
WHERE topic.team_id = $2
  AND (topic.created_at, topic.id) < (
      SELECT cursor_topic.created_at, cursor_topic.id
      FROM topics AS cursor_topic
      WHERE cursor_topic.id = $3
        AND cursor_topic.team_id = $2
  )
ORDER BY topic.created_at DESC, topic.id DESC
LIMIT $4
`

type ListContactTopicsAfterParams struct {
	ScopeContactID uuid.UUID `db:"scope_contact_id" json:"scope_contact_id"`
	ScopeTeamID    uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	CursorID       uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

type ListContactTopicsAfterRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) ListContactTopicsAfter(ctx context.Context, arg ListContactTopicsAfterParams) ([]ListContactTopicsAfterRow, error) {
	rows, err := q.db.Query(ctx, listContactTopicsAfter,
		arg.ScopeContactID,
		arg.ScopeTeamID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTopicsAfterRow{}
	for rows.Next() {
		var i ListContactTopicsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Subscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactTopicsBefore = `-- name: ListContactTopicsBefore :many
SELECT
    topic.id,
    topic.name,
    topic.description,
    COALESCE(subscription.subscription, topic.default_subscription) AS subscription
FROM topics AS topic
LEFT JOIN contact_topic_subscriptions AS subscription
  ON subscription.team_id = topic.team_id
 AND subscription.topic_id = topic.id
 AND subscription.contact_id = $1
WHERE topic.team_id = $2
  AND (topic.created_at, topic.id) > (
      SELECT cursor_topic.created_at, cursor_topic.id
      FROM topics AS cursor_topic
      WHERE cursor_topic.id = $3
        AND cursor_topic.team_id = $2
  )
ORDER BY topic.created_at ASC, topic.id ASC
LIMIT $4
`

type ListContactTopicsBeforeParams struct {
	ScopeContactID uuid.UUID `db:"scope_contact_id" json:"scope_contact_id"`
	ScopeTeamID    uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	CursorID       uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

type ListContactTopicsBeforeRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Description  *string   `db:"description" json:"description"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) ListContactTopicsBefore(ctx context.Context, arg ListContactTopicsBeforeParams) ([]ListContactTopicsBeforeRow, error) {
	rows, err := q.db.Query(ctx, listContactTopicsBefore,
		arg.ScopeContactID,
		arg.ScopeTeamID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTopicsBeforeRow{}
	for rows.Next() {
		var i ListContactTopicsBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Subscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, team_id, email, first_name, last_name, unsubscribed, phone, normalized_phone, phone_country, sms_consent_status, sms_consent_updated_at, sms_consent_source, created_at, updated_at
FROM contacts
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListContactsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Unsubscribed,
			&i.Phone,
			&i.NormalizedPhone,
			&i.PhoneCountry,
			&i.SmsConsentStatus,
			&i.SmsConsentUpdatedAt,
			&i.SmsConsentSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET email = $1,
    phone = $2,
    normalized_phone = $3,
    phone_country = $4,
    first_name = $5,
    last_name = $6,
    unsubscribed = $7,
    sms_consent_updated_at = CASE
        WHEN sms_consent_status IS DISTINCT FROM $8
        THEN CASE WHEN $8 = 'unknown' THEN NULL ELSE now() END
        ELSE sms_consent_updated_at
    END,
    sms_consent_source = CASE
        WHEN sms_consent_status IS DISTINCT FROM $8
        THEN $9
        ELSE sms_consent_source
    END,
    sms_consent_status = $8,
    updated_at = now()
WHERE id = $10
  AND team_id = $11
RETURNING id, team_id, email, first_name, last_name, unsubscribed, phone, normalized_phone, phone_country, sms_consent_status, sms_consent_updated_at, sms_consent_source, created_at, updated_at
`

type UpdateContactParams struct {
	Email            string    `db:"email" json:"email"`
	Phone            *string   `db:"phone" json:"phone"`
	NormalizedPhone  *string   `db:"normalized_phone" json:"normalized_phone"`
	PhoneCountry     *string   `db:"phone_country" json:"phone_country"`
	FirstName        *string   `db:"first_name" json:"first_name"`
	LastName         *string   `db:"last_name" json:"last_name"`
	Unsubscribed     bool      `db:"unsubscribed" json:"unsubscribed"`
	SmsConsentStatus string    `db:"sms_consent_status" json:"sms_consent_status"`
	SmsConsentSource *string   `db:"sms_consent_source" json:"sms_consent_source"`
	ID               uuid.UUID `db:"id" json:"id"`
	TeamID           uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Email,
		arg.Phone,
		arg.NormalizedPhone,
		arg.PhoneCountry,
		arg.FirstName,
		arg.LastName,
		arg.Unsubscribed,
		arg.SmsConsentStatus,
		arg.SmsConsentSource,
		arg.ID,
		arg.TeamID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Unsubscribed,
		&i.Phone,
		&i.NormalizedPhone,
		&i.PhoneCountry,
		&i.SmsConsentStatus,
		&i.SmsConsentUpdatedAt,
		&i.SmsConsentSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContactNumberPropertyValue = `-- name: UpsertContactNumberPropertyValue :exec
INSERT INTO contact_property_values (
    team_id,
    contact_id,
    contact_property_id,
    value_type,
    number_value
)
SELECT
    $1,
    $2,
    cp.id,
    cp.value_type,
    $3
FROM contact_properties AS cp
WHERE cp.team_id = $1
  AND cp.key = $4
  AND cp.value_type = 'number'
ON CONFLICT (contact_id, contact_property_id)
DO UPDATE SET
    value_type = EXCLUDED.value_type,
    string_value = NULL,
    number_value = EXCLUDED.number_value,
    updated_at = now()
`

type UpsertContactNumberPropertyValueParams struct {
	TeamID        uuid.UUID      `db:"team_id" json:"team_id"`
	ContactID     uuid.UUID      `db:"contact_id" json:"contact_id"`
	PropertyValue pgtype.Numeric `db:"property_value" json:"property_value"`
	PropertyKey   string         `db:"property_key" json:"property_key"`
}

func (q *Queries) UpsertContactNumberPropertyValue(ctx context.Context, arg UpsertContactNumberPropertyValueParams) error {
	_, err := q.db.Exec(ctx, upsertContactNumberPropertyValue,
		arg.TeamID,
		arg.ContactID,
		arg.PropertyValue,
		arg.PropertyKey,
	)
	return err
}

const upsertContactStringPropertyValue = `-- name: UpsertContactStringPropertyValue :exec
INSERT INTO contact_property_values (
    team_id,
    contact_id,
    contact_property_id,
    value_type,
    string_value
)
SELECT
    $1,
    $2,
    cp.id,
    cp.value_type,
    $3
FROM contact_properties AS cp
WHERE cp.team_id = $1
  AND cp.key = $4
  AND cp.value_type = 'string'
ON CONFLICT (contact_id, contact_property_id)
DO UPDATE SET
    value_type = EXCLUDED.value_type,
    string_value = EXCLUDED.string_value,
    number_value = NULL,
    updated_at = now()
`

type UpsertContactStringPropertyValueParams struct {
	TeamID        uuid.UUID `db:"team_id" json:"team_id"`
	ContactID     uuid.UUID `db:"contact_id" json:"contact_id"`
	PropertyValue *string   `db:"property_value" json:"property_value"`
	PropertyKey   string    `db:"property_key" json:"property_key"`
}

func (q *Queries) UpsertContactStringPropertyValue(ctx context.Context, arg UpsertContactStringPropertyValueParams) error {
	_, err := q.db.Exec(ctx, upsertContactStringPropertyValue,
		arg.TeamID,
		arg.ContactID,
		arg.PropertyValue,
		arg.PropertyKey,
	)
	return err
}

const upsertContactTopicSubscription = `-- name: UpsertContactTopicSubscription :one
INSERT INTO contact_topic_subscriptions (
    team_id,
    contact_id,
    topic_id,
    subscription
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (contact_id, topic_id)
DO UPDATE SET
    subscription = EXCLUDED.subscription,
    updated_at = now()
RETURNING topic_id
`

type UpsertContactTopicSubscriptionParams struct {
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	ContactID    uuid.UUID `db:"contact_id" json:"contact_id"`
	TopicID      uuid.UUID `db:"topic_id" json:"topic_id"`
	Subscription string    `db:"subscription" json:"subscription"`
}

func (q *Queries) UpsertContactTopicSubscription(ctx context.Context, arg UpsertContactTopicSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertContactTopicSubscription,
		arg.TeamID,
		arg.ContactID,
		arg.TopicID,
		arg.Subscription,
	)
	var topic_id uuid.UUID
	err := row.Scan(&topic_id)
	return topic_id, err
}
