// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_dns_records.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDomainDNSRecord = `-- name: CreateDomainDNSRecord :one
INSERT INTO domain_dns_records (
    domain_id,
    purpose,
    record,
    name,
    type,
    value,
    ttl,
    priority,
    status,
    is_current,
    verified_at
) VALUES (
    $1,
    lower(trim($2)),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    true,
    CASE WHEN $9 = 'verified' THEN now() ELSE NULL END
)
ON CONFLICT (domain_id, purpose, name, type, value)
DO UPDATE SET record = EXCLUDED.record,
              ttl = EXCLUDED.ttl,
              priority = EXCLUDED.priority,
              status = EXCLUDED.status,
              is_current = true,
              verified_at = CASE
                  WHEN EXCLUDED.status = 'verified'
                      THEN COALESCE(domain_dns_records.verified_at, now())
                  ELSE domain_dns_records.verified_at
              END,
              superseded_at = NULL,
              updated_at = now()
RETURNING id, domain_id, purpose, record, name, type, value, ttl, priority, status, is_current, verified_at, superseded_at, created_at, updated_at
`

type CreateDomainDNSRecordParams struct {
	DomainID uuid.UUID `db:"domain_id" json:"domain_id"`
	Purpose  string    `db:"purpose" json:"purpose"`
	Record   string    `db:"record" json:"record"`
	Name     string    `db:"name" json:"name"`
	Type     string    `db:"type" json:"type"`
	Value    string    `db:"value" json:"value"`
	Ttl      string    `db:"ttl" json:"ttl"`
	Priority *int32    `db:"priority" json:"priority"`
	Status   string    `db:"status" json:"status"`
}

func (q *Queries) CreateDomainDNSRecord(ctx context.Context, arg CreateDomainDNSRecordParams) (DomainDnsRecord, error) {
	row := q.db.QueryRow(ctx, createDomainDNSRecord,
		arg.DomainID,
		arg.Purpose,
		arg.Record,
		arg.Name,
		arg.Type,
		arg.Value,
		arg.Ttl,
		arg.Priority,
		arg.Status,
	)
	var i DomainDnsRecord
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Purpose,
		&i.Record,
		&i.Name,
		&i.Type,
		&i.Value,
		&i.Ttl,
		&i.Priority,
		&i.Status,
		&i.IsCurrent,
		&i.VerifiedAt,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCurrentDomainDNSRecords = `-- name: DeleteCurrentDomainDNSRecords :exec
DELETE FROM domain_dns_records
WHERE domain_id = $1
  AND is_current
  AND purpose <> 'tracking'
`

type DeleteCurrentDomainDNSRecordsParams struct {
	DomainID uuid.UUID `db:"domain_id" json:"domain_id"`
}

func (q *Queries) DeleteCurrentDomainDNSRecords(ctx context.Context, arg DeleteCurrentDomainDNSRecordsParams) error {
	_, err := q.db.Exec(ctx, deleteCurrentDomainDNSRecords, arg.DomainID)
	return err
}

const deleteDomainDNSRecords = `-- name: DeleteDomainDNSRecords :exec
DELETE FROM domain_dns_records
WHERE domain_id = $1
`

type DeleteDomainDNSRecordsParams struct {
	DomainID uuid.UUID `db:"domain_id" json:"domain_id"`
}

func (q *Queries) DeleteDomainDNSRecords(ctx context.Context, arg DeleteDomainDNSRecordsParams) error {
	_, err := q.db.Exec(ctx, deleteDomainDNSRecords, arg.DomainID)
	return err
}

const listAllDomainDNSRecords = `-- name: ListAllDomainDNSRecords :many
SELECT dns_record.id, dns_record.domain_id, dns_record.purpose, dns_record.record, dns_record.name, dns_record.type, dns_record.value, dns_record.ttl, dns_record.priority, dns_record.status, dns_record.is_current, dns_record.verified_at, dns_record.superseded_at, dns_record.created_at, dns_record.updated_at
FROM domain_dns_records AS dns_record
WHERE dns_record.domain_id = $1
ORDER BY dns_record.created_at, dns_record.id
`

type ListAllDomainDNSRecordsParams struct {
	DomainID uuid.UUID `db:"domain_id" json:"domain_id"`
}

func (q *Queries) ListAllDomainDNSRecords(ctx context.Context, arg ListAllDomainDNSRecordsParams) ([]DomainDnsRecord, error) {
	rows, err := q.db.Query(ctx, listAllDomainDNSRecords, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainDnsRecord{}
	for rows.Next() {
		var i DomainDnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Purpose,
			&i.Record,
			&i.Name,
			&i.Type,
			&i.Value,
			&i.Ttl,
			&i.Priority,
			&i.Status,
			&i.IsCurrent,
			&i.VerifiedAt,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainDNSRecords = `-- name: ListDomainDNSRecords :many
SELECT dns_record.id, dns_record.domain_id, dns_record.purpose, dns_record.record, dns_record.name, dns_record.type, dns_record.value, dns_record.ttl, dns_record.priority, dns_record.status, dns_record.is_current, dns_record.verified_at, dns_record.superseded_at, dns_record.created_at, dns_record.updated_at
FROM domain_dns_records AS dns_record
WHERE dns_record.domain_id = $1
  AND dns_record.is_current
ORDER BY dns_record.created_at, dns_record.id
`

type ListDomainDNSRecordsParams struct {
	DomainID uuid.UUID `db:"domain_id" json:"domain_id"`
}

func (q *Queries) ListDomainDNSRecords(ctx context.Context, arg ListDomainDNSRecordsParams) ([]DomainDnsRecord, error) {
	rows, err := q.db.Query(ctx, listDomainDNSRecords, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainDnsRecord{}
	for rows.Next() {
		var i DomainDnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Purpose,
			&i.Record,
			&i.Name,
			&i.Type,
			&i.Value,
			&i.Ttl,
			&i.Priority,
			&i.Status,
			&i.IsCurrent,
			&i.VerifiedAt,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeDomainTrackingRecords = `-- name: SupersedeDomainTrackingRecords :exec
UPDATE domain_dns_records
SET is_current = false,
    superseded_at = now(),
    updated_at = now()
WHERE domain_id = $1
  AND purpose = 'tracking'
  AND is_current
`

type SupersedeDomainTrackingRecordsParams struct {
	DomainID uuid.UUID `db:"domain_id" json:"domain_id"`
}

func (q *Queries) SupersedeDomainTrackingRecords(ctx context.Context, arg SupersedeDomainTrackingRecordsParams) error {
	_, err := q.db.Exec(ctx, supersedeDomainTrackingRecords, arg.DomainID)
	return err
}
