// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingDomainReconciliations = `-- name: ClaimPendingDomainReconciliations :many
WITH candidates AS (
    SELECT domain_record.id
    FROM domains AS domain_record
    WHERE domain_record.status IN ('pending', 'verified', 'temporary_failure')
      AND domain_record.disabled_at IS NULL
      AND domain_record.next_check_at <= now()
      AND (
          domain_record.reconcile_locked_at IS NULL
          OR domain_record.reconcile_locked_at < $1
      )
    ORDER BY domain_record.next_check_at, domain_record.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $2
), updated AS (
    UPDATE domains AS domain_record
    SET reconcile_locked_at = now(),
        reconcile_locked_by = trim($3),
        reconciliation_attempts = domain_record.reconciliation_attempts + 1,
        updated_at = now()
    FROM candidates
    WHERE domain_record.id = candidates.id
    RETURNING domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
)
SELECT updated.id, updated.team_id, updated.name, updated.normalized_name, updated.provider, updated.provider_account, updated.provider_region, updated.provider_external_id, updated.status, updated.provider_status, updated.open_tracking, updated.click_tracking, updated.tracking_subdomain, updated.active_tracking_subdomain, updated.tls_mode, updated.sending_enabled, updated.receiving_enabled, updated.custom_return_path, updated.health_status, updated.consecutive_health_failures, updated.failure_reason, updated.last_error, updated.submitted_at, updated.verified_at, updated.disabled_at, updated.last_checked_at, updated.next_check_at, updated.last_health_checked_at, updated.last_health_failure_at, updated.reconciliation_attempts, updated.reconcile_locked_at, updated.reconcile_locked_by, updated.created_by, updated.created_at, updated.updated_at
FROM updated
ORDER BY updated.next_check_at, updated.created_at
`

type ClaimPendingDomainReconciliationsParams struct {
	StaleBefore pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
	ClaimLimit  int32              `db:"claim_limit" json:"claim_limit"`
	WorkerID    string             `db:"worker_id" json:"worker_id"`
}

type ClaimPendingDomainReconciliationsRow struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	TeamID                    uuid.UUID          `db:"team_id" json:"team_id"`
	Name                      string             `db:"name" json:"name"`
	NormalizedName            string             `db:"normalized_name" json:"normalized_name"`
	Provider                  string             `db:"provider" json:"provider"`
	ProviderAccount           string             `db:"provider_account" json:"provider_account"`
	ProviderRegion            string             `db:"provider_region" json:"provider_region"`
	ProviderExternalID        *string            `db:"provider_external_id" json:"provider_external_id"`
	Status                    string             `db:"status" json:"status"`
	ProviderStatus            *string            `db:"provider_status" json:"provider_status"`
	OpenTracking              bool               `db:"open_tracking" json:"open_tracking"`
	ClickTracking             bool               `db:"click_tracking" json:"click_tracking"`
	TrackingSubdomain         *string            `db:"tracking_subdomain" json:"tracking_subdomain"`
	ActiveTrackingSubdomain   *string            `db:"active_tracking_subdomain" json:"active_tracking_subdomain"`
	TlsMode                   string             `db:"tls_mode" json:"tls_mode"`
	SendingEnabled            bool               `db:"sending_enabled" json:"sending_enabled"`
	ReceivingEnabled          bool               `db:"receiving_enabled" json:"receiving_enabled"`
	CustomReturnPath          string             `db:"custom_return_path" json:"custom_return_path"`
	HealthStatus              string             `db:"health_status" json:"health_status"`
	ConsecutiveHealthFailures int32              `db:"consecutive_health_failures" json:"consecutive_health_failures"`
	FailureReason             *string            `db:"failure_reason" json:"failure_reason"`
	LastError                 *string            `db:"last_error" json:"last_error"`
	SubmittedAt               pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	VerifiedAt                pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	DisabledAt                pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastCheckedAt             pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	NextCheckAt               pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	LastHealthCheckedAt       pgtype.Timestamptz `db:"last_health_checked_at" json:"last_health_checked_at"`
	LastHealthFailureAt       pgtype.Timestamptz `db:"last_health_failure_at" json:"last_health_failure_at"`
	ReconciliationAttempts    int32              `db:"reconciliation_attempts" json:"reconciliation_attempts"`
	ReconcileLockedAt         pgtype.Timestamptz `db:"reconcile_locked_at" json:"reconcile_locked_at"`
	ReconcileLockedBy         *string            `db:"reconcile_locked_by" json:"reconcile_locked_by"`
	CreatedBy                 *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ClaimPendingDomainReconciliations(ctx context.Context, arg ClaimPendingDomainReconciliationsParams) ([]ClaimPendingDomainReconciliationsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingDomainReconciliations, arg.StaleBefore, arg.ClaimLimit, arg.WorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingDomainReconciliationsRow{}
	for rows.Next() {
		var i ClaimPendingDomainReconciliationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.NormalizedName,
			&i.Provider,
			&i.ProviderAccount,
			&i.ProviderRegion,
			&i.ProviderExternalID,
			&i.Status,
			&i.ProviderStatus,
			&i.OpenTracking,
			&i.ClickTracking,
			&i.TrackingSubdomain,
			&i.ActiveTrackingSubdomain,
			&i.TlsMode,
			&i.SendingEnabled,
			&i.ReceivingEnabled,
			&i.CustomReturnPath,
			&i.HealthStatus,
			&i.ConsecutiveHealthFailures,
			&i.FailureReason,
			&i.LastError,
			&i.SubmittedAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.LastHealthCheckedAt,
			&i.LastHealthFailureAt,
			&i.ReconciliationAttempts,
			&i.ReconcileLockedAt,
			&i.ReconcileLockedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDomainHealthCheck = `-- name: CompleteDomainHealthCheck :one
UPDATE domains
SET health_status = 'healthy',
    consecutive_health_failures = 0,
    last_error = NULL,
    last_checked_at = now(),
    last_health_checked_at = now(),
    next_check_at = $1,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $2
  AND status = 'verified'
  AND reconcile_locked_by = trim($3)
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type CompleteDomainHealthCheckParams struct {
	NextCheckAt pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	WorkerID    string             `db:"worker_id" json:"worker_id"`
}

func (q *Queries) CompleteDomainHealthCheck(ctx context.Context, arg CompleteDomainHealthCheckParams) (Domain, error) {
	row := q.db.QueryRow(ctx, completeDomainHealthCheck, arg.NextCheckAt, arg.ID, arg.WorkerID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeDomainReconciliation = `-- name: CompleteDomainReconciliation :one
UPDATE domains
SET status = $1,
    provider_status = $1,
    failure_reason = CASE
        WHEN $1 IN ('failed', 'partially_failed', 'temporary_failure')
            THEN $2
        ELSE NULL
    END,
    last_error = $2,
    last_checked_at = now(),
    health_status = CASE
        WHEN $1 = 'verified' THEN 'healthy'
        ELSE health_status
    END,
    consecutive_health_failures = CASE
        WHEN $1 = 'verified' THEN 0
        ELSE consecutive_health_failures
    END,
    last_health_checked_at = CASE
        WHEN $1 = 'verified' THEN now()
        ELSE last_health_checked_at
    END,
    verified_at = CASE
        WHEN $1 = 'verified' THEN COALESCE(verified_at, now())
        ELSE verified_at
    END,
    next_check_at = $3,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $4
  AND reconcile_locked_by = trim($5)
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type CompleteDomainReconciliationParams struct {
	Status        string             `db:"status" json:"status"`
	FailureReason *string            `db:"failure_reason" json:"failure_reason"`
	NextCheckAt   pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID            uuid.UUID          `db:"id" json:"id"`
	WorkerID      string             `db:"worker_id" json:"worker_id"`
}

func (q *Queries) CompleteDomainReconciliation(ctx context.Context, arg CompleteDomainReconciliationParams) (Domain, error) {
	row := q.db.QueryRow(ctx, completeDomainReconciliation,
		arg.Status,
		arg.FailureReason,
		arg.NextCheckAt,
		arg.ID,
		arg.WorkerID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClaimedDomain = `-- name: CreateClaimedDomain :one
INSERT INTO domains (
    id,
    team_id,
    name,
    normalized_name,
    provider,
    provider_account,
    provider_region,
    status,
    provider_status,
    open_tracking,
    click_tracking,
    tracking_subdomain,
    tls_mode,
    sending_enabled,
    receiving_enabled,
    custom_return_path,
    health_status,
    submitted_at,
    next_check_at,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    lower(trim($3)),
    lower(trim($4)),
    lower(trim($5)),
    lower(trim($6)),
    'pending',
    'pending',
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    lower(trim($13)),
    'unknown',
    now(),
    now() + interval '1 minute',
    $14
)
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type CreateClaimedDomainParams struct {
	ID                uuid.UUID  `db:"id" json:"id"`
	TeamID            uuid.UUID  `db:"team_id" json:"team_id"`
	Name              string     `db:"name" json:"name"`
	Provider          string     `db:"provider" json:"provider"`
	ProviderAccount   string     `db:"provider_account" json:"provider_account"`
	ProviderRegion    string     `db:"provider_region" json:"provider_region"`
	OpenTracking      bool       `db:"open_tracking" json:"open_tracking"`
	ClickTracking     bool       `db:"click_tracking" json:"click_tracking"`
	TrackingSubdomain *string    `db:"tracking_subdomain" json:"tracking_subdomain"`
	TlsMode           string     `db:"tls_mode" json:"tls_mode"`
	SendingEnabled    bool       `db:"sending_enabled" json:"sending_enabled"`
	ReceivingEnabled  bool       `db:"receiving_enabled" json:"receiving_enabled"`
	CustomReturnPath  string     `db:"custom_return_path" json:"custom_return_path"`
	CreatedBy         *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateClaimedDomain(ctx context.Context, arg CreateClaimedDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createClaimedDomain,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Provider,
		arg.ProviderAccount,
		arg.ProviderRegion,
		arg.OpenTracking,
		arg.ClickTracking,
		arg.TrackingSubdomain,
		arg.TlsMode,
		arg.SendingEnabled,
		arg.ReceivingEnabled,
		arg.CustomReturnPath,
		arg.CreatedBy,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (
    team_id,
    name,
    normalized_name,
    provider,
    provider_account,
    provider_region,
    custom_return_path,
    open_tracking,
    click_tracking,
    tracking_subdomain,
    tls_mode,
    sending_enabled,
    receiving_enabled,
    created_by,
    submitted_at,
    next_check_at
)
SELECT team.id,
       $1,
       lower(trim($1)),
       lower(trim($2)),
       lower(trim($3)),
       lower(trim($4)),
       lower(trim($5)),
       $6,
       $7,
       $8,
       $9,
       $10,
       $11,
       $12,
       now(),
       now() + interval '1 minute'
FROM teams AS team
WHERE team.id = $13
  AND team.status = 'active'
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type CreateDomainParams struct {
	Name              string     `db:"name" json:"name"`
	Provider          string     `db:"provider" json:"provider"`
	ProviderAccount   string     `db:"provider_account" json:"provider_account"`
	ProviderRegion    string     `db:"provider_region" json:"provider_region"`
	CustomReturnPath  string     `db:"custom_return_path" json:"custom_return_path"`
	OpenTracking      bool       `db:"open_tracking" json:"open_tracking"`
	ClickTracking     bool       `db:"click_tracking" json:"click_tracking"`
	TrackingSubdomain *string    `db:"tracking_subdomain" json:"tracking_subdomain"`
	TlsMode           string     `db:"tls_mode" json:"tls_mode"`
	SendingEnabled    bool       `db:"sending_enabled" json:"sending_enabled"`
	ReceivingEnabled  bool       `db:"receiving_enabled" json:"receiving_enabled"`
	CreatedBy         *uuid.UUID `db:"created_by" json:"created_by"`
	TeamID            uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.Name,
		arg.Provider,
		arg.ProviderAccount,
		arg.ProviderRegion,
		arg.CustomReturnPath,
		arg.OpenTracking,
		arg.ClickTracking,
		arg.TrackingSubdomain,
		arg.TlsMode,
		arg.SendingEnabled,
		arg.ReceivingEnabled,
		arg.CreatedBy,
		arg.TeamID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDisabledDomainIfUnreferenced = `-- name: DeleteDisabledDomainIfUnreferenced :one
DELETE FROM domains AS domain_record
WHERE domain_record.id = $1
  AND domain_record.team_id = $2
  AND domain_record.status = 'disabled'
  AND NOT EXISTS (
      SELECT 1
      FROM email_messages AS message
      WHERE message.sender_domain_id = domain_record.id
  )
RETURNING domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
`

type DeleteDisabledDomainIfUnreferencedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteDisabledDomainIfUnreferenced(ctx context.Context, arg DeleteDisabledDomainIfUnreferencedParams) (Domain, error) {
	row := q.db.QueryRow(ctx, deleteDisabledDomainIfUnreferenced, arg.ID, arg.TeamID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :one
DELETE FROM domains
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type DeleteDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, deleteDomain, arg.ID, arg.TeamID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomainForClaim = `-- name: DeleteDomainForClaim :one
DELETE FROM domains
WHERE id = $1
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type DeleteDomainForClaimParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteDomainForClaim(ctx context.Context, arg DeleteDomainForClaimParams) (Domain, error) {
	row := q.db.QueryRow(ctx, deleteDomainForClaim, arg.ID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableDomain = `-- name: DisableDomain :one
UPDATE domains
SET status = 'disabled',
    disabled_at = COALESCE(disabled_at, now()),
    next_check_at = now(),
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type DisableDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DisableDomain(ctx context.Context, arg DisableDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, disableDomain, arg.ID, arg.TeamID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
FROM domains AS domain_record
WHERE domain_record.id = $1
  AND domain_record.team_id = $2
`

type GetDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetDomain(ctx context.Context, arg GetDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, arg.ID, arg.TeamID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
FROM domains AS domain_record
WHERE domain_record.id = $1
`

type GetDomainByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetDomainByID(ctx context.Context, arg GetDomainByIDParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByID, arg.ID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
FROM domains AS domain_record
WHERE domain_record.normalized_name = lower(trim($1))
  AND domain_record.team_id = $2
`

type GetDomainByNameParams struct {
	Name   string    `db:"name" json:"name"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetDomainByName(ctx context.Context, arg GetDomainByNameParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, arg.Name, arg.TeamID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByNameForClaim = `-- name: GetDomainByNameForClaim :one
SELECT domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
FROM domains AS domain_record
WHERE domain_record.normalized_name = lower(trim($1))
FOR SHARE
`

type GetDomainByNameForClaimParams struct {
	Name string `db:"name" json:"name"`
}

func (q *Queries) GetDomainByNameForClaim(ctx context.Context, arg GetDomainByNameForClaimParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByNameForClaim, arg.Name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT domain_record.id, domain_record.team_id, domain_record.name, domain_record.normalized_name, domain_record.provider, domain_record.provider_account, domain_record.provider_region, domain_record.provider_external_id, domain_record.status, domain_record.provider_status, domain_record.open_tracking, domain_record.click_tracking, domain_record.tracking_subdomain, domain_record.active_tracking_subdomain, domain_record.tls_mode, domain_record.sending_enabled, domain_record.receiving_enabled, domain_record.custom_return_path, domain_record.health_status, domain_record.consecutive_health_failures, domain_record.failure_reason, domain_record.last_error, domain_record.submitted_at, domain_record.verified_at, domain_record.disabled_at, domain_record.last_checked_at, domain_record.next_check_at, domain_record.last_health_checked_at, domain_record.last_health_failure_at, domain_record.reconciliation_attempts, domain_record.reconcile_locked_at, domain_record.reconcile_locked_by, domain_record.created_by, domain_record.created_at, domain_record.updated_at
FROM domains AS domain_record
WHERE domain_record.team_id = $1
ORDER BY domain_record.created_at DESC, domain_record.id DESC
`

type ListDomainsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.NormalizedName,
			&i.Provider,
			&i.ProviderAccount,
			&i.ProviderRegion,
			&i.ProviderExternalID,
			&i.Status,
			&i.ProviderStatus,
			&i.OpenTracking,
			&i.ClickTracking,
			&i.TrackingSubdomain,
			&i.ActiveTrackingSubdomain,
			&i.TlsMode,
			&i.SendingEnabled,
			&i.ReceivingEnabled,
			&i.CustomReturnPath,
			&i.HealthStatus,
			&i.ConsecutiveHealthFailures,
			&i.FailureReason,
			&i.LastError,
			&i.SubmittedAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.LastHealthCheckedAt,
			&i.LastHealthFailureAt,
			&i.ReconciliationAttempts,
			&i.ReconcileLockedAt,
			&i.ReconcileLockedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDomainHealthFailure = `-- name: RecordDomainHealthFailure :one
UPDATE domains
SET health_status = CASE
        WHEN consecutive_health_failures + 1 >= $1
            THEN 'degraded'
        ELSE health_status
    END,
    consecutive_health_failures = consecutive_health_failures + 1,
    last_error = $2,
    last_checked_at = now(),
    last_health_checked_at = now(),
    last_health_failure_at = now(),
    next_check_at = $3,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $4
  AND status = 'verified'
  AND reconcile_locked_by = trim($5)
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type RecordDomainHealthFailureParams struct {
	FailureThreshold int32              `db:"failure_threshold" json:"failure_threshold"`
	LastError        *string            `db:"last_error" json:"last_error"`
	NextCheckAt      pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID               uuid.UUID          `db:"id" json:"id"`
	WorkerID         string             `db:"worker_id" json:"worker_id"`
}

func (q *Queries) RecordDomainHealthFailure(ctx context.Context, arg RecordDomainHealthFailureParams) (Domain, error) {
	row := q.db.QueryRow(ctx, recordDomainHealthFailure,
		arg.FailureThreshold,
		arg.LastError,
		arg.NextCheckAt,
		arg.ID,
		arg.WorkerID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordDomainReconciliationFailure = `-- name: RecordDomainReconciliationFailure :one
UPDATE domains
SET last_error = $1,
    last_checked_at = now(),
    next_check_at = $2,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $3
  AND reconcile_locked_by = trim($4)
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type RecordDomainReconciliationFailureParams struct {
	LastError   *string            `db:"last_error" json:"last_error"`
	NextCheckAt pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	WorkerID    string             `db:"worker_id" json:"worker_id"`
}

func (q *Queries) RecordDomainReconciliationFailure(ctx context.Context, arg RecordDomainReconciliationFailureParams) (Domain, error) {
	row := q.db.QueryRow(ctx, recordDomainReconciliationFailure,
		arg.LastError,
		arg.NextCheckAt,
		arg.ID,
		arg.WorkerID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveEmailSenderDomain = `-- name: ResolveEmailSenderDomain :one
SELECT id, provider, provider_region, status, health_status, disabled_at
FROM domains
WHERE team_id = $1
  AND normalized_name = lower(trim($2))
LIMIT 1
`

type ResolveEmailSenderDomainParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	DomainName string    `db:"domain_name" json:"domain_name"`
}

type ResolveEmailSenderDomainRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderRegion string             `db:"provider_region" json:"provider_region"`
	Status         string             `db:"status" json:"status"`
	HealthStatus   string             `db:"health_status" json:"health_status"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

func (q *Queries) ResolveEmailSenderDomain(ctx context.Context, arg ResolveEmailSenderDomainParams) (ResolveEmailSenderDomainRow, error) {
	row := q.db.QueryRow(ctx, resolveEmailSenderDomain, arg.TeamID, arg.DomainName)
	var i ResolveEmailSenderDomainRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.HealthStatus,
		&i.DisabledAt,
	)
	return i, err
}

const updateDomainConfiguration = `-- name: UpdateDomainConfiguration :one
UPDATE domains
SET open_tracking = $1,
    click_tracking = $2,
    tracking_subdomain = $3,
    tls_mode = $4,
    sending_enabled = $5,
    receiving_enabled = $6,
    updated_at = now()
WHERE id = $7
  AND team_id = $8
  AND disabled_at IS NULL
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type UpdateDomainConfigurationParams struct {
	OpenTracking      bool      `db:"open_tracking" json:"open_tracking"`
	ClickTracking     bool      `db:"click_tracking" json:"click_tracking"`
	TrackingSubdomain *string   `db:"tracking_subdomain" json:"tracking_subdomain"`
	TlsMode           string    `db:"tls_mode" json:"tls_mode"`
	SendingEnabled    bool      `db:"sending_enabled" json:"sending_enabled"`
	ReceivingEnabled  bool      `db:"receiving_enabled" json:"receiving_enabled"`
	ID                uuid.UUID `db:"id" json:"id"`
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateDomainConfiguration(ctx context.Context, arg UpdateDomainConfigurationParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainConfiguration,
		arg.OpenTracking,
		arg.ClickTracking,
		arg.TrackingSubdomain,
		arg.TlsMode,
		arg.SendingEnabled,
		arg.ReceivingEnabled,
		arg.ID,
		arg.TeamID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainManualHealthCheck = `-- name: UpdateDomainManualHealthCheck :one
UPDATE domains
SET health_status = CASE
        WHEN $1::text IS NULL THEN 'healthy'
        WHEN consecutive_health_failures + 1 >= $2
            THEN 'degraded'
        ELSE health_status
    END,
    consecutive_health_failures = CASE
        WHEN $1::text IS NULL THEN 0
        ELSE consecutive_health_failures + 1
    END,
    last_error = $1,
    last_checked_at = now(),
    last_health_checked_at = now(),
    last_health_failure_at = CASE
        WHEN $1::text IS NULL THEN last_health_failure_at
        ELSE now()
    END,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND status = 'verified'
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type UpdateDomainManualHealthCheckParams struct {
	FailureReason    *string   `db:"failure_reason" json:"failure_reason"`
	FailureThreshold int32     `db:"failure_threshold" json:"failure_threshold"`
	ID               uuid.UUID `db:"id" json:"id"`
	TeamID           uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateDomainManualHealthCheck(ctx context.Context, arg UpdateDomainManualHealthCheckParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainManualHealthCheck,
		arg.FailureReason,
		arg.FailureThreshold,
		arg.ID,
		arg.TeamID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainVerification = `-- name: UpdateDomainVerification :one
UPDATE domains
SET status = $1,
    provider_status = $1,
    failure_reason = CASE
        WHEN $1 IN ('failed', 'partially_failed', 'temporary_failure')
            THEN $2
        ELSE NULL
    END,
    last_error = $2,
    last_checked_at = now(),
    health_status = CASE
        WHEN $1 = 'verified' THEN 'healthy'
        ELSE health_status
    END,
    consecutive_health_failures = CASE
        WHEN $1 = 'verified' THEN 0
        ELSE consecutive_health_failures
    END,
    last_health_checked_at = CASE
        WHEN $1 = 'verified' THEN now()
        ELSE last_health_checked_at
    END,
    verified_at = CASE
        WHEN $1 = 'verified' THEN COALESCE(verified_at, now())
        ELSE verified_at
    END,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
RETURNING id, team_id, name, normalized_name, provider, provider_account, provider_region, provider_external_id, status, provider_status, open_tracking, click_tracking, tracking_subdomain, active_tracking_subdomain, tls_mode, sending_enabled, receiving_enabled, custom_return_path, health_status, consecutive_health_failures, failure_reason, last_error, submitted_at, verified_at, disabled_at, last_checked_at, next_check_at, last_health_checked_at, last_health_failure_at, reconciliation_attempts, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type UpdateDomainVerificationParams struct {
	Status        string    `db:"status" json:"status"`
	FailureReason *string   `db:"failure_reason" json:"failure_reason"`
	ID            uuid.UUID `db:"id" json:"id"`
	TeamID        uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateDomainVerification(ctx context.Context, arg UpdateDomainVerificationParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainVerification,
		arg.Status,
		arg.FailureReason,
		arg.ID,
		arg.TeamID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.NormalizedName,
		&i.Provider,
		&i.ProviderAccount,
		&i.ProviderRegion,
		&i.ProviderExternalID,
		&i.Status,
		&i.ProviderStatus,
		&i.OpenTracking,
		&i.ClickTracking,
		&i.TrackingSubdomain,
		&i.ActiveTrackingSubdomain,
		&i.TlsMode,
		&i.SendingEnabled,
		&i.ReceivingEnabled,
		&i.CustomReturnPath,
		&i.HealthStatus,
		&i.ConsecutiveHealthFailures,
		&i.FailureReason,
		&i.LastError,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.LastHealthCheckedAt,
		&i.LastHealthFailureAt,
		&i.ReconciliationAttempts,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
