// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_claims.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDomainClaim = `-- name: CancelDomainClaim :one
UPDATE domain_claims
SET status = 'canceled',
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE target_domain_id = $1
  AND target_team_id = $2
  AND status IN ('pending', 'verified', 'blocked')
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type CancelDomainClaimParams struct {
	TargetDomainID uuid.UUID `db:"target_domain_id" json:"target_domain_id"`
	TargetTeamID   uuid.UUID `db:"target_team_id" json:"target_team_id"`
}

func (q *Queries) CancelDomainClaim(ctx context.Context, arg CancelDomainClaimParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, cancelDomainClaim, arg.TargetDomainID, arg.TargetTeamID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPendingDomainClaims = `-- name: ClaimPendingDomainClaims :many
WITH candidates AS (
    SELECT claim.id
    FROM domain_claims AS claim
    WHERE claim.status IN ('pending', 'verified', 'blocked')
      AND claim.verification_requested_at IS NOT NULL
      AND claim.expires_at > now()
      AND (
          claim.reconcile_locked_at IS NULL
          OR claim.reconcile_locked_at < $1
      )
    ORDER BY claim.verification_requested_at, claim.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $2
), updated AS (
    UPDATE domain_claims AS claim
    SET reconcile_locked_at = now(),
        reconcile_locked_by = trim($3),
        updated_at = now()
    FROM candidates
    WHERE claim.id = candidates.id
    RETURNING claim.id, claim.target_domain_id, claim.source_domain_id, claim.normalized_name, claim.source_team_id, claim.target_team_id, claim.provider_region, claim.custom_return_path, claim.tls_mode, claim.status, claim.blocked_reason, claim.failure_reason, claim.record_name, claim.record_value, claim.record_ttl, claim.verification_requested_at, claim.verified_at, claim.completed_at, claim.expires_at, claim.reconcile_locked_at, claim.reconcile_locked_by, claim.created_by, claim.created_at, claim.updated_at
)
SELECT updated.id, updated.target_domain_id, updated.source_domain_id, updated.normalized_name, updated.source_team_id, updated.target_team_id, updated.provider_region, updated.custom_return_path, updated.tls_mode, updated.status, updated.blocked_reason, updated.failure_reason, updated.record_name, updated.record_value, updated.record_ttl, updated.verification_requested_at, updated.verified_at, updated.completed_at, updated.expires_at, updated.reconcile_locked_at, updated.reconcile_locked_by, updated.created_by, updated.created_at, updated.updated_at
FROM updated
ORDER BY updated.verification_requested_at, updated.created_at
`

type ClaimPendingDomainClaimsParams struct {
	StaleBefore pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
	ClaimLimit  int32              `db:"claim_limit" json:"claim_limit"`
	WorkerID    string             `db:"worker_id" json:"worker_id"`
}

type ClaimPendingDomainClaimsRow struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	TargetDomainID          uuid.UUID          `db:"target_domain_id" json:"target_domain_id"`
	SourceDomainID          *uuid.UUID         `db:"source_domain_id" json:"source_domain_id"`
	NormalizedName          string             `db:"normalized_name" json:"normalized_name"`
	SourceTeamID            uuid.UUID          `db:"source_team_id" json:"source_team_id"`
	TargetTeamID            uuid.UUID          `db:"target_team_id" json:"target_team_id"`
	ProviderRegion          string             `db:"provider_region" json:"provider_region"`
	CustomReturnPath        string             `db:"custom_return_path" json:"custom_return_path"`
	TlsMode                 string             `db:"tls_mode" json:"tls_mode"`
	Status                  string             `db:"status" json:"status"`
	BlockedReason           *string            `db:"blocked_reason" json:"blocked_reason"`
	FailureReason           *string            `db:"failure_reason" json:"failure_reason"`
	RecordName              string             `db:"record_name" json:"record_name"`
	RecordValue             string             `db:"record_value" json:"record_value"`
	RecordTtl               string             `db:"record_ttl" json:"record_ttl"`
	VerificationRequestedAt pgtype.Timestamptz `db:"verification_requested_at" json:"verification_requested_at"`
	VerifiedAt              pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CompletedAt             pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ReconcileLockedAt       pgtype.Timestamptz `db:"reconcile_locked_at" json:"reconcile_locked_at"`
	ReconcileLockedBy       *string            `db:"reconcile_locked_by" json:"reconcile_locked_by"`
	CreatedBy               *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ClaimPendingDomainClaims(ctx context.Context, arg ClaimPendingDomainClaimsParams) ([]ClaimPendingDomainClaimsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingDomainClaims, arg.StaleBefore, arg.ClaimLimit, arg.WorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingDomainClaimsRow{}
	for rows.Next() {
		var i ClaimPendingDomainClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetDomainID,
			&i.SourceDomainID,
			&i.NormalizedName,
			&i.SourceTeamID,
			&i.TargetTeamID,
			&i.ProviderRegion,
			&i.CustomReturnPath,
			&i.TlsMode,
			&i.Status,
			&i.BlockedReason,
			&i.FailureReason,
			&i.RecordName,
			&i.RecordValue,
			&i.RecordTtl,
			&i.VerificationRequestedAt,
			&i.VerifiedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.ReconcileLockedAt,
			&i.ReconcileLockedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDomainClaim = `-- name: CreateDomainClaim :one
INSERT INTO domain_claims (
    target_domain_id,
    source_domain_id,
    normalized_name,
    source_team_id,
    target_team_id,
    provider_region,
    custom_return_path,
    tls_mode,
    record_name,
    record_value,
    record_ttl,
    expires_at,
    created_by
) VALUES (
    $1,
    $2,
    lower(trim($3)),
    $4,
    $5,
    lower(trim($6)),
    lower(trim($7)),
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type CreateDomainClaimParams struct {
	TargetDomainID   uuid.UUID          `db:"target_domain_id" json:"target_domain_id"`
	SourceDomainID   *uuid.UUID         `db:"source_domain_id" json:"source_domain_id"`
	NormalizedName   string             `db:"normalized_name" json:"normalized_name"`
	SourceTeamID     uuid.UUID          `db:"source_team_id" json:"source_team_id"`
	TargetTeamID     uuid.UUID          `db:"target_team_id" json:"target_team_id"`
	ProviderRegion   string             `db:"provider_region" json:"provider_region"`
	CustomReturnPath string             `db:"custom_return_path" json:"custom_return_path"`
	TlsMode          string             `db:"tls_mode" json:"tls_mode"`
	RecordName       string             `db:"record_name" json:"record_name"`
	RecordValue      string             `db:"record_value" json:"record_value"`
	RecordTtl        string             `db:"record_ttl" json:"record_ttl"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy        *uuid.UUID         `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateDomainClaim(ctx context.Context, arg CreateDomainClaimParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, createDomainClaim,
		arg.TargetDomainID,
		arg.SourceDomainID,
		arg.NormalizedName,
		arg.SourceTeamID,
		arg.TargetTeamID,
		arg.ProviderRegion,
		arg.CustomReturnPath,
		arg.TlsMode,
		arg.RecordName,
		arg.RecordValue,
		arg.RecordTtl,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainHasPendingScheduledEmails = `-- name: DomainHasPendingScheduledEmails :one
SELECT EXISTS (
    SELECT 1
    FROM email_messages AS message
    WHERE message.sender_domain_id = $1
      AND message.status = 'queued'
      AND message.scheduled_at IS NOT NULL
      AND message.scheduled_at > now()
)
`

type DomainHasPendingScheduledEmailsParams struct {
	DomainID *uuid.UUID `db:"domain_id" json:"domain_id"`
}

func (q *Queries) DomainHasPendingScheduledEmails(ctx context.Context, arg DomainHasPendingScheduledEmailsParams) (bool, error) {
	row := q.db.QueryRow(ctx, domainHasPendingScheduledEmails, arg.DomainID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const expireDomainClaims = `-- name: ExpireDomainClaims :many
UPDATE domain_claims
SET status = 'expired',
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE status IN ('pending', 'verified', 'blocked')
  AND expires_at <= now()
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

func (q *Queries) ExpireDomainClaims(ctx context.Context) ([]DomainClaim, error) {
	rows, err := q.db.Query(ctx, expireDomainClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainClaim{}
	for rows.Next() {
		var i DomainClaim
		if err := rows.Scan(
			&i.ID,
			&i.TargetDomainID,
			&i.SourceDomainID,
			&i.NormalizedName,
			&i.SourceTeamID,
			&i.TargetTeamID,
			&i.ProviderRegion,
			&i.CustomReturnPath,
			&i.TlsMode,
			&i.Status,
			&i.BlockedReason,
			&i.FailureReason,
			&i.RecordName,
			&i.RecordValue,
			&i.RecordTtl,
			&i.VerificationRequestedAt,
			&i.VerifiedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.ReconcileLockedAt,
			&i.ReconcileLockedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainClaim = `-- name: GetDomainClaim :one
SELECT claim.id, claim.target_domain_id, claim.source_domain_id, claim.normalized_name, claim.source_team_id, claim.target_team_id, claim.provider_region, claim.custom_return_path, claim.tls_mode, claim.status, claim.blocked_reason, claim.failure_reason, claim.record_name, claim.record_value, claim.record_ttl, claim.verification_requested_at, claim.verified_at, claim.completed_at, claim.expires_at, claim.reconcile_locked_at, claim.reconcile_locked_by, claim.created_by, claim.created_at, claim.updated_at
FROM domain_claims AS claim
WHERE claim.target_domain_id = $1
  AND claim.target_team_id = $2
`

type GetDomainClaimParams struct {
	TargetDomainID uuid.UUID `db:"target_domain_id" json:"target_domain_id"`
	TargetTeamID   uuid.UUID `db:"target_team_id" json:"target_team_id"`
}

func (q *Queries) GetDomainClaim(ctx context.Context, arg GetDomainClaimParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, getDomainClaim, arg.TargetDomainID, arg.TargetTeamID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainClaimByID = `-- name: GetDomainClaimByID :one
SELECT claim.id, claim.target_domain_id, claim.source_domain_id, claim.normalized_name, claim.source_team_id, claim.target_team_id, claim.provider_region, claim.custom_return_path, claim.tls_mode, claim.status, claim.blocked_reason, claim.failure_reason, claim.record_name, claim.record_value, claim.record_ttl, claim.verification_requested_at, claim.verified_at, claim.completed_at, claim.expires_at, claim.reconcile_locked_at, claim.reconcile_locked_by, claim.created_by, claim.created_at, claim.updated_at
FROM domain_claims AS claim
WHERE claim.id = $1
`

type GetDomainClaimByIDParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetDomainClaimByID(ctx context.Context, arg GetDomainClaimByIDParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, getDomainClaimByID, arg.ID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDomainClaimBlocked = `-- name: MarkDomainClaimBlocked :one
UPDATE domain_claims
SET status = 'blocked',
    blocked_reason = $1,
    failure_reason = NULL,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $2
  AND reconcile_locked_by = trim($3)
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type MarkDomainClaimBlockedParams struct {
	BlockedReason *string   `db:"blocked_reason" json:"blocked_reason"`
	ID            uuid.UUID `db:"id" json:"id"`
	WorkerID      string    `db:"worker_id" json:"worker_id"`
}

func (q *Queries) MarkDomainClaimBlocked(ctx context.Context, arg MarkDomainClaimBlockedParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, markDomainClaimBlocked, arg.BlockedReason, arg.ID, arg.WorkerID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDomainClaimCompleted = `-- name: MarkDomainClaimCompleted :one
UPDATE domain_claims
SET status = 'completed',
    completed_at = COALESCE(completed_at, now()),
    blocked_reason = NULL,
    failure_reason = NULL,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'verified'
  AND reconcile_locked_by = trim($2)
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type MarkDomainClaimCompletedParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WorkerID string    `db:"worker_id" json:"worker_id"`
}

func (q *Queries) MarkDomainClaimCompleted(ctx context.Context, arg MarkDomainClaimCompletedParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, markDomainClaimCompleted, arg.ID, arg.WorkerID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDomainClaimFailed = `-- name: MarkDomainClaimFailed :one
UPDATE domain_claims
SET status = 'failed',
    failure_reason = $1,
    reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $2
  AND reconcile_locked_by = trim($3)
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type MarkDomainClaimFailedParams struct {
	FailureReason *string   `db:"failure_reason" json:"failure_reason"`
	ID            uuid.UUID `db:"id" json:"id"`
	WorkerID      string    `db:"worker_id" json:"worker_id"`
}

func (q *Queries) MarkDomainClaimFailed(ctx context.Context, arg MarkDomainClaimFailedParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, markDomainClaimFailed, arg.FailureReason, arg.ID, arg.WorkerID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDomainClaimVerified = `-- name: MarkDomainClaimVerified :one
UPDATE domain_claims
SET status = 'verified',
    verified_at = COALESCE(verified_at, now()),
    blocked_reason = NULL,
    failure_reason = NULL,
    updated_at = now()
WHERE id = $1
  AND reconcile_locked_by = trim($2)
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type MarkDomainClaimVerifiedParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WorkerID string    `db:"worker_id" json:"worker_id"`
}

func (q *Queries) MarkDomainClaimVerified(ctx context.Context, arg MarkDomainClaimVerifiedParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, markDomainClaimVerified, arg.ID, arg.WorkerID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseDomainClaim = `-- name: ReleaseDomainClaim :one
UPDATE domain_claims
SET reconcile_locked_at = NULL,
    reconcile_locked_by = NULL,
    updated_at = now()
WHERE id = $1
  AND reconcile_locked_by = trim($2)
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type ReleaseDomainClaimParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WorkerID string    `db:"worker_id" json:"worker_id"`
}

func (q *Queries) ReleaseDomainClaim(ctx context.Context, arg ReleaseDomainClaimParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, releaseDomainClaim, arg.ID, arg.WorkerID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestDomainClaimVerification = `-- name: RequestDomainClaimVerification :one
UPDATE domain_claims
SET verification_requested_at = now(),
    blocked_reason = NULL,
    failure_reason = NULL,
    updated_at = now()
WHERE target_domain_id = $1
  AND target_team_id = $2
  AND status IN ('pending', 'blocked')
  AND expires_at > now()
RETURNING id, target_domain_id, source_domain_id, normalized_name, source_team_id, target_team_id, provider_region, custom_return_path, tls_mode, status, blocked_reason, failure_reason, record_name, record_value, record_ttl, verification_requested_at, verified_at, completed_at, expires_at, reconcile_locked_at, reconcile_locked_by, created_by, created_at, updated_at
`

type RequestDomainClaimVerificationParams struct {
	TargetDomainID uuid.UUID `db:"target_domain_id" json:"target_domain_id"`
	TargetTeamID   uuid.UUID `db:"target_team_id" json:"target_team_id"`
}

func (q *Queries) RequestDomainClaimVerification(ctx context.Context, arg RequestDomainClaimVerificationParams) (DomainClaim, error) {
	row := q.db.QueryRow(ctx, requestDomainClaimVerification, arg.TargetDomainID, arg.TargetTeamID)
	var i DomainClaim
	err := row.Scan(
		&i.ID,
		&i.TargetDomainID,
		&i.SourceDomainID,
		&i.NormalizedName,
		&i.SourceTeamID,
		&i.TargetTeamID,
		&i.ProviderRegion,
		&i.CustomReturnPath,
		&i.TlsMode,
		&i.Status,
		&i.BlockedReason,
		&i.FailureReason,
		&i.RecordName,
		&i.RecordValue,
		&i.RecordTtl,
		&i.VerificationRequestedAt,
		&i.VerifiedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.ReconcileLockedAt,
		&i.ReconcileLockedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
