// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createEmailTenant = `-- name: CreateEmailTenant :one
INSERT INTO email_tenants (
    team_id,
    provider,
    region,
    external_name,
    suppression_scope,
    reputation_policy
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (team_id, provider, region)
DO UPDATE SET updated_at = email_tenants.updated_at
RETURNING id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
`

type CreateEmailTenantParams struct {
	TeamID           uuid.UUID `db:"team_id" json:"team_id"`
	Provider         string    `db:"provider" json:"provider"`
	Region           string    `db:"region" json:"region"`
	ExternalName     string    `db:"external_name" json:"external_name"`
	SuppressionScope string    `db:"suppression_scope" json:"suppression_scope"`
	ReputationPolicy string    `db:"reputation_policy" json:"reputation_policy"`
}

func (q *Queries) CreateEmailTenant(ctx context.Context, arg CreateEmailTenantParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, createEmailTenant,
		arg.TeamID,
		arg.Provider,
		arg.Region,
		arg.ExternalName,
		arg.SuppressionScope,
		arg.ReputationPolicy,
	)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailTenant = `-- name: DeleteEmailTenant :execrows
DELETE FROM email_tenants
WHERE id = $1
  AND status = 'deleting'
`

type DeleteEmailTenantParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteEmailTenant(ctx context.Context, arg DeleteEmailTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailTenant, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveEmailTenantExternalName = `-- name: GetActiveEmailTenantExternalName :one
SELECT external_name
FROM email_tenants
WHERE team_id = $1
  AND provider = $2
  AND region = $3
  AND status = 'active'
FOR SHARE
`

type GetActiveEmailTenantExternalNameParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Provider string    `db:"provider" json:"provider"`
	Region   string    `db:"region" json:"region"`
}

func (q *Queries) GetActiveEmailTenantExternalName(ctx context.Context, arg GetActiveEmailTenantExternalNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getActiveEmailTenantExternalName, arg.TeamID, arg.Provider, arg.Region)
	var external_name string
	err := row.Scan(&external_name)
	return external_name, err
}

const getEmailTenant = `-- name: GetEmailTenant :one
SELECT id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
FROM email_tenants
WHERE id = $1
`

type GetEmailTenantParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetEmailTenant(ctx context.Context, arg GetEmailTenantParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, getEmailTenant, arg.ID)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailTenantByTeamProviderRegion = `-- name: GetEmailTenantByTeamProviderRegion :one
SELECT id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
FROM email_tenants
WHERE team_id = $1
  AND provider = $2
  AND region = $3
`

type GetEmailTenantByTeamProviderRegionParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Provider string    `db:"provider" json:"provider"`
	Region   string    `db:"region" json:"region"`
}

func (q *Queries) GetEmailTenantByTeamProviderRegion(ctx context.Context, arg GetEmailTenantByTeamProviderRegionParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, getEmailTenantByTeamProviderRegion, arg.TeamID, arg.Provider, arg.Region)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailTenantActive = `-- name: MarkEmailTenantActive :one
UPDATE email_tenants
SET external_id = $1,
    tenant_arn = $2,
    status = 'active',
    failure_reason = NULL,
    updated_at = now()
WHERE id = $3
  AND status = 'provisioning'
RETURNING id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
`

type MarkEmailTenantActiveParams struct {
	ExternalID *string   `db:"external_id" json:"external_id"`
	TenantArn  *string   `db:"tenant_arn" json:"tenant_arn"`
	ID         uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkEmailTenantActive(ctx context.Context, arg MarkEmailTenantActiveParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, markEmailTenantActive, arg.ExternalID, arg.TenantArn, arg.ID)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailTenantDeleting = `-- name: MarkEmailTenantDeleting :one
UPDATE email_tenants
SET status = 'deleting',
    updated_at = now()
WHERE id = $1
  AND status IN ('active', 'paused', 'failed')
RETURNING id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
`

type MarkEmailTenantDeletingParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkEmailTenantDeleting(ctx context.Context, arg MarkEmailTenantDeletingParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, markEmailTenantDeleting, arg.ID)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailTenantFailed = `-- name: MarkEmailTenantFailed :one
UPDATE email_tenants
SET status = 'failed',
    failure_reason = $1,
    updated_at = now()
WHERE id = $2
  AND status IN ('pending', 'provisioning')
RETURNING id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
`

type MarkEmailTenantFailedParams struct {
	FailureReason *string   `db:"failure_reason" json:"failure_reason"`
	ID            uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkEmailTenantFailed(ctx context.Context, arg MarkEmailTenantFailedParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, markEmailTenantFailed, arg.FailureReason, arg.ID)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailTenantPaused = `-- name: MarkEmailTenantPaused :one
UPDATE email_tenants
SET status = 'paused',
    failure_reason = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'active'
RETURNING id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
`

type MarkEmailTenantPausedParams struct {
	FailureReason *string   `db:"failure_reason" json:"failure_reason"`
	ID            uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkEmailTenantPaused(ctx context.Context, arg MarkEmailTenantPausedParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, markEmailTenantPaused, arg.FailureReason, arg.ID)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailTenantProvisioning = `-- name: MarkEmailTenantProvisioning :one
UPDATE email_tenants
SET status = 'provisioning',
    failure_reason = NULL,
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'failed')
RETURNING id, team_id, provider, region, external_name, external_id, tenant_arn, status, suppression_scope, reputation_policy, failure_reason, created_at, updated_at
`

type MarkEmailTenantProvisioningParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkEmailTenantProvisioning(ctx context.Context, arg MarkEmailTenantProvisioningParams) (EmailTenant, error) {
	row := q.db.QueryRow(ctx, markEmailTenantProvisioning, arg.ID)
	var i EmailTenant
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.Region,
		&i.ExternalName,
		&i.ExternalID,
		&i.TenantArn,
		&i.Status,
		&i.SuppressionScope,
		&i.ReputationPolicy,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
