// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_provider_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueEmailProviderEvents = `-- name: ClaimDueEmailProviderEvents :many
WITH due AS (
    SELECT id
    FROM email_provider_events
    WHERE processed_at IS NULL
      AND dead_lettered_at IS NULL
      AND next_attempt_at IS NOT NULL
      AND next_attempt_at <= now()
    ORDER BY next_attempt_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE email_provider_events AS event
SET attempt_count = event.attempt_count + 1,
    last_attempt_at = now(),
    next_attempt_at = now() + ($1::bigint * interval '1 second')
FROM due
WHERE event.id = due.id
RETURNING event.id, event.attempt_count
`

type ClaimDueEmailProviderEventsParams struct {
	LeaseSeconds int64 `db:"lease_seconds" json:"lease_seconds"`
	BatchSize    int32 `db:"batch_size" json:"batch_size"`
}

type ClaimDueEmailProviderEventsRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AttemptCount int32     `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) ClaimDueEmailProviderEvents(ctx context.Context, arg ClaimDueEmailProviderEventsParams) ([]ClaimDueEmailProviderEventsRow, error) {
	rows, err := q.db.Query(ctx, claimDueEmailProviderEvents, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueEmailProviderEventsRow{}
	for rows.Next() {
		var i ClaimDueEmailProviderEventsRow
		if err := rows.Scan(&i.ID, &i.AttemptCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimEmailProviderEvent = `-- name: ClaimEmailProviderEvent :one
UPDATE email_provider_events
SET attempt_count = attempt_count + 1,
    last_attempt_at = now(),
    next_attempt_at = now() + ($1::bigint * interval '1 second')
WHERE id = $2
  AND processed_at IS NULL
  AND dead_lettered_at IS NULL
  AND (next_attempt_at IS NULL OR next_attempt_at <= now())
RETURNING id, attempt_count
`

type ClaimEmailProviderEventParams struct {
	LeaseSeconds int64     `db:"lease_seconds" json:"lease_seconds"`
	ID           uuid.UUID `db:"id" json:"id"`
}

type ClaimEmailProviderEventRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AttemptCount int32     `db:"attempt_count" json:"attempt_count"`
}

func (q *Queries) ClaimEmailProviderEvent(ctx context.Context, arg ClaimEmailProviderEventParams) (ClaimEmailProviderEventRow, error) {
	row := q.db.QueryRow(ctx, claimEmailProviderEvent, arg.LeaseSeconds, arg.ID)
	var i ClaimEmailProviderEventRow
	err := row.Scan(&i.ID, &i.AttemptCount)
	return i, err
}

const createEmailProviderEvent = `-- name: CreateEmailProviderEvent :one
INSERT INTO email_provider_events (
    email_message_id,
    provider,
    transport,
    provider_notification_id,
    provider_message_id,
    event_type,
    occurred_at,
    received_at,
    normalized_payload,
    provider_payload,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (provider, transport, provider_notification_id) DO NOTHING
RETURNING id, email_message_id, provider, transport, provider_notification_id, provider_message_id, event_type, occurred_at, received_at, normalized_payload, provider_payload, processed_at, attempt_count, next_attempt_at, last_attempt_at, last_error, dead_lettered_at, created_at
`

type CreateEmailProviderEventParams struct {
	EmailMessageID         *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	Provider               string             `db:"provider" json:"provider"`
	Transport              string             `db:"transport" json:"transport"`
	ProviderNotificationID string             `db:"provider_notification_id" json:"provider_notification_id"`
	ProviderMessageID      string             `db:"provider_message_id" json:"provider_message_id"`
	EventType              string             `db:"event_type" json:"event_type"`
	OccurredAt             pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ReceivedAt             pgtype.Timestamptz `db:"received_at" json:"received_at"`
	NormalizedPayload      []byte             `db:"normalized_payload" json:"normalized_payload"`
	ProviderPayload        []byte             `db:"provider_payload" json:"provider_payload"`
	NextAttemptAt          pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
}

func (q *Queries) CreateEmailProviderEvent(ctx context.Context, arg CreateEmailProviderEventParams) (EmailProviderEvent, error) {
	row := q.db.QueryRow(ctx, createEmailProviderEvent,
		arg.EmailMessageID,
		arg.Provider,
		arg.Transport,
		arg.ProviderNotificationID,
		arg.ProviderMessageID,
		arg.EventType,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.NormalizedPayload,
		arg.ProviderPayload,
		arg.NextAttemptAt,
	)
	var i EmailProviderEvent
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Provider,
		&i.Transport,
		&i.ProviderNotificationID,
		&i.ProviderMessageID,
		&i.EventType,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.NormalizedPayload,
		&i.ProviderPayload,
		&i.ProcessedAt,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.DeadLetteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deadLetterEmailProviderEvent = `-- name: DeadLetterEmailProviderEvent :execrows
UPDATE email_provider_events
SET dead_lettered_at = COALESCE(dead_lettered_at, now()),
    next_attempt_at = NULL,
    last_error = $1
WHERE id = $2
  AND processed_at IS NULL
`

type DeadLetterEmailProviderEventParams struct {
	LastError *string   `db:"last_error" json:"last_error"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeadLetterEmailProviderEvent(ctx context.Context, arg DeadLetterEmailProviderEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterEmailProviderEvent, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailProviderEventForUpdate = `-- name: GetEmailProviderEventForUpdate :one
SELECT id, email_message_id, provider, transport, provider_notification_id, provider_message_id, event_type, occurred_at, received_at, normalized_payload, provider_payload, processed_at, attempt_count, next_attempt_at, last_attempt_at, last_error, dead_lettered_at, created_at
FROM email_provider_events
WHERE id = $1
  AND provider = $2
  AND transport = $3
FOR UPDATE
`

type GetEmailProviderEventForUpdateParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Provider  string    `db:"provider" json:"provider"`
	Transport string    `db:"transport" json:"transport"`
}

func (q *Queries) GetEmailProviderEventForUpdate(ctx context.Context, arg GetEmailProviderEventForUpdateParams) (EmailProviderEvent, error) {
	row := q.db.QueryRow(ctx, getEmailProviderEventForUpdate, arg.ID, arg.Provider, arg.Transport)
	var i EmailProviderEvent
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Provider,
		&i.Transport,
		&i.ProviderNotificationID,
		&i.ProviderMessageID,
		&i.EventType,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.NormalizedPayload,
		&i.ProviderPayload,
		&i.ProcessedAt,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.DeadLetteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkEmailProviderEvent = `-- name: LinkEmailProviderEvent :execrows
UPDATE email_provider_events
SET email_message_id = $1
WHERE id = $2
  AND email_message_id IS NULL
`

type LinkEmailProviderEventParams struct {
	EmailMessageID *uuid.UUID `db:"email_message_id" json:"email_message_id"`
	ID             uuid.UUID  `db:"id" json:"id"`
}

func (q *Queries) LinkEmailProviderEvent(ctx context.Context, arg LinkEmailProviderEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkEmailProviderEvent, arg.EmailMessageID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailProviderEventProcessed = `-- name: MarkEmailProviderEventProcessed :execrows
UPDATE email_provider_events
SET processed_at = COALESCE(processed_at, now()),
    next_attempt_at = NULL,
    last_error = NULL
WHERE id = $1
`

type MarkEmailProviderEventProcessedParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkEmailProviderEventProcessed(ctx context.Context, arg MarkEmailProviderEventProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailProviderEventProcessed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleEmailProviderEvent = `-- name: RescheduleEmailProviderEvent :execrows
UPDATE email_provider_events
SET next_attempt_at = now() + ($1::bigint * interval '1 second'),
    last_error = $2
WHERE id = $3
  AND processed_at IS NULL
  AND dead_lettered_at IS NULL
`

type RescheduleEmailProviderEventParams struct {
	DelaySeconds int64     `db:"delay_seconds" json:"delay_seconds"`
	LastError    *string   `db:"last_error" json:"last_error"`
	ID           uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) RescheduleEmailProviderEvent(ctx context.Context, arg RescheduleEmailProviderEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleEmailProviderEvent, arg.DelaySeconds, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
