// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MessageTemplateCategory string

const (
	MessageTemplateCategoryOtp          MessageTemplateCategory = "otp"
	MessageTemplateCategoryWelcome      MessageTemplateCategory = "welcome"
	MessageTemplateCategoryReceipt      MessageTemplateCategory = "receipt"
	MessageTemplateCategoryAlert        MessageTemplateCategory = "alert"
	MessageTemplateCategoryNotification MessageTemplateCategory = "notification"
	MessageTemplateCategoryCustom       MessageTemplateCategory = "custom"
)

func (e *MessageTemplateCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageTemplateCategory(s)
	case string:
		*e = MessageTemplateCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageTemplateCategory: %T", src)
	}
	return nil
}

type NullMessageTemplateCategory struct {
	MessageTemplateCategory MessageTemplateCategory `json:"message_template_category"`
	Valid                   bool                    `json:"valid"` // Valid is true if MessageTemplateCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageTemplateCategory) Scan(value interface{}) error {
	if value == nil {
		ns.MessageTemplateCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageTemplateCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageTemplateCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageTemplateCategory), nil
}

type AllowancePolicy struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Product          string             `db:"product" json:"product"`
	Meter            string             `db:"meter" json:"meter"`
	BillingMarket    string             `db:"billing_market" json:"billing_market"`
	Tier             string             `db:"tier" json:"tier"`
	IncludedQuantity int64              `db:"included_quantity" json:"included_quantity"`
	Cadence          string             `db:"cadence" json:"cadence"`
	EffectiveFrom    pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil   pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuditEvent struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	TeamID         *uuid.UUID         `db:"team_id" json:"team_id"`
	ActorType      string             `db:"actor_type" json:"actor_type"`
	ActorUserID    *uuid.UUID         `db:"actor_user_id" json:"actor_user_id"`
	ActorSessionID *string            `db:"actor_session_id" json:"actor_session_id"`
	ActorTokenID   *uuid.UUID         `db:"actor_token_id" json:"actor_token_id"`
	Action         string             `db:"action" json:"action"`
	ResourceType   string             `db:"resource_type" json:"resource_type"`
	ResourceID     string             `db:"resource_id" json:"resource_id"`
	Outcome        string             `db:"outcome" json:"outcome"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	RequestID      *string            `db:"request_id" json:"request_id"`
	IpAddress      *string            `db:"ip_address" json:"ip_address"`
	UserAgent      *string            `db:"user_agent" json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthenticationChallenge struct {
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	UserID     *uuid.UUID         `db:"user_id" json:"user_id"`
	Purpose    string             `db:"purpose" json:"purpose"`
	State      []byte             `db:"state" json:"state"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BillingMarket struct {
	Code      string `db:"code" json:"code"`
	Currency  string `db:"currency" json:"currency"`
	IsEnabled bool   `db:"is_enabled" json:"is_enabled"`
}

type Broadcast struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	TeamID                   uuid.UUID          `db:"team_id" json:"team_id"`
	Name                     string             `db:"name" json:"name"`
	Status                   string             `db:"status" json:"status"`
	SegmentID                uuid.UUID          `db:"segment_id" json:"segment_id"`
	TopicID                  *uuid.UUID         `db:"topic_id" json:"topic_id"`
	FromEmail                *string            `db:"from_email" json:"from_email"`
	FromName                 *string            `db:"from_name" json:"from_name"`
	ReplyToEmail             *string            `db:"reply_to_email" json:"reply_to_email"`
	Subject                  string             `db:"subject" json:"subject"`
	PreviewText              *string            `db:"preview_text" json:"preview_text"`
	HtmlBody                 string             `db:"html_body" json:"html_body"`
	TextBody                 *string            `db:"text_body" json:"text_body"`
	VariableBindings         []byte             `db:"variable_bindings" json:"variable_bindings"`
	ScheduledAt              pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	QueuedAt                 pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	SentAt                   pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	CanceledAt               pgtype.Timestamptz `db:"canceled_at" json:"canceled_at"`
	RecipientsMaterializedAt pgtype.Timestamptz `db:"recipients_materialized_at" json:"recipients_materialized_at"`
	AudienceCount            int64              `db:"audience_count" json:"audience_count"`
	EligibleCount            int64              `db:"eligible_count" json:"eligible_count"`
	SuppressedCount          int64              `db:"suppressed_count" json:"suppressed_count"`
	QueuedCount              int64              `db:"queued_count" json:"queued_count"`
	FailedCount              int64              `db:"failed_count" json:"failed_count"`
	Revision                 int64              `db:"revision" json:"revision"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type BroadcastRecipient struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	BroadcastID      uuid.UUID          `db:"broadcast_id" json:"broadcast_id"`
	ContactID        *uuid.UUID         `db:"contact_id" json:"contact_id"`
	Email            string             `db:"email" json:"email"`
	NormalizedEmail  string             `db:"normalized_email" json:"normalized_email"`
	FirstName        *string            `db:"first_name" json:"first_name"`
	LastName         *string            `db:"last_name" json:"last_name"`
	ContactSnapshot  []byte             `db:"contact_snapshot" json:"contact_snapshot"`
	Status           string             `db:"status" json:"status"`
	ExclusionReason  *string            `db:"exclusion_reason" json:"exclusion_reason"`
	EmailMessageID   *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	AttemptCount     int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt    pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastErrorCode    *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage *string            `db:"last_error_message" json:"last_error_message"`
	FailedAt         pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	QueuedAt         pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
}

type ChannelSuppression struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	Channel           string             `db:"channel" json:"channel"`
	Address           string             `db:"address" json:"address"`
	NormalizedAddress string             `db:"normalized_address" json:"normalized_address"`
	Reason            string             `db:"reason" json:"reason"`
	Origin            string             `db:"origin" json:"origin"`
	SourceID          *string            `db:"source_id" json:"source_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Contact struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	Email               string             `db:"email" json:"email"`
	FirstName           *string            `db:"first_name" json:"first_name"`
	LastName            *string            `db:"last_name" json:"last_name"`
	Unsubscribed        bool               `db:"unsubscribed" json:"unsubscribed"`
	Phone               *string            `db:"phone" json:"phone"`
	NormalizedPhone     *string            `db:"normalized_phone" json:"normalized_phone"`
	PhoneCountry        *string            `db:"phone_country" json:"phone_country"`
	SmsConsentStatus    string             `db:"sms_consent_status" json:"sms_consent_status"`
	SmsConsentUpdatedAt pgtype.Timestamptz `db:"sms_consent_updated_at" json:"sms_consent_updated_at"`
	SmsConsentSource    *string            `db:"sms_consent_source" json:"sms_consent_source"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContactProperty struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	TeamID         uuid.UUID          `db:"team_id" json:"team_id"`
	Key            string             `db:"key" json:"key"`
	ValueType      string             `db:"value_type" json:"value_type"`
	FallbackString *string            `db:"fallback_string" json:"fallback_string"`
	FallbackNumber pgtype.Numeric     `db:"fallback_number" json:"fallback_number"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContactPropertyValue struct {
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	ContactID         uuid.UUID          `db:"contact_id" json:"contact_id"`
	ContactPropertyID uuid.UUID          `db:"contact_property_id" json:"contact_property_id"`
	ValueType         string             `db:"value_type" json:"value_type"`
	StringValue       *string            `db:"string_value" json:"string_value"`
	NumberValue       pgtype.Numeric     `db:"number_value" json:"number_value"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContactSegment struct {
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	ContactID uuid.UUID          `db:"contact_id" json:"contact_id"`
	SegmentID uuid.UUID          `db:"segment_id" json:"segment_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ContactTopicSubscription struct {
	TeamID       uuid.UUID          `db:"team_id" json:"team_id"`
	ContactID    uuid.UUID          `db:"contact_id" json:"contact_id"`
	TopicID      uuid.UUID          `db:"topic_id" json:"topic_id"`
	Subscription string             `db:"subscription" json:"subscription"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Currency struct {
	Code      string `db:"code" json:"code"`
	MinorUnit int16  `db:"minor_unit" json:"minor_unit"`
	IsEnabled bool   `db:"is_enabled" json:"is_enabled"`
}

type Domain struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	TeamID                    uuid.UUID          `db:"team_id" json:"team_id"`
	Name                      string             `db:"name" json:"name"`
	NormalizedName            string             `db:"normalized_name" json:"normalized_name"`
	Provider                  string             `db:"provider" json:"provider"`
	ProviderAccount           string             `db:"provider_account" json:"provider_account"`
	ProviderRegion            string             `db:"provider_region" json:"provider_region"`
	ProviderExternalID        *string            `db:"provider_external_id" json:"provider_external_id"`
	Status                    string             `db:"status" json:"status"`
	ProviderStatus            *string            `db:"provider_status" json:"provider_status"`
	TlsMode                   string             `db:"tls_mode" json:"tls_mode"`
	CustomReturnPath          string             `db:"custom_return_path" json:"custom_return_path"`
	HealthStatus              string             `db:"health_status" json:"health_status"`
	ConsecutiveHealthFailures int32              `db:"consecutive_health_failures" json:"consecutive_health_failures"`
	FailureReason             *string            `db:"failure_reason" json:"failure_reason"`
	LastError                 *string            `db:"last_error" json:"last_error"`
	SubmittedAt               pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	VerifiedAt                pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	DisabledAt                pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastCheckedAt             pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	NextCheckAt               pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	LastHealthCheckedAt       pgtype.Timestamptz `db:"last_health_checked_at" json:"last_health_checked_at"`
	LastHealthFailureAt       pgtype.Timestamptz `db:"last_health_failure_at" json:"last_health_failure_at"`
	ReconciliationAttempts    int32              `db:"reconciliation_attempts" json:"reconciliation_attempts"`
	ReconcileLockedAt         pgtype.Timestamptz `db:"reconcile_locked_at" json:"reconcile_locked_at"`
	ReconcileLockedBy         *string            `db:"reconcile_locked_by" json:"reconcile_locked_by"`
	CreatedBy                 *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DomainClaim struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	TargetDomainID          uuid.UUID          `db:"target_domain_id" json:"target_domain_id"`
	SourceDomainID          *uuid.UUID         `db:"source_domain_id" json:"source_domain_id"`
	NormalizedName          string             `db:"normalized_name" json:"normalized_name"`
	SourceTeamID            uuid.UUID          `db:"source_team_id" json:"source_team_id"`
	TargetTeamID            uuid.UUID          `db:"target_team_id" json:"target_team_id"`
	ProviderRegion          string             `db:"provider_region" json:"provider_region"`
	CustomReturnPath        string             `db:"custom_return_path" json:"custom_return_path"`
	TlsMode                 string             `db:"tls_mode" json:"tls_mode"`
	Status                  string             `db:"status" json:"status"`
	BlockedReason           *string            `db:"blocked_reason" json:"blocked_reason"`
	FailureReason           *string            `db:"failure_reason" json:"failure_reason"`
	RecordName              string             `db:"record_name" json:"record_name"`
	RecordValue             string             `db:"record_value" json:"record_value"`
	RecordTtl               string             `db:"record_ttl" json:"record_ttl"`
	VerificationRequestedAt pgtype.Timestamptz `db:"verification_requested_at" json:"verification_requested_at"`
	VerifiedAt              pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CompletedAt             pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ReconcileLockedAt       pgtype.Timestamptz `db:"reconcile_locked_at" json:"reconcile_locked_at"`
	ReconcileLockedBy       *string            `db:"reconcile_locked_by" json:"reconcile_locked_by"`
	CreatedBy               *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DomainDnsRecord struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	DomainID     uuid.UUID          `db:"domain_id" json:"domain_id"`
	Purpose      string             `db:"purpose" json:"purpose"`
	Record       string             `db:"record" json:"record"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	Value        string             `db:"value" json:"value"`
	Ttl          string             `db:"ttl" json:"ttl"`
	Priority     *int32             `db:"priority" json:"priority"`
	Status       string             `db:"status" json:"status"`
	IsCurrent    bool               `db:"is_current" json:"is_current"`
	VerifiedAt   pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	SupersededAt pgtype.Timestamptz `db:"superseded_at" json:"superseded_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailChangeRequest struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	PendingEmail string             `db:"pending_email" json:"pending_email"`
	RequestedAt  pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type EmailMessage struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	TeamID                   uuid.UUID          `db:"team_id" json:"team_id"`
	SenderDomainID           *uuid.UUID         `db:"sender_domain_id" json:"sender_domain_id"`
	DeliveryProvider         string             `db:"delivery_provider" json:"delivery_provider"`
	ProviderRegion           string             `db:"provider_region" json:"provider_region"`
	MessageType              string             `db:"message_type" json:"message_type"`
	FromEmail                string             `db:"from_email" json:"from_email"`
	FromName                 *string            `db:"from_name" json:"from_name"`
	ReplyToEmail             *string            `db:"reply_to_email" json:"reply_to_email"`
	ToEmail                  string             `db:"to_email" json:"to_email"`
	ToName                   *string            `db:"to_name" json:"to_name"`
	Subject                  string             `db:"subject" json:"subject"`
	HtmlBody                 *string            `db:"html_body" json:"html_body"`
	TextBody                 *string            `db:"text_body" json:"text_body"`
	Status                   string             `db:"status" json:"status"`
	Provider                 *string            `db:"provider" json:"provider"`
	ProviderMessageID        *string            `db:"provider_message_id" json:"provider_message_id"`
	CurrentDeliveryAttemptID *uuid.UUID         `db:"current_delivery_attempt_id" json:"current_delivery_attempt_id"`
	ErrorCode                *string            `db:"error_code" json:"error_code"`
	ErrorMessage             *string            `db:"error_message" json:"error_message"`
	Metadata                 []byte             `db:"metadata" json:"metadata"`
	Recipients               []byte             `db:"recipients" json:"recipients"`
	Headers                  []byte             `db:"headers" json:"headers"`
	Attachments              []byte             `db:"attachments" json:"attachments"`
	Tags                     []byte             `db:"tags" json:"tags"`
	ScheduledAt              pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	QueuedAt                 pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	ProcessingAt             pgtype.Timestamptz `db:"processing_at" json:"processing_at"`
	SubmittedAt              pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt              pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt                 pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TemplateID               *uuid.UUID         `db:"template_id" json:"template_id"`
}

type EmailProviderEvent struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	EmailMessageID         *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	Provider               string             `db:"provider" json:"provider"`
	Transport              string             `db:"transport" json:"transport"`
	ProviderNotificationID string             `db:"provider_notification_id" json:"provider_notification_id"`
	ProviderMessageID      string             `db:"provider_message_id" json:"provider_message_id"`
	EventType              string             `db:"event_type" json:"event_type"`
	OccurredAt             pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ReceivedAt             pgtype.Timestamptz `db:"received_at" json:"received_at"`
	NormalizedPayload      []byte             `db:"normalized_payload" json:"normalized_payload"`
	ProviderPayload        []byte             `db:"provider_payload" json:"provider_payload"`
	ProcessedAt            pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	AttemptCount           int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt          pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt          pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastError              *string            `db:"last_error" json:"last_error"`
	DeadLetteredAt         pgtype.Timestamptz `db:"dead_lettered_at" json:"dead_lettered_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmailRecipient struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	EmailMessageID     uuid.UUID          `db:"email_message_id" json:"email_message_id"`
	RecipientEmail     string             `db:"recipient_email" json:"recipient_email"`
	RecipientType      string             `db:"recipient_type" json:"recipient_type"`
	Status             string             `db:"status" json:"status"`
	LastEventType      *string            `db:"last_event_type" json:"last_event_type"`
	LastEventAt        pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	LastAction         *string            `db:"last_action" json:"last_action"`
	LastStatusCode     *string            `db:"last_status_code" json:"last_status_code"`
	LastDiagnosticCode *string            `db:"last_diagnostic_code" json:"last_diagnostic_code"`
	DeliveredAt        pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt           pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	ErrorCode          *string            `db:"error_code" json:"error_code"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmailTenant struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	Provider         string             `db:"provider" json:"provider"`
	Region           string             `db:"region" json:"region"`
	ExternalName     string             `db:"external_name" json:"external_name"`
	ExternalID       *string            `db:"external_id" json:"external_id"`
	TenantArn        *string            `db:"tenant_arn" json:"tenant_arn"`
	Status           string             `db:"status" json:"status"`
	SuppressionScope string             `db:"suppression_scope" json:"suppression_scope"`
	ReputationPolicy string             `db:"reputation_policy" json:"reputation_policy"`
	FailureReason    *string            `db:"failure_reason" json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type FxRate struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	BaseCurrency   string             `db:"base_currency" json:"base_currency"`
	QuoteCurrency  string             `db:"quote_currency" json:"quote_currency"`
	Rate           pgtype.Numeric     `db:"rate" json:"rate"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type IdempotencyKey struct {
	Scope               string             `db:"scope" json:"scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	Method              string             `db:"method" json:"method"`
	Path                string             `db:"path" json:"path"`
	RequestHash         string             `db:"request_hash" json:"request_hash"`
	Status              string             `db:"status" json:"status"`
	ResponseStatus      *int32             `db:"response_status" json:"response_status"`
	ResponseBody        []byte             `db:"response_body" json:"response_body"`
	ResponseContentType *string            `db:"response_content_type" json:"response_content_type"`
	ResponseHeaders     []byte             `db:"response_headers" json:"response_headers"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	CompletedAt         pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MessageDeliveryAttempt struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	Channel            string             `db:"channel" json:"channel"`
	EmailMessageID     *uuid.UUID         `db:"email_message_id" json:"email_message_id"`
	SmsMessageID       *uuid.UUID         `db:"sms_message_id" json:"sms_message_id"`
	AttemptNumber      int32              `db:"attempt_number" json:"attempt_number"`
	Status             string             `db:"status" json:"status"`
	Provider           *string            `db:"provider" json:"provider"`
	ProviderAccount    string             `db:"provider_account" json:"provider_account"`
	ProviderMessageID  *string            `db:"provider_message_id" json:"provider_message_id"`
	ProviderStatus     *string            `db:"provider_status" json:"provider_status"`
	SenderDomainID     *uuid.UUID         `db:"sender_domain_id" json:"sender_domain_id"`
	SenderID           *uuid.UUID         `db:"sender_id" json:"sender_id"`
	ErrorCode          *string            `db:"error_code" json:"error_code"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	ClaimedAt          pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
	RequestStartedAt   pgtype.Timestamptz `db:"request_started_at" json:"request_started_at"`
	RequestCompletedAt pgtype.Timestamptz `db:"request_completed_at" json:"request_completed_at"`
	SubmittedAt        pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	TerminalAt         pgtype.Timestamptz `db:"terminal_at" json:"terminal_at"`
	NextReconcileAt    pgtype.Timestamptz `db:"next_reconcile_at" json:"next_reconcile_at"`
	LastReconciledAt   pgtype.Timestamptz `db:"last_reconciled_at" json:"last_reconciled_at"`
	ReconcileAttempts  int32              `db:"reconcile_attempts" json:"reconcile_attempts"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MessageTemplate struct {
	ID                 uuid.UUID               `db:"id" json:"id"`
	TeamID             uuid.UUID               `db:"team_id" json:"team_id"`
	Name               string                  `db:"name" json:"name"`
	Alias              *string                 `db:"alias" json:"alias"`
	CurrentVersionID   *uuid.UUID              `db:"current_version_id" json:"current_version_id"`
	PublishedVersionID *uuid.UUID              `db:"published_version_id" json:"published_version_id"`
	NextVersionNumber  int32                   `db:"next_version_number" json:"next_version_number"`
	PublishedAt        pgtype.Timestamptz      `db:"published_at" json:"published_at"`
	CreatedAt          pgtype.Timestamptz      `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz      `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz      `db:"deleted_at" json:"deleted_at"`
	Category           MessageTemplateCategory `db:"category" json:"category"`
}

type MessageTemplatePublication struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	TemplateID  uuid.UUID          `db:"template_id" json:"template_id"`
	VersionID   uuid.UUID          `db:"version_id" json:"version_id"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type MessageTemplateVersion struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	TemplateID       uuid.UUID          `db:"template_id" json:"template_id"`
	VersionNumber    int32              `db:"version_number" json:"version_number"`
	FromEmail        *string            `db:"from_email" json:"from_email"`
	FromName         *string            `db:"from_name" json:"from_name"`
	ReplyToEmail     *string            `db:"reply_to_email" json:"reply_to_email"`
	Subject          string             `db:"subject" json:"subject"`
	HtmlBody         string             `db:"html_body" json:"html_body"`
	TextBody         *string            `db:"text_body" json:"text_body"`
	Variables        []byte             `db:"variables" json:"variables"`
	BasedOnVersionID *uuid.UUID         `db:"based_on_version_id" json:"based_on_version_id"`
	ChangeNote       *string            `db:"change_note" json:"change_note"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OauthIdentity struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Provider    string             `db:"provider" json:"provider"`
	ProviderUid string             `db:"provider_uid" json:"provider_uid"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxEvent struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Subject          string             `db:"subject" json:"subject"`
	AggregateType    string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID      uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	Payload          []byte             `db:"payload" json:"payload"`
	Headers          []byte             `db:"headers" json:"headers"`
	AvailableAt      pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attempts         int32              `db:"attempts" json:"attempts"`
	PublishFailures  int32              `db:"publish_failures" json:"publish_failures"`
	RedriveCount     int32              `db:"redrive_count" json:"redrive_count"`
	LastError        *string            `db:"last_error" json:"last_error"`
	QuarantinedAt    pgtype.Timestamptz `db:"quarantined_at" json:"quarantined_at"`
	QuarantineCode   *string            `db:"quarantine_code" json:"quarantine_code"`
	QuarantineReason *string            `db:"quarantine_reason" json:"quarantine_reason"`
	LockedAt         pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy         *string            `db:"locked_by" json:"locked_by"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OutboxEventAction struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	EventID         uuid.UUID          `db:"event_id" json:"event_id"`
	Action          string             `db:"action" json:"action"`
	ReasonCode      *string            `db:"reason_code" json:"reason_code"`
	Reason          *string            `db:"reason" json:"reason"`
	PublishFailures int32              `db:"publish_failures" json:"publish_failures"`
	RedriveCount    int32              `db:"redrive_count" json:"redrive_count"`
	ActorType       string             `db:"actor_type" json:"actor_type"`
	ActorID         *string            `db:"actor_id" json:"actor_id"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PaymentTransaction struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	TeamID                uuid.UUID          `db:"team_id" json:"team_id"`
	Provider              string             `db:"provider" json:"provider"`
	ClientReference       string             `db:"client_reference" json:"client_reference"`
	Currency              string             `db:"currency" json:"currency"`
	AmountUnits           int64              `db:"amount_units" json:"amount_units"`
	Status                string             `db:"status" json:"status"`
	ProviderTransactionID *string            `db:"provider_transaction_id" json:"provider_transaction_id"`
	PaidAt                pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Plan struct {
	Code      string             `db:"code" json:"code"`
	Name      string             `db:"name" json:"name"`
	IsEnabled bool               `db:"is_enabled" json:"is_enabled"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PlanPrice struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	PlanCode        string             `db:"plan_code" json:"plan_code"`
	BillingMarket   string             `db:"billing_market" json:"billing_market"`
	Currency        string             `db:"currency" json:"currency"`
	AmountUnits     int64              `db:"amount_units" json:"amount_units"`
	BillingInterval string             `db:"billing_interval" json:"billing_interval"`
	EffectiveFrom   pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil  pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProcessedEvent struct {
	ConsumerName string             `db:"consumer_name" json:"consumer_name"`
	EventID      uuid.UUID          `db:"event_id" json:"event_id"`
	ProcessedAt  pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
}

type ProductRate struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	Product        string             `db:"product" json:"product"`
	Meter          string             `db:"meter" json:"meter"`
	BillingMarket  string             `db:"billing_market" json:"billing_market"`
	Tier           string             `db:"tier" json:"tier"`
	Currency       string             `db:"currency" json:"currency"`
	CostUnits      int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RecoveryCode struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CodeHash  string             `db:"code_hash" json:"code_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Segment struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SenderID struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	TeamID                    uuid.UUID          `db:"team_id" json:"team_id"`
	Name                      string             `db:"name" json:"name"`
	NormalizedName            string             `db:"normalized_name" json:"normalized_name"`
	CountryCode               string             `db:"country_code" json:"country_code"`
	Purpose                   *string            `db:"purpose" json:"purpose"`
	Provider                  *string            `db:"provider" json:"provider"`
	ProviderStatus            *string            `db:"provider_status" json:"provider_status"`
	ProviderWhitelisted       bool               `db:"provider_whitelisted" json:"provider_whitelisted"`
	Status                    string             `db:"status" json:"status"`
	HealthStatus              string             `db:"health_status" json:"health_status"`
	SubmittedAt               pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	ApprovedAt                pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	RejectedAt                pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	SuspendedAt               pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	DisabledAt                pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	NextCheckAt               pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	LastCheckedAt             pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	ReconciliationAttempts    int32              `db:"reconciliation_attempts" json:"reconciliation_attempts"`
	ConsecutiveHealthFailures int32              `db:"consecutive_health_failures" json:"consecutive_health_failures"`
	LastHealthCheckedAt       pgtype.Timestamptz `db:"last_health_checked_at" json:"last_health_checked_at"`
	LastHealthFailureAt       pgtype.Timestamptz `db:"last_health_failure_at" json:"last_health_failure_at"`
	RejectionReason           *string            `db:"rejection_reason" json:"rejection_reason"`
	LastError                 *string            `db:"last_error" json:"last_error"`
	ReconcileLockedAt         pgtype.Timestamptz `db:"reconcile_locked_at" json:"reconcile_locked_at"`
	ReconcileLockedBy         *string            `db:"reconcile_locked_by" json:"reconcile_locked_by"`
	CreatedBy                 *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID                   string             `db:"id" json:"id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash            string             `db:"token_hash" json:"token_hash"`
	UserAgent            *string            `db:"user_agent" json:"user_agent"`
	IpAddress            *string            `db:"ip_address" json:"ip_address"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	CredentialVersion    int64              `db:"credential_version" json:"credential_version"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	AssuranceLevel       string             `db:"assurance_level" json:"assurance_level"`
	AuthenticatedAt      pgtype.Timestamptz `db:"authenticated_at" json:"authenticated_at"`
	MfaCompletedAt       pgtype.Timestamptz `db:"mfa_completed_at" json:"mfa_completed_at"`
}

type SmsCampaign struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	TeamID                     uuid.UUID          `db:"team_id" json:"team_id"`
	Name                       string             `db:"name" json:"name"`
	Status                     string             `db:"status" json:"status"`
	SegmentID                  uuid.UUID          `db:"segment_id" json:"segment_id"`
	SenderID                   uuid.UUID          `db:"sender_id" json:"sender_id"`
	Body                       string             `db:"body" json:"body"`
	ScheduledAt                pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	QueuedAt                   pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	CanceledAt                 pgtype.Timestamptz `db:"canceled_at" json:"canceled_at"`
	MaterializedAt             pgtype.Timestamptz `db:"materialized_at" json:"materialized_at"`
	SentAt                     pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	AudienceCount              int64              `db:"audience_count" json:"audience_count"`
	EligibleCount              int64              `db:"eligible_count" json:"eligible_count"`
	ExcludedCount              int64              `db:"excluded_count" json:"excluded_count"`
	FailedCount                int64              `db:"failed_count" json:"failed_count"`
	EstimatedSegments          int64              `db:"estimated_segments" json:"estimated_segments"`
	EstimatedCostUnits         int64              `db:"estimated_cost_units" json:"estimated_cost_units"`
	EstimatedBillableCostUnits int64              `db:"estimated_billable_cost_units" json:"estimated_billable_cost_units"`
	PreflightAllowanceSegments int64              `db:"preflight_allowance_segments" json:"preflight_allowance_segments"`
	ActualSegments             int64              `db:"actual_segments" json:"actual_segments"`
	ActualChargeUnits          int64              `db:"actual_charge_units" json:"actual_charge_units"`
	Currency                   *string            `db:"currency" json:"currency"`
	PreflightBalanceUnits      *int64             `db:"preflight_balance_units" json:"preflight_balance_units"`
	PreflightAt                pgtype.Timestamptz `db:"preflight_at" json:"preflight_at"`
	RateLimitPerSecond         int32              `db:"rate_limit_per_second" json:"rate_limit_per_second"`
	DailySendLimit             *int32             `db:"daily_send_limit" json:"daily_send_limit"`
	Revision                   int64              `db:"revision" json:"revision"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SmsCampaignRecipient struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TeamID                 uuid.UUID          `db:"team_id" json:"team_id"`
	CampaignID             uuid.UUID          `db:"campaign_id" json:"campaign_id"`
	ContactID              *uuid.UUID         `db:"contact_id" json:"contact_id"`
	Phone                  *string            `db:"phone" json:"phone"`
	PhoneCountry           *string            `db:"phone_country" json:"phone_country"`
	ContactSnapshot        []byte             `db:"contact_snapshot" json:"contact_snapshot"`
	Status                 string             `db:"status" json:"status"`
	ExclusionReason        *string            `db:"exclusion_reason" json:"exclusion_reason"`
	SmsMessageID           *uuid.UUID         `db:"sms_message_id" json:"sms_message_id"`
	RenderedBody           *string            `db:"rendered_body" json:"rendered_body"`
	AttemptCount           int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt          pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	FailureCode            *string            `db:"failure_code" json:"failure_code"`
	FailureMessage         *string            `db:"failure_message" json:"failure_message"`
	Encoding               *string            `db:"encoding" json:"encoding"`
	EstimatedSegments      *int32             `db:"estimated_segments" json:"estimated_segments"`
	EstimatedUnitCostUnits *int64             `db:"estimated_unit_cost_units" json:"estimated_unit_cost_units"`
	EstimatedCostUnits     *int64             `db:"estimated_cost_units" json:"estimated_cost_units"`
	ActualSegments         *int32             `db:"actual_segments" json:"actual_segments"`
	ActualChargeUnits      *int64             `db:"actual_charge_units" json:"actual_charge_units"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	QueuedAt               pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
}

type SmsConsentEvent struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	ContactID  *uuid.UUID         `db:"contact_id" json:"contact_id"`
	Phone      string             `db:"phone" json:"phone"`
	Action     string             `db:"action" json:"action"`
	Source     string             `db:"source" json:"source"`
	SourceID   *string            `db:"source_id" json:"source_id"`
	RecordedAt pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type SmsMessage struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	SenderID           *uuid.UUID         `db:"sender_id" json:"sender_id"`
	ToNumber           string             `db:"to_number" json:"to_number"`
	FromName           string             `db:"from_name" json:"from_name"`
	Body               string             `db:"body" json:"body"`
	Status             string             `db:"status" json:"status"`
	ProviderID         *string            `db:"provider_id" json:"provider_id"`
	ProviderMessageID  *string            `db:"provider_message_id" json:"provider_message_id"`
	Segments           int32              `db:"segments" json:"segments"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	ScheduledAt        pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	SubmittedAt        pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt        pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
}

type SmsRate struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
	RouteType          string             `db:"route_type" json:"route_type"`
	Tier               string             `db:"tier" json:"tier"`
	Currency           string             `db:"currency" json:"currency"`
	CostUnits          int64              `db:"cost_units" json:"cost_units"`
	EffectiveFrom      pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil     pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SubscriptionCharge struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	SubscriptionID  uuid.UUID          `db:"subscription_id" json:"subscription_id"`
	TeamID          uuid.UUID          `db:"team_id" json:"team_id"`
	PlanPriceID     uuid.UUID          `db:"plan_price_id" json:"plan_price_id"`
	PlanCode        string             `db:"plan_code" json:"plan_code"`
	BillingMarket   string             `db:"billing_market" json:"billing_market"`
	Currency        string             `db:"currency" json:"currency"`
	PeriodStart     pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd       pgtype.Timestamptz `db:"period_end" json:"period_end"`
	AmountUnits     int64              `db:"amount_units" json:"amount_units"`
	Status          string             `db:"status" json:"status"`
	FailureCode     *string            `db:"failure_code" json:"failure_code"`
	AttemptCount    int32              `db:"attempt_count" json:"attempt_count"`
	LastAttemptedAt pgtype.Timestamptz `db:"last_attempted_at" json:"last_attempted_at"`
	AppliedAt       pgtype.Timestamptz `db:"applied_at" json:"applied_at"`
	ReferenceID     string             `db:"reference_id" json:"reference_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SubscriptionCredit struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	SubscriptionID       uuid.UUID          `db:"subscription_id" json:"subscription_id"`
	SubscriptionChargeID uuid.UUID          `db:"subscription_charge_id" json:"subscription_charge_id"`
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	PlanCode             string             `db:"plan_code" json:"plan_code"`
	BillingMarket        string             `db:"billing_market" json:"billing_market"`
	Currency             string             `db:"currency" json:"currency"`
	PeriodStart          pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd            pgtype.Timestamptz `db:"period_end" json:"period_end"`
	GrantedUnits         int64              `db:"granted_units" json:"granted_units"`
	ConsumedUnits        int64              `db:"consumed_units" json:"consumed_units"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Team struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	MarketCode string             `db:"market_code" json:"market_code"`
	Phone      string             `db:"phone" json:"phone"`
	Address    string             `db:"address" json:"address"`
	Website    *string            `db:"website" json:"website"`
	Status     string             `db:"status" json:"status"`
	CreatedBy  *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamInvitation struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	Email      string             `db:"email" json:"email"`
	Role       string             `db:"role" json:"role"`
	Status     string             `db:"status" json:"status"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	InvitedBy  *uuid.UUID         `db:"invited_by" json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	DeclinedAt pgtype.Timestamptz `db:"declined_at" json:"declined_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamSubscription struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TeamID                 uuid.UUID          `db:"team_id" json:"team_id"`
	PlanCode               string             `db:"plan_code" json:"plan_code"`
	Status                 string             `db:"status" json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	PendingPlanCode        *string            `db:"pending_plan_code" json:"pending_plan_code"`
	PendingPlanEffectiveAt pgtype.Timestamptz `db:"pending_plan_effective_at" json:"pending_plan_effective_at"`
	CancelAtPeriodEnd      bool               `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamToken struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Permissions []string           `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID         `db:"created_by" json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamWallet struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	Currency      string             `db:"currency" json:"currency"`
	BalanceUnits  int64              `db:"balance_units" json:"balance_units"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Topic struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	Name                string             `db:"name" json:"name"`
	Description         *string            `db:"description" json:"description"`
	DefaultSubscription string             `db:"default_subscription" json:"default_subscription"`
	Visibility          string             `db:"visibility" json:"visibility"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TotpCredential struct {
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	SecretCiphertext []byte             `db:"secret_ciphertext" json:"secret_ciphertext"`
	VerifiedAt       pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	LastUsedStep     *int64             `db:"last_used_step" json:"last_used_step"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UsageAllowance struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	AllowancePolicyID uuid.UUID          `db:"allowance_policy_id" json:"allowance_policy_id"`
	Product           string             `db:"product" json:"product"`
	Meter             string             `db:"meter" json:"meter"`
	BillingMarket     string             `db:"billing_market" json:"billing_market"`
	Tier              string             `db:"tier" json:"tier"`
	PeriodStart       pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd         pgtype.Timestamptz `db:"period_end" json:"period_end"`
	IncludedQuantity  int64              `db:"included_quantity" json:"included_quantity"`
	ConsumedQuantity  int64              `db:"consumed_quantity" json:"consumed_quantity"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UsageAuthorization struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	Product              string             `db:"product" json:"product"`
	Meter                string             `db:"meter" json:"meter"`
	ReferenceID          string             `db:"reference_id" json:"reference_id"`
	UsageAllowanceID     *uuid.UUID         `db:"usage_allowance_id" json:"usage_allowance_id"`
	SmsRateID            *uuid.UUID         `db:"sms_rate_id" json:"sms_rate_id"`
	FxRateID             *uuid.UUID         `db:"fx_rate_id" json:"fx_rate_id"`
	ProductRateID        *uuid.UUID         `db:"product_rate_id" json:"product_rate_id"`
	BillingMarket        string             `db:"billing_market" json:"billing_market"`
	DestinationCountry   *string            `db:"destination_country" json:"destination_country"`
	RouteType            *string            `db:"route_type" json:"route_type"`
	TotalQuantity        int64              `db:"total_quantity" json:"total_quantity"`
	AllowanceQuantity    int64              `db:"allowance_quantity" json:"allowance_quantity"`
	BillableQuantity     int64              `db:"billable_quantity" json:"billable_quantity"`
	UnitCostUnits        int64              `db:"unit_cost_units" json:"unit_cost_units"`
	AmountUnits          int64              `db:"amount_units" json:"amount_units"`
	SubscriptionCreditID *uuid.UUID         `db:"subscription_credit_id" json:"subscription_credit_id"`
	FullCostUnits        int64              `db:"full_cost_units" json:"full_cost_units"`
	CreditConsumedUnits  int64              `db:"credit_consumed_units" json:"credit_consumed_units"`
	WalletDebitUnits     int64              `db:"wallet_debit_units" json:"wallet_debit_units"`
	Currency             string             `db:"currency" json:"currency"`
	Tier                 string             `db:"tier" json:"tier"`
	PricedAt             pgtype.Timestamptz `db:"priced_at" json:"priced_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	EmailVerified     bool               `db:"email_verified" json:"email_verified"`
	Name              string             `db:"name" json:"name"`
	PasswordHash      *string            `db:"password_hash" json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CredentialVersion int64              `db:"credential_version" json:"credential_version"`
	SecurityUpdatedAt pgtype.Timestamptz `db:"security_updated_at" json:"security_updated_at"`
}

type VerificationToken struct {
	Identifier string             `db:"identifier" json:"identifier"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WalletLedger struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	UsageAuthorizationID *uuid.UUID         `db:"usage_authorization_id" json:"usage_authorization_id"`
	SubscriptionChargeID *uuid.UUID         `db:"subscription_charge_id" json:"subscription_charge_id"`
	PaymentTransactionID *uuid.UUID         `db:"payment_transaction_id" json:"payment_transaction_id"`
	AmountUnits          int64              `db:"amount_units" json:"amount_units"`
	TransactionType      string             `db:"transaction_type" json:"transaction_type"`
	ReferenceID          string             `db:"reference_id" json:"reference_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WebhookDeliveryAttempt struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	DeliveryID       uuid.UUID          `db:"delivery_id" json:"delivery_id"`
	AttemptNumber    int32              `db:"attempt_number" json:"attempt_number"`
	Outcome          string             `db:"outcome" json:"outcome"`
	RequestTimestamp pgtype.Timestamptz `db:"request_timestamp" json:"request_timestamp"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DurationMs       int64              `db:"duration_ms" json:"duration_ms"`
	ResponseStatus   *int32             `db:"response_status" json:"response_status"`
	ResponseHeaders  []byte             `db:"response_headers" json:"response_headers"`
	ResponseBody     *string            `db:"response_body" json:"response_body"`
	ErrorMessage     *string            `db:"error_message" json:"error_message"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebhookEndpoint struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	Url                 string             `db:"url" json:"url"`
	SigningSecret       []byte             `db:"signing_secret" json:"signing_secret"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	SubscribedEvents    []string           `db:"subscribed_events" json:"subscribed_events"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt          pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	ConsecutiveFailures int32              `db:"consecutive_failures" json:"consecutive_failures"`
	LastFailureAt       pgtype.Timestamptz `db:"last_failure_at" json:"last_failure_at"`
	DisabledReason      *string            `db:"disabled_reason" json:"disabled_reason"`
}

type WebhookEvent struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ObjectType string             `db:"object_type" json:"object_type"`
	ObjectID   *uuid.UUID         `db:"object_id" json:"object_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
