// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_identities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (
    user_id,
    provider,
    provider_uid
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, provider, provider_uid, created_at
`

type CreateOAuthIdentityParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Provider    string    `db:"provider" json:"provider"`
	ProviderUid string    `db:"provider_uid" json:"provider_uid"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity, arg.UserID, arg.Provider, arg.ProviderUid)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_uid, created_at
FROM oauth_identities
WHERE provider = $1
  AND provider_uid = $2
`

type GetOAuthIdentityParams struct {
	Provider    string `db:"provider" json:"provider"`
	ProviderUid string `db:"provider_uid" json:"provider_uid"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUid)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthIdentitiesByUserID = `-- name: ListOAuthIdentitiesByUserID :many
SELECT id, user_id, provider, provider_uid, created_at
FROM oauth_identities
WHERE user_id = $1
ORDER BY created_at ASC
`

type ListOAuthIdentitiesByUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListOAuthIdentitiesByUserID(ctx context.Context, arg ListOAuthIdentitiesByUserIDParams) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, listOAuthIdentitiesByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdentity{}
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
