// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (
    team_id,
    provider,
    client_reference,
    currency,
    amount_units
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5
FROM team_wallets tw
WHERE tw.team_id = $1
  AND tw.currency = $4
RETURNING id, team_id, provider, client_reference, currency, amount_units, status, provider_transaction_id, paid_at, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	Provider        string    `db:"provider" json:"provider"`
	ClientReference string    `db:"client_reference" json:"client_reference"`
	Currency        string    `db:"currency" json:"currency"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.TeamID,
		arg.Provider,
		arg.ClientReference,
		arg.Currency,
		arg.AmountUnits,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ClientReference,
		&i.Currency,
		&i.AmountUnits,
		&i.Status,
		&i.ProviderTransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByClientReference = `-- name: GetPaymentTransactionByClientReference :one
SELECT id, team_id, provider, client_reference, currency, amount_units, status, provider_transaction_id, paid_at, created_at, updated_at
FROM payment_transactions
WHERE provider = $1
  AND client_reference = $2
`

type GetPaymentTransactionByClientReferenceParams struct {
	Provider        string `db:"provider" json:"provider"`
	ClientReference string `db:"client_reference" json:"client_reference"`
}

func (q *Queries) GetPaymentTransactionByClientReference(ctx context.Context, arg GetPaymentTransactionByClientReferenceParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getPaymentTransactionByClientReference, arg.Provider, arg.ClientReference)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ClientReference,
		&i.Currency,
		&i.AmountUnits,
		&i.Status,
		&i.ProviderTransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByID = `-- name: GetPaymentTransactionByID :one
SELECT id, team_id, provider, client_reference, currency, amount_units, status, provider_transaction_id, paid_at, created_at, updated_at
FROM payment_transactions
WHERE id = $1
  AND team_id = $2
`

type GetPaymentTransactionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetPaymentTransactionByID(ctx context.Context, arg GetPaymentTransactionByIDParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getPaymentTransactionByID, arg.ID, arg.TeamID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ClientReference,
		&i.Currency,
		&i.AmountUnits,
		&i.Status,
		&i.ProviderTransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentTransactionsByTeam = `-- name: ListPaymentTransactionsByTeam :many
SELECT id, team_id, provider, client_reference, currency, amount_units, status, provider_transaction_id, paid_at, created_at, updated_at
FROM payment_transactions
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListPaymentTransactionsByTeamParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListPaymentTransactionsByTeam(ctx context.Context, arg ListPaymentTransactionsByTeamParams) ([]PaymentTransaction, error) {
	rows, err := q.db.Query(ctx, listPaymentTransactionsByTeam, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTransaction{}
	for rows.Next() {
		var i PaymentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Provider,
			&i.ClientReference,
			&i.Currency,
			&i.AmountUnits,
			&i.Status,
			&i.ProviderTransactionID,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentTransactionFailed = `-- name: MarkPaymentTransactionFailed :one
UPDATE payment_transactions
SET status = 'failed',
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status = 'pending'
RETURNING id, team_id, provider, client_reference, currency, amount_units, status, provider_transaction_id, paid_at, created_at, updated_at
`

type MarkPaymentTransactionFailedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkPaymentTransactionFailed(ctx context.Context, arg MarkPaymentTransactionFailedParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, markPaymentTransactionFailed, arg.ID, arg.TeamID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ClientReference,
		&i.Currency,
		&i.AmountUnits,
		&i.Status,
		&i.ProviderTransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentTransactionPaid = `-- name: MarkPaymentTransactionPaid :one
UPDATE payment_transactions
SET status = 'paid',
    provider_transaction_id = $1,
    paid_at = now(),
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND amount_units = $4
  AND status = 'pending'
RETURNING id, team_id, provider, client_reference, currency, amount_units, status, provider_transaction_id, paid_at, created_at, updated_at
`

type MarkPaymentTransactionPaidParams struct {
	ProviderTransactionID *string   `db:"provider_transaction_id" json:"provider_transaction_id"`
	ID                    uuid.UUID `db:"id" json:"id"`
	TeamID                uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits           int64     `db:"amount_units" json:"amount_units"`
}

func (q *Queries) MarkPaymentTransactionPaid(ctx context.Context, arg MarkPaymentTransactionPaidParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, markPaymentTransactionPaid,
		arg.ProviderTransactionID,
		arg.ID,
		arg.TeamID,
		arg.AmountUnits,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ClientReference,
		&i.Currency,
		&i.AmountUnits,
		&i.Status,
		&i.ProviderTransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
