// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActivePlanPrice = `-- name: GetActivePlanPrice :one
SELECT id, plan_code, billing_market, currency, amount_units, billing_interval, effective_from, effective_until, created_at
FROM plan_prices
WHERE plan_code = $1
  AND billing_market = $2
  AND billing_interval = 'monthly'
  AND effective_from <= $3
  AND (effective_until IS NULL OR effective_until > $3)
ORDER BY effective_from DESC
LIMIT 1
`

type GetActivePlanPriceParams struct {
	PlanCode      string             `db:"plan_code" json:"plan_code"`
	BillingMarket string             `db:"billing_market" json:"billing_market"`
	PricedAt      pgtype.Timestamptz `db:"priced_at" json:"priced_at"`
}

func (q *Queries) GetActivePlanPrice(ctx context.Context, arg GetActivePlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, getActivePlanPrice, arg.PlanCode, arg.BillingMarket, arg.PricedAt)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanCode,
		&i.BillingMarket,
		&i.Currency,
		&i.AmountUnits,
		&i.BillingInterval,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT code, name, is_enabled, created_at, updated_at
FROM plans
WHERE code = $1
`

type GetPlanParams struct {
	Code string `db:"code" json:"code"`
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, arg.Code)
	var i Plan
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPlans = `-- name: ListEnabledPlans :many
SELECT code, name, is_enabled, created_at, updated_at
FROM plans
WHERE is_enabled = true
ORDER BY CASE code
    WHEN 'growth' THEN 1
    WHEN 'scale' THEN 2
    WHEN 'enterprise' THEN 3
    ELSE 4
END, code
`

func (q *Queries) ListEnabledPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listEnabledPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansForTeam = `-- name: ListPlansForTeam :many
SELECT
    plan.code,
    plan.name,
    subscription.plan_code AS current_plan_code,
    subscription.pending_plan_code,
    subscription.current_period_end,
    COALESCE(price.id, '00000000-0000-0000-0000-000000000000'::uuid) AS plan_price_id,
    COALESCE(price.currency, '')::text AS currency,
    COALESCE(price.amount_units, 0)::bigint AS amount_units,
    (price.id IS NOT NULL)::boolean AS is_available
FROM team_subscriptions AS subscription
JOIN team_wallets AS wallet ON wallet.team_id = subscription.team_id
CROSS JOIN plans AS plan
LEFT JOIN LATERAL (
    SELECT plan_price.id, plan_price.plan_code, plan_price.billing_market, plan_price.currency, plan_price.amount_units, plan_price.billing_interval, plan_price.effective_from, plan_price.effective_until, plan_price.created_at
    FROM plan_prices AS plan_price
    WHERE plan_price.plan_code = plan.code
      AND plan_price.billing_market = wallet.billing_market
      AND plan_price.billing_interval = 'monthly'
      AND plan_price.effective_from <= subscription.current_period_end
      AND (
          plan_price.effective_until IS NULL
          OR plan_price.effective_until > subscription.current_period_end
      )
    ORDER BY plan_price.effective_from DESC
    LIMIT 1
) AS price ON true
WHERE subscription.team_id = $1
  AND plan.is_enabled = true
ORDER BY CASE plan.code
    WHEN 'growth' THEN 1
    WHEN 'scale' THEN 2
    WHEN 'enterprise' THEN 3
    ELSE 4
END, plan.code
`

type ListPlansForTeamParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

type ListPlansForTeamRow struct {
	Code             string             `db:"code" json:"code"`
	Name             string             `db:"name" json:"name"`
	CurrentPlanCode  string             `db:"current_plan_code" json:"current_plan_code"`
	PendingPlanCode  *string            `db:"pending_plan_code" json:"pending_plan_code"`
	CurrentPeriodEnd pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	PlanPriceID      uuid.UUID          `db:"plan_price_id" json:"plan_price_id"`
	Currency         string             `db:"currency" json:"currency"`
	AmountUnits      int64              `db:"amount_units" json:"amount_units"`
	IsAvailable      bool               `db:"is_available" json:"is_available"`
}

func (q *Queries) ListPlansForTeam(ctx context.Context, arg ListPlansForTeamParams) ([]ListPlansForTeamRow, error) {
	rows, err := q.db.Query(ctx, listPlansForTeam, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansForTeamRow{}
	for rows.Next() {
		var i ListPlansForTeamRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.CurrentPlanCode,
			&i.PendingPlanCode,
			&i.CurrentPeriodEnd,
			&i.PlanPriceID,
			&i.Currency,
			&i.AmountUnits,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
