// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (
    team_id,
    name
) VALUES (
    $1,
    $2
)
RETURNING id, team_id, name, created_at
`

type CreateSegmentParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, createSegment, arg.TeamID, arg.Name)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSegment = `-- name: DeleteSegment :one
DELETE FROM segments
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, name, created_at
`

type DeleteSegmentParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSegment(ctx context.Context, arg DeleteSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, deleteSegment, arg.ID, arg.TeamID)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSegment = `-- name: GetSegment :one
SELECT id, team_id, name, created_at
FROM segments
WHERE id = $1
  AND team_id = $2
`

type GetSegmentParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSegment(ctx context.Context, arg GetSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegment, arg.ID, arg.TeamID)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listSegmentContacts = `-- name: ListSegmentContacts :many
SELECT
    contact.id,
    contact.team_id,
    contact.email,
    contact.first_name,
    contact.last_name,
    contact.unsubscribed,
    contact.created_at,
    contact.updated_at
FROM contact_segments AS membership
JOIN contacts AS contact
  ON contact.id = membership.contact_id
 AND contact.team_id = membership.team_id
WHERE membership.team_id = $1
  AND membership.segment_id = $2
ORDER BY contact.created_at DESC, contact.id DESC
LIMIT $4
OFFSET $3
`

type ListSegmentContactsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	SegmentID  uuid.UUID `db:"segment_id" json:"segment_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

type ListSegmentContactsRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TeamID       uuid.UUID          `db:"team_id" json:"team_id"`
	Email        string             `db:"email" json:"email"`
	FirstName    *string            `db:"first_name" json:"first_name"`
	LastName     *string            `db:"last_name" json:"last_name"`
	Unsubscribed bool               `db:"unsubscribed" json:"unsubscribed"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSegmentContacts(ctx context.Context, arg ListSegmentContactsParams) ([]ListSegmentContactsRow, error) {
	rows, err := q.db.Query(ctx, listSegmentContacts,
		arg.TeamID,
		arg.SegmentID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentContactsRow{}
	for rows.Next() {
		var i ListSegmentContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Unsubscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegments = `-- name: ListSegments :many
SELECT id, team_id, name, created_at
FROM segments
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListSegmentsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSegments(ctx context.Context, arg ListSegmentsParams) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listSegments, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
