// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    token_hash,
    user_agent,
    ip_address,
    expires_at,
    credential_version,
    authentication_method,
    assurance_level,
    authenticated_at,
    mfa_completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, last_seen_at, credential_version, authentication_method, assurance_level, authenticated_at, mfa_completed_at
`

type CreateSessionParams struct {
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash            string             `db:"token_hash" json:"token_hash"`
	UserAgent            *string            `db:"user_agent" json:"user_agent"`
	IpAddress            *string            `db:"ip_address" json:"ip_address"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CredentialVersion    int64              `db:"credential_version" json:"credential_version"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	AssuranceLevel       string             `db:"assurance_level" json:"assurance_level"`
	AuthenticatedAt      pgtype.Timestamptz `db:"authenticated_at" json:"authenticated_at"`
	MfaCompletedAt       pgtype.Timestamptz `db:"mfa_completed_at" json:"mfa_completed_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.CredentialVersion,
		arg.AuthenticationMethod,
		arg.AssuranceLevel,
		arg.AuthenticatedAt,
		arg.MfaCompletedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CredentialVersion,
		&i.AuthenticationMethod,
		&i.AssuranceLevel,
		&i.AuthenticatedAt,
		&i.MfaCompletedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, last_seen_at, credential_version, authentication_method, assurance_level, authenticated_at, mfa_completed_at
FROM sessions
WHERE id = $1
`

type GetSessionByIDParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CredentialVersion,
		&i.AuthenticationMethod,
		&i.AssuranceLevel,
		&i.AuthenticatedAt,
		&i.MfaCompletedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, last_seen_at, credential_version, authentication_method, assurance_level, authenticated_at, mfa_completed_at
FROM sessions
WHERE token_hash = $1
`

type GetSessionByTokenHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.CredentialVersion,
		&i.AuthenticationMethod,
		&i.AssuranceLevel,
		&i.AuthenticatedAt,
		&i.MfaCompletedAt,
	)
	return i, err
}

const hasKnownSessionFingerprint = `-- name: HasKnownSessionFingerprint :one
SELECT EXISTS (
    SELECT 1
    FROM sessions
    WHERE user_id = $1
      AND user_agent IS NOT DISTINCT FROM $2
      AND ip_address IS NOT DISTINCT FROM $3
)
`

type HasKnownSessionFingerprintParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	UserAgent *string   `db:"user_agent" json:"user_agent"`
	IpAddress *string   `db:"ip_address" json:"ip_address"`
}

func (q *Queries) HasKnownSessionFingerprint(ctx context.Context, arg HasKnownSessionFingerprintParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasKnownSessionFingerprint, arg.UserID, arg.UserAgent, arg.IpAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, last_seen_at, credential_version, authentication_method, assurance_level, authenticated_at, mfa_completed_at
FROM sessions
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

type ListSessionsByUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListSessionsByUserID(ctx context.Context, arg ListSessionsByUserIDParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.CredentialVersion,
			&i.AuthenticationMethod,
			&i.AssuranceLevel,
			&i.AuthenticatedAt,
			&i.MfaCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND id <> $2
  AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
	CurrentSessionID string    `db:"current_session_id" json:"current_session_id"`
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.UserID, arg.CurrentSessionID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     string    `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1
  AND last_seen_at < now() - interval '5 minutes'
`

type TouchSessionParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID)
	return err
}
