// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_campaigns.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateSMSCampaign = `-- name: ActivateSMSCampaign :one
UPDATE sms_campaigns AS campaign
SET status = CASE WHEN $1::timestamptz IS NULL THEN 'queued' ELSE 'scheduled' END,
    scheduled_at = $1,
    queued_at = CASE WHEN $1::timestamptz IS NULL THEN now() ELSE NULL END,
    revision = revision + 1,
    updated_at = now()
WHERE campaign.id = $2 AND campaign.team_id = $3 AND campaign.status = 'draft'
  AND EXISTS (
      SELECT 1 FROM sender_ids AS sender
      WHERE sender.id = campaign.sender_id AND sender.team_id = campaign.team_id
        AND sender.status = 'approved' AND sender.provider_whitelisted
  )
RETURNING campaign.id, campaign.team_id, campaign.name, campaign.status, campaign.segment_id, campaign.sender_id, campaign.body, campaign.scheduled_at, campaign.queued_at, campaign.canceled_at, campaign.materialized_at, campaign.sent_at, campaign.audience_count, campaign.eligible_count, campaign.excluded_count, campaign.failed_count, campaign.estimated_segments, campaign.estimated_cost_units, campaign.estimated_billable_cost_units, campaign.preflight_allowance_segments, campaign.actual_segments, campaign.actual_charge_units, campaign.currency, campaign.preflight_balance_units, campaign.preflight_at, campaign.rate_limit_per_second, campaign.daily_send_limit, campaign.revision, campaign.created_at, campaign.updated_at
`

type ActivateSMSCampaignParams struct {
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) ActivateSMSCampaign(ctx context.Context, arg ActivateSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, activateSMSCampaign, arg.ScheduledAt, arg.ID, arg.TeamID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelSMSCampaign = `-- name: CancelSMSCampaign :one
UPDATE sms_campaigns
SET status = 'canceled', canceled_at = now(), revision = revision + 1, updated_at = now()
WHERE id = $1 AND team_id = $2 AND status IN ('scheduled', 'queued')
RETURNING id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at
`

type CancelSMSCampaignParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CancelSMSCampaign(ctx context.Context, arg CancelSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, cancelSMSCampaign, arg.ID, arg.TeamID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSMSCampaign = `-- name: CreateSMSCampaign :one
INSERT INTO sms_campaigns (team_id, name, segment_id, sender_id, body, rate_limit_per_second, daily_send_limit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at
`

type CreateSMSCampaignParams struct {
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
	Name               string    `db:"name" json:"name"`
	SegmentID          uuid.UUID `db:"segment_id" json:"segment_id"`
	SenderID           uuid.UUID `db:"sender_id" json:"sender_id"`
	Body               string    `db:"body" json:"body"`
	RateLimitPerSecond int32     `db:"rate_limit_per_second" json:"rate_limit_per_second"`
	DailySendLimit     *int32    `db:"daily_send_limit" json:"daily_send_limit"`
}

func (q *Queries) CreateSMSCampaign(ctx context.Context, arg CreateSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, createSMSCampaign,
		arg.TeamID,
		arg.Name,
		arg.SegmentID,
		arg.SenderID,
		arg.Body,
		arg.RateLimitPerSecond,
		arg.DailySendLimit,
	)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSMSCampaign = `-- name: DeleteSMSCampaign :one
DELETE FROM sms_campaigns
WHERE id = $1 AND team_id = $2 AND status IN ('draft', 'canceled')
RETURNING id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at
`

type DeleteSMSCampaignParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSMSCampaign(ctx context.Context, arg DeleteSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, deleteSMSCampaign, arg.ID, arg.TeamID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const duplicateSMSCampaign = `-- name: DuplicateSMSCampaign :one
INSERT INTO sms_campaigns (team_id, name, segment_id, sender_id, body, rate_limit_per_second, daily_send_limit)
SELECT team_id, $1, segment_id, sender_id, body, rate_limit_per_second, daily_send_limit
FROM sms_campaigns AS source
WHERE source.id = $2 AND source.team_id = $3
RETURNING id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at
`

type DuplicateSMSCampaignParams struct {
	Name     string    `db:"name" json:"name"`
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DuplicateSMSCampaign(ctx context.Context, arg DuplicateSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, duplicateSMSCampaign, arg.Name, arg.SourceID, arg.TeamID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMSCampaign = `-- name: GetSMSCampaign :one
SELECT id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at FROM sms_campaigns WHERE id = $1 AND team_id = $2
`

type GetSMSCampaignParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSMSCampaign(ctx context.Context, arg GetSMSCampaignParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, getSMSCampaign, arg.ID, arg.TeamID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isApprovedSMSCampaignSender = `-- name: IsApprovedSMSCampaignSender :one
SELECT EXISTS (
    SELECT 1 FROM sms_campaigns AS campaign
    JOIN sender_ids AS sender ON sender.id = campaign.sender_id AND sender.team_id = campaign.team_id
    WHERE campaign.id = $1 AND campaign.team_id = $2
      AND sender.status = 'approved' AND sender.provider_whitelisted
)
`

type IsApprovedSMSCampaignSenderParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) IsApprovedSMSCampaignSender(ctx context.Context, arg IsApprovedSMSCampaignSenderParams) (bool, error) {
	row := q.db.QueryRow(ctx, isApprovedSMSCampaignSender, arg.ID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSMSCampaignRecipients = `-- name: ListSMSCampaignRecipients :many
SELECT id, team_id, campaign_id, contact_id, phone, phone_country, contact_snapshot, status, exclusion_reason, sms_message_id, rendered_body, attempt_count, next_attempt_at, failure_code, failure_message, encoding, estimated_segments, estimated_unit_cost_units, estimated_cost_units, actual_segments, actual_charge_units, created_at, queued_at FROM sms_campaign_recipients
WHERE campaign_id = $1 AND team_id = $2
ORDER BY created_at, id
LIMIT $4 OFFSET $3
`

type ListSMSCampaignRecipientsParams struct {
	CampaignID uuid.UUID `db:"campaign_id" json:"campaign_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSMSCampaignRecipients(ctx context.Context, arg ListSMSCampaignRecipientsParams) ([]SmsCampaignRecipient, error) {
	rows, err := q.db.Query(ctx, listSMSCampaignRecipients,
		arg.CampaignID,
		arg.TeamID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsCampaignRecipient{}
	for rows.Next() {
		var i SmsCampaignRecipient
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.CampaignID,
			&i.ContactID,
			&i.Phone,
			&i.PhoneCountry,
			&i.ContactSnapshot,
			&i.Status,
			&i.ExclusionReason,
			&i.SmsMessageID,
			&i.RenderedBody,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.FailureCode,
			&i.FailureMessage,
			&i.Encoding,
			&i.EstimatedSegments,
			&i.EstimatedUnitCostUnits,
			&i.EstimatedCostUnits,
			&i.ActualSegments,
			&i.ActualChargeUnits,
			&i.CreatedAt,
			&i.QueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSCampaigns = `-- name: ListSMSCampaigns :many
SELECT id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at FROM sms_campaigns
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListSMSCampaignsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSMSCampaigns(ctx context.Context, arg ListSMSCampaignsParams) ([]SmsCampaign, error) {
	rows, err := q.db.Query(ctx, listSMSCampaigns, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsCampaign{}
	for rows.Next() {
		var i SmsCampaign
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Status,
			&i.SegmentID,
			&i.SenderID,
			&i.Body,
			&i.ScheduledAt,
			&i.QueuedAt,
			&i.CanceledAt,
			&i.MaterializedAt,
			&i.SentAt,
			&i.AudienceCount,
			&i.EligibleCount,
			&i.ExcludedCount,
			&i.FailedCount,
			&i.EstimatedSegments,
			&i.EstimatedCostUnits,
			&i.EstimatedBillableCostUnits,
			&i.PreflightAllowanceSegments,
			&i.ActualSegments,
			&i.ActualChargeUnits,
			&i.Currency,
			&i.PreflightBalanceUnits,
			&i.PreflightAt,
			&i.RateLimitPerSecond,
			&i.DailySendLimit,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSMSCampaignDraft = `-- name: UpdateSMSCampaignDraft :one
UPDATE sms_campaigns
SET name = $1, segment_id = $2, sender_id = $3,
    body = $4, rate_limit_per_second = $5,
    daily_send_limit = $6, revision = revision + 1, updated_at = now()
WHERE id = $7 AND team_id = $8
  AND status = 'draft' AND revision = $9
RETURNING id, team_id, name, status, segment_id, sender_id, body, scheduled_at, queued_at, canceled_at, materialized_at, sent_at, audience_count, eligible_count, excluded_count, failed_count, estimated_segments, estimated_cost_units, estimated_billable_cost_units, preflight_allowance_segments, actual_segments, actual_charge_units, currency, preflight_balance_units, preflight_at, rate_limit_per_second, daily_send_limit, revision, created_at, updated_at
`

type UpdateSMSCampaignDraftParams struct {
	Name               string    `db:"name" json:"name"`
	SegmentID          uuid.UUID `db:"segment_id" json:"segment_id"`
	SenderID           uuid.UUID `db:"sender_id" json:"sender_id"`
	Body               string    `db:"body" json:"body"`
	RateLimitPerSecond int32     `db:"rate_limit_per_second" json:"rate_limit_per_second"`
	DailySendLimit     *int32    `db:"daily_send_limit" json:"daily_send_limit"`
	ID                 uuid.UUID `db:"id" json:"id"`
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
	Revision           int64     `db:"revision" json:"revision"`
}

func (q *Queries) UpdateSMSCampaignDraft(ctx context.Context, arg UpdateSMSCampaignDraftParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, updateSMSCampaignDraft,
		arg.Name,
		arg.SegmentID,
		arg.SenderID,
		arg.Body,
		arg.RateLimitPerSecond,
		arg.DailySendLimit,
		arg.ID,
		arg.TeamID,
		arg.Revision,
	)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
