// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_campaign_compliance.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getSMSCampaignAnalytics = `-- name: GetSMSCampaignAnalytics :one
SELECT
    campaign.id AS campaign_id,
    campaign.audience_count,
    campaign.eligible_count,
    campaign.excluded_count,
    count(recipient.id) FILTER (WHERE recipient.status = 'queued')::bigint AS queued_count,
    count(recipient.id) FILTER (WHERE recipient.status = 'failed')::bigint AS failed_count,
    count(message.id) FILTER (WHERE message.status IN ('submitted', 'sent', 'delivered'))::bigint AS sent_count,
    count(message.id) FILTER (WHERE message.status = 'delivered')::bigint AS delivered_count,
    count(message.id) FILTER (WHERE message.status IN ('undelivered', 'rejected', 'failed', 'expired'))::bigint AS delivery_failed_count,
    campaign.estimated_segments,
    campaign.estimated_cost_units,
    campaign.estimated_billable_cost_units,
    campaign.actual_segments,
    campaign.actual_charge_units,
    campaign.currency
FROM sms_campaigns AS campaign
LEFT JOIN sms_campaign_recipients AS recipient
  ON recipient.campaign_id = campaign.id AND recipient.team_id = campaign.team_id
LEFT JOIN sms_messages AS message
  ON message.id = recipient.sms_message_id AND message.team_id = recipient.team_id
WHERE campaign.id = $1 AND campaign.team_id = $2
GROUP BY campaign.id
`

type GetSMSCampaignAnalyticsParams struct {
	CampaignID uuid.UUID `db:"campaign_id" json:"campaign_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

type GetSMSCampaignAnalyticsRow struct {
	CampaignID                 uuid.UUID `db:"campaign_id" json:"campaign_id"`
	AudienceCount              int64     `db:"audience_count" json:"audience_count"`
	EligibleCount              int64     `db:"eligible_count" json:"eligible_count"`
	ExcludedCount              int64     `db:"excluded_count" json:"excluded_count"`
	QueuedCount                int64     `db:"queued_count" json:"queued_count"`
	FailedCount                int64     `db:"failed_count" json:"failed_count"`
	SentCount                  int64     `db:"sent_count" json:"sent_count"`
	DeliveredCount             int64     `db:"delivered_count" json:"delivered_count"`
	DeliveryFailedCount        int64     `db:"delivery_failed_count" json:"delivery_failed_count"`
	EstimatedSegments          int64     `db:"estimated_segments" json:"estimated_segments"`
	EstimatedCostUnits         int64     `db:"estimated_cost_units" json:"estimated_cost_units"`
	EstimatedBillableCostUnits int64     `db:"estimated_billable_cost_units" json:"estimated_billable_cost_units"`
	ActualSegments             int64     `db:"actual_segments" json:"actual_segments"`
	ActualChargeUnits          int64     `db:"actual_charge_units" json:"actual_charge_units"`
	Currency                   *string   `db:"currency" json:"currency"`
}

func (q *Queries) GetSMSCampaignAnalytics(ctx context.Context, arg GetSMSCampaignAnalyticsParams) (GetSMSCampaignAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getSMSCampaignAnalytics, arg.CampaignID, arg.TeamID)
	var i GetSMSCampaignAnalyticsRow
	err := row.Scan(
		&i.CampaignID,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.QueuedCount,
		&i.FailedCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.DeliveryFailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
	)
	return i, err
}

const getSMSCampaignExclusionSummary = `-- name: GetSMSCampaignExclusionSummary :many
SELECT exclusion_reason, count(*)::bigint AS total
FROM sms_campaign_recipients
WHERE campaign_id = $1 AND team_id = $2
  AND status = 'excluded'
GROUP BY exclusion_reason
ORDER BY exclusion_reason
`

type GetSMSCampaignExclusionSummaryParams struct {
	CampaignID uuid.UUID `db:"campaign_id" json:"campaign_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

type GetSMSCampaignExclusionSummaryRow struct {
	ExclusionReason *string `db:"exclusion_reason" json:"exclusion_reason"`
	Total           int64   `db:"total" json:"total"`
}

func (q *Queries) GetSMSCampaignExclusionSummary(ctx context.Context, arg GetSMSCampaignExclusionSummaryParams) ([]GetSMSCampaignExclusionSummaryRow, error) {
	rows, err := q.db.Query(ctx, getSMSCampaignExclusionSummary, arg.CampaignID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSMSCampaignExclusionSummaryRow{}
	for rows.Next() {
		var i GetSMSCampaignExclusionSummaryRow
		if err := rows.Scan(&i.ExclusionReason, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSMSOptOut = `-- name: RecordSMSOptOut :one
WITH contact_record AS (
    SELECT id FROM contacts
    WHERE team_id = $1 AND normalized_phone = $2
    FOR UPDATE
), updated_contact AS (
    UPDATE contacts
    SET sms_consent_status = 'opted_out',
        sms_consent_updated_at = now(),
        sms_consent_source = $3,
        updated_at = now()
    WHERE id = (SELECT id FROM contact_record) AND team_id = $1
    RETURNING id
), suppression AS (
    INSERT INTO channel_suppressions (
        team_id, channel, address, normalized_address, reason, origin, source_id
    ) VALUES (
        $1, 'sms', $2, $2,
        'user_opt_out', $3, $4
    )
    ON CONFLICT (team_id, channel, normalized_address)
    DO UPDATE SET reason = 'user_opt_out', origin = EXCLUDED.origin, source_id = EXCLUDED.source_id
    RETURNING id
)
INSERT INTO sms_consent_events (team_id, contact_id, phone, action, source, source_id)
VALUES (
    $1, (SELECT id FROM contact_record), $2,
    'opted_out', $3, $4
)
ON CONFLICT (team_id, source, source_id) WHERE source_id IS NOT NULL
DO UPDATE SET source_id = EXCLUDED.source_id
RETURNING id, team_id, contact_id, phone, action, source, source_id, recorded_at
`

type RecordSMSOptOutParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Phone    string    `db:"phone" json:"phone"`
	Source   string    `db:"source" json:"source"`
	SourceID *string   `db:"source_id" json:"source_id"`
}

func (q *Queries) RecordSMSOptOut(ctx context.Context, arg RecordSMSOptOutParams) (SmsConsentEvent, error) {
	row := q.db.QueryRow(ctx, recordSMSOptOut,
		arg.TeamID,
		arg.Phone,
		arg.Source,
		arg.SourceID,
	)
	var i SmsConsentEvent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ContactID,
		&i.Phone,
		&i.Action,
		&i.Source,
		&i.SourceID,
		&i.RecordedAt,
	)
	return i, err
}
