// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_campaign_costs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextSMSCampaignRecipientForEstimate = `-- name: ClaimNextSMSCampaignRecipientForEstimate :one
SELECT recipient.id, recipient.team_id, recipient.campaign_id, recipient.contact_id, recipient.phone, recipient.phone_country, recipient.contact_snapshot, recipient.status, recipient.exclusion_reason, recipient.sms_message_id, recipient.rendered_body, recipient.attempt_count, recipient.next_attempt_at, recipient.failure_code, recipient.failure_message, recipient.encoding, recipient.estimated_segments, recipient.estimated_unit_cost_units, recipient.estimated_cost_units, recipient.actual_segments, recipient.actual_charge_units, recipient.created_at, recipient.queued_at, campaign.body AS campaign_body,
       campaign.sender_id, sender.name AS sender_name
FROM sms_campaign_recipients AS recipient
JOIN sms_campaigns AS campaign
  ON campaign.id = recipient.campaign_id AND campaign.team_id = recipient.team_id
JOIN sender_ids AS sender
  ON sender.id = campaign.sender_id AND sender.team_id = campaign.team_id
WHERE recipient.status = 'pending' AND recipient.estimated_segments IS NULL
  AND campaign.status = 'estimating'
ORDER BY recipient.created_at, recipient.id
FOR UPDATE OF recipient SKIP LOCKED
LIMIT 1
`

type ClaimNextSMSCampaignRecipientForEstimateRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TeamID                 uuid.UUID          `db:"team_id" json:"team_id"`
	CampaignID             uuid.UUID          `db:"campaign_id" json:"campaign_id"`
	ContactID              *uuid.UUID         `db:"contact_id" json:"contact_id"`
	Phone                  *string            `db:"phone" json:"phone"`
	PhoneCountry           *string            `db:"phone_country" json:"phone_country"`
	ContactSnapshot        []byte             `db:"contact_snapshot" json:"contact_snapshot"`
	Status                 string             `db:"status" json:"status"`
	ExclusionReason        *string            `db:"exclusion_reason" json:"exclusion_reason"`
	SmsMessageID           *uuid.UUID         `db:"sms_message_id" json:"sms_message_id"`
	RenderedBody           *string            `db:"rendered_body" json:"rendered_body"`
	AttemptCount           int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt          pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	FailureCode            *string            `db:"failure_code" json:"failure_code"`
	FailureMessage         *string            `db:"failure_message" json:"failure_message"`
	Encoding               *string            `db:"encoding" json:"encoding"`
	EstimatedSegments      *int32             `db:"estimated_segments" json:"estimated_segments"`
	EstimatedUnitCostUnits *int64             `db:"estimated_unit_cost_units" json:"estimated_unit_cost_units"`
	EstimatedCostUnits     *int64             `db:"estimated_cost_units" json:"estimated_cost_units"`
	ActualSegments         *int32             `db:"actual_segments" json:"actual_segments"`
	ActualChargeUnits      *int64             `db:"actual_charge_units" json:"actual_charge_units"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	QueuedAt               pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	CampaignBody           string             `db:"campaign_body" json:"campaign_body"`
	SenderID               uuid.UUID          `db:"sender_id" json:"sender_id"`
	SenderName             string             `db:"sender_name" json:"sender_name"`
}

func (q *Queries) ClaimNextSMSCampaignRecipientForEstimate(ctx context.Context) (ClaimNextSMSCampaignRecipientForEstimateRow, error) {
	row := q.db.QueryRow(ctx, claimNextSMSCampaignRecipientForEstimate)
	var i ClaimNextSMSCampaignRecipientForEstimateRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CampaignID,
		&i.ContactID,
		&i.Phone,
		&i.PhoneCountry,
		&i.ContactSnapshot,
		&i.Status,
		&i.ExclusionReason,
		&i.SmsMessageID,
		&i.RenderedBody,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.FailureCode,
		&i.FailureMessage,
		&i.Encoding,
		&i.EstimatedSegments,
		&i.EstimatedUnitCostUnits,
		&i.EstimatedCostUnits,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.CampaignBody,
		&i.SenderID,
		&i.SenderName,
	)
	return i, err
}

const estimateSMSCampaignRecipientCost = `-- name: EstimateSMSCampaignRecipientCost :one
SELECT
    CASE
        WHEN rate.currency = wallet.currency THEN rate.cost_units::bigint
        ELSE round(rate.cost_units::numeric * fx.rate)::bigint
    END AS unit_cost_units,
    (
        CASE
            WHEN rate.currency = wallet.currency THEN rate.cost_units::bigint
            ELSE round(rate.cost_units::numeric * fx.rate)::bigint
        END * $1::bigint
    )::bigint AS cost_units,
    wallet.currency::text AS currency
FROM team_wallets AS wallet
JOIN teams AS team ON team.id = wallet.team_id AND team.status = 'active'
JOIN team_subscriptions AS subscription
  ON subscription.team_id = wallet.team_id
 AND subscription.status = 'active'
 AND subscription.current_period_start <= now()
 AND subscription.current_period_end > now()
JOIN sms_rates AS rate
  ON rate.tier = subscription.plan_code
 AND rate.destination_country = $2::char(2)
 AND rate.route_type = CASE WHEN team.market_code = $2::char(2) THEN 'local' ELSE 'intl' END
 AND rate.effective_from <= now()
 AND (rate.effective_until IS NULL OR rate.effective_until > now())
LEFT JOIN fx_rates AS fx
  ON rate.currency <> wallet.currency
 AND fx.base_currency = rate.currency
 AND fx.quote_currency = wallet.currency
 AND fx.effective_from <= now()
 AND (fx.effective_until IS NULL OR fx.effective_until > now())
WHERE wallet.team_id = $3
  AND (rate.currency = wallet.currency OR fx.id IS NOT NULL)
ORDER BY rate.effective_from DESC, fx.effective_from DESC NULLS LAST
LIMIT 1
`

type EstimateSMSCampaignRecipientCostParams struct {
	Segments           int64     `db:"segments" json:"segments"`
	DestinationCountry string    `db:"destination_country" json:"destination_country"`
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
}

type EstimateSMSCampaignRecipientCostRow struct {
	UnitCostUnits int64  `db:"unit_cost_units" json:"unit_cost_units"`
	CostUnits     int64  `db:"cost_units" json:"cost_units"`
	Currency      string `db:"currency" json:"currency"`
}

func (q *Queries) EstimateSMSCampaignRecipientCost(ctx context.Context, arg EstimateSMSCampaignRecipientCostParams) (EstimateSMSCampaignRecipientCostRow, error) {
	row := q.db.QueryRow(ctx, estimateSMSCampaignRecipientCost, arg.Segments, arg.DestinationCountry, arg.TeamID)
	var i EstimateSMSCampaignRecipientCostRow
	err := row.Scan(&i.UnitCostUnits, &i.CostUnits, &i.Currency)
	return i, err
}

const failSMSCampaignRecipientEstimate = `-- name: FailSMSCampaignRecipientEstimate :exec
UPDATE sms_campaign_recipients
SET status = 'failed', failure_code = $1,
    failure_message = $2
WHERE id = $3 AND team_id = $4
  AND status = 'pending' AND estimated_segments IS NULL
`

type FailSMSCampaignRecipientEstimateParams struct {
	FailureCode    *string   `db:"failure_code" json:"failure_code"`
	FailureMessage *string   `db:"failure_message" json:"failure_message"`
	ID             uuid.UUID `db:"id" json:"id"`
	TeamID         uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) FailSMSCampaignRecipientEstimate(ctx context.Context, arg FailSMSCampaignRecipientEstimateParams) error {
	_, err := q.db.Exec(ctx, failSMSCampaignRecipientEstimate,
		arg.FailureCode,
		arg.FailureMessage,
		arg.ID,
		arg.TeamID,
	)
	return err
}

const finalizeSMSCampaignCostPreflight = `-- name: FinalizeSMSCampaignCostPreflight :one
WITH estimate AS (
    SELECT
        COALESCE(sum(estimated_segments), 0)::bigint AS segments,
        COALESCE(sum(estimated_cost_units), 0)::bigint AS cost_units,
        COALESCE(min(estimated_unit_cost_units), 0)::bigint AS minimum_unit_cost_units,
        count(*) FILTER (WHERE status = 'failed')::bigint AS failures
    FROM sms_campaign_recipients
    WHERE campaign_id = $1 AND team_id = $2
), wallet AS (
    SELECT team_wallet.balance_units, team_wallet.currency::text AS currency
    FROM (VALUES (1)) AS singleton(value)
    LEFT JOIN team_wallets AS team_wallet ON team_wallet.team_id = $2
), allowance AS (
    SELECT COALESCE(max(included_quantity - consumed_quantity), 0)::bigint AS remaining
    FROM usage_allowances
    WHERE team_id = $2 AND product = 'sms' AND meter = 'sms_segment'
      AND period_start <= now() AND period_end > now()
), preflight AS (
    SELECT estimate.segments, estimate.cost_units, estimate.minimum_unit_cost_units, estimate.failures,
        LEAST(estimate.segments, allowance.remaining)::bigint AS allowance_segments,
        GREATEST(
            estimate.cost_units
              - LEAST(estimate.segments, allowance.remaining) * estimate.minimum_unit_cost_units,
            0
        )::bigint AS billable_cost_units
    FROM estimate, allowance
)
UPDATE sms_campaigns AS campaign
SET estimated_segments = preflight.segments,
    estimated_cost_units = preflight.cost_units,
    estimated_billable_cost_units = preflight.billable_cost_units,
    preflight_allowance_segments = preflight.allowance_segments,
    currency = wallet.currency,
    preflight_balance_units = wallet.balance_units,
    preflight_at = now(),
    failed_count = preflight.failures,
    status = CASE
        WHEN preflight.failures > 0 OR wallet.balance_units IS NULL THEN 'failed'
        WHEN wallet.balance_units < preflight.billable_cost_units THEN 'failed'
        ELSE 'sending'
    END,
    updated_at = now()
FROM preflight, wallet
WHERE campaign.id = $1 AND campaign.team_id = $2
  AND campaign.status = 'estimating'
  AND NOT EXISTS (
      SELECT 1 FROM sms_campaign_recipients
      WHERE campaign_id = campaign.id AND status = 'pending'
        AND estimated_segments IS NULL
  )
RETURNING campaign.id, campaign.team_id, campaign.name, campaign.status, campaign.segment_id, campaign.sender_id, campaign.body, campaign.scheduled_at, campaign.queued_at, campaign.canceled_at, campaign.materialized_at, campaign.sent_at, campaign.audience_count, campaign.eligible_count, campaign.excluded_count, campaign.failed_count, campaign.estimated_segments, campaign.estimated_cost_units, campaign.estimated_billable_cost_units, campaign.preflight_allowance_segments, campaign.actual_segments, campaign.actual_charge_units, campaign.currency, campaign.preflight_balance_units, campaign.preflight_at, campaign.rate_limit_per_second, campaign.daily_send_limit, campaign.revision, campaign.created_at, campaign.updated_at
`

type FinalizeSMSCampaignCostPreflightParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) FinalizeSMSCampaignCostPreflight(ctx context.Context, arg FinalizeSMSCampaignCostPreflightParams) (SmsCampaign, error) {
	row := q.db.QueryRow(ctx, finalizeSMSCampaignCostPreflight, arg.ID, arg.TeamID)
	var i SmsCampaign
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.SenderID,
		&i.Body,
		&i.ScheduledAt,
		&i.QueuedAt,
		&i.CanceledAt,
		&i.MaterializedAt,
		&i.SentAt,
		&i.AudienceCount,
		&i.EligibleCount,
		&i.ExcludedCount,
		&i.FailedCount,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.Currency,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.RateLimitPerSecond,
		&i.DailySendLimit,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMSCampaignCostEstimate = `-- name: GetSMSCampaignCostEstimate :one
SELECT
    campaign.id AS campaign_id,
    campaign.currency,
    campaign.estimated_segments,
    campaign.estimated_cost_units,
    campaign.estimated_billable_cost_units,
    campaign.preflight_allowance_segments,
    campaign.actual_segments,
    campaign.actual_charge_units,
    campaign.preflight_balance_units,
    campaign.preflight_at,
    count(recipient.id) FILTER (WHERE recipient.status <> 'excluded')::bigint AS recipients,
    COALESCE(min(recipient.estimated_cost_units), 0)::bigint AS minimum_recipient_cost_units,
    COALESCE(max(recipient.estimated_cost_units), 0)::bigint AS maximum_recipient_cost_units
FROM sms_campaigns AS campaign
LEFT JOIN sms_campaign_recipients AS recipient
  ON recipient.campaign_id = campaign.id AND recipient.team_id = campaign.team_id
WHERE campaign.id = $1 AND campaign.team_id = $2
GROUP BY campaign.id
`

type GetSMSCampaignCostEstimateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

type GetSMSCampaignCostEstimateRow struct {
	CampaignID                 uuid.UUID          `db:"campaign_id" json:"campaign_id"`
	Currency                   *string            `db:"currency" json:"currency"`
	EstimatedSegments          int64              `db:"estimated_segments" json:"estimated_segments"`
	EstimatedCostUnits         int64              `db:"estimated_cost_units" json:"estimated_cost_units"`
	EstimatedBillableCostUnits int64              `db:"estimated_billable_cost_units" json:"estimated_billable_cost_units"`
	PreflightAllowanceSegments int64              `db:"preflight_allowance_segments" json:"preflight_allowance_segments"`
	ActualSegments             int64              `db:"actual_segments" json:"actual_segments"`
	ActualChargeUnits          int64              `db:"actual_charge_units" json:"actual_charge_units"`
	PreflightBalanceUnits      *int64             `db:"preflight_balance_units" json:"preflight_balance_units"`
	PreflightAt                pgtype.Timestamptz `db:"preflight_at" json:"preflight_at"`
	Recipients                 int64              `db:"recipients" json:"recipients"`
	MinimumRecipientCostUnits  int64              `db:"minimum_recipient_cost_units" json:"minimum_recipient_cost_units"`
	MaximumRecipientCostUnits  int64              `db:"maximum_recipient_cost_units" json:"maximum_recipient_cost_units"`
}

func (q *Queries) GetSMSCampaignCostEstimate(ctx context.Context, arg GetSMSCampaignCostEstimateParams) (GetSMSCampaignCostEstimateRow, error) {
	row := q.db.QueryRow(ctx, getSMSCampaignCostEstimate, arg.ID, arg.TeamID)
	var i GetSMSCampaignCostEstimateRow
	err := row.Scan(
		&i.CampaignID,
		&i.Currency,
		&i.EstimatedSegments,
		&i.EstimatedCostUnits,
		&i.EstimatedBillableCostUnits,
		&i.PreflightAllowanceSegments,
		&i.ActualSegments,
		&i.ActualChargeUnits,
		&i.PreflightBalanceUnits,
		&i.PreflightAt,
		&i.Recipients,
		&i.MinimumRecipientCostUnits,
		&i.MaximumRecipientCostUnits,
	)
	return i, err
}

const setSMSCampaignRecipientEstimate = `-- name: SetSMSCampaignRecipientEstimate :exec
UPDATE sms_campaign_recipients
SET rendered_body = $1,
    encoding = $2,
    estimated_segments = $3,
    estimated_unit_cost_units = $4,
    estimated_cost_units = $5
WHERE id = $6 AND team_id = $7
  AND status = 'pending' AND estimated_segments IS NULL
`

type SetSMSCampaignRecipientEstimateParams struct {
	RenderedBody           *string   `db:"rendered_body" json:"rendered_body"`
	Encoding               *string   `db:"encoding" json:"encoding"`
	EstimatedSegments      *int32    `db:"estimated_segments" json:"estimated_segments"`
	EstimatedUnitCostUnits *int64    `db:"estimated_unit_cost_units" json:"estimated_unit_cost_units"`
	EstimatedCostUnits     *int64    `db:"estimated_cost_units" json:"estimated_cost_units"`
	ID                     uuid.UUID `db:"id" json:"id"`
	TeamID                 uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SetSMSCampaignRecipientEstimate(ctx context.Context, arg SetSMSCampaignRecipientEstimateParams) error {
	_, err := q.db.Exec(ctx, setSMSCampaignRecipientEstimate,
		arg.RenderedBody,
		arg.Encoding,
		arg.EstimatedSegments,
		arg.EstimatedUnitCostUnits,
		arg.EstimatedCostUnits,
		arg.ID,
		arg.TeamID,
	)
	return err
}
