// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppressions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createChannelSuppression = `-- name: CreateChannelSuppression :one
INSERT INTO channel_suppressions (
    team_id, channel, address, normalized_address, reason, origin, source_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type CreateChannelSuppressionParams struct {
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
	Channel           string    `db:"channel" json:"channel"`
	Address           string    `db:"address" json:"address"`
	NormalizedAddress string    `db:"normalized_address" json:"normalized_address"`
	Reason            string    `db:"reason" json:"reason"`
	Origin            string    `db:"origin" json:"origin"`
	SourceID          *string   `db:"source_id" json:"source_id"`
}

func (q *Queries) CreateChannelSuppression(ctx context.Context, arg CreateChannelSuppressionParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, createChannelSuppression,
		arg.TeamID,
		arg.Channel,
		arg.Address,
		arg.NormalizedAddress,
		arg.Reason,
		arg.Origin,
		arg.SourceID,
	)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createSuppression = `-- name: CreateSuppression :one
INSERT INTO channel_suppressions (
    team_id, channel, address, normalized_address, reason, origin, source_id
) VALUES (
    $1,
    'email',
    $2,
    lower(btrim($2)),
    $3,
    CASE WHEN $3::text = 'manual' THEN 'manual' ELSE 'provider' END,
    $4
)
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type CreateSuppressionParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Email    string    `db:"email" json:"email"`
	Origin   string    `db:"origin" json:"origin"`
	SourceID *string   `db:"source_id" json:"source_id"`
}

func (q *Queries) CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, createSuppression,
		arg.TeamID,
		arg.Email,
		arg.Origin,
		arg.SourceID,
	)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createSuppressions = `-- name: CreateSuppressions :many
INSERT INTO channel_suppressions (
    team_id, channel, address, normalized_address, reason, origin
)
SELECT $1,
       'email',
       batch_email.email,
       lower(btrim(batch_email.email)),
       'manual',
       'manual'
FROM unnest($2::text[]) WITH ORDINALITY AS batch_email(email, position)
ORDER BY batch_email.position
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type CreateSuppressionsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Emails []string  `db:"emails" json:"emails"`
}

func (q *Queries) CreateSuppressions(ctx context.Context, arg CreateSuppressionsParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, createSuppressions, arg.TeamID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChannelSuppression = `-- name: DeleteChannelSuppression :one
DELETE FROM channel_suppressions
WHERE team_id = $1
  AND channel = $2
  AND normalized_address = $3
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type DeleteChannelSuppressionParams struct {
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
	Channel           string    `db:"channel" json:"channel"`
	NormalizedAddress string    `db:"normalized_address" json:"normalized_address"`
}

func (q *Queries) DeleteChannelSuppression(ctx context.Context, arg DeleteChannelSuppressionParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, deleteChannelSuppression, arg.TeamID, arg.Channel, arg.NormalizedAddress)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionByEmail = `-- name: DeleteSuppressionByEmail :one
DELETE FROM channel_suppressions
WHERE team_id = $1
  AND channel = 'email'
  AND normalized_address = lower(btrim($2))
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type DeleteSuppressionByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) DeleteSuppressionByEmail(ctx context.Context, arg DeleteSuppressionByEmailParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, deleteSuppressionByEmail, arg.TeamID, arg.Email)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionByID = `-- name: DeleteSuppressionByID :one
DELETE FROM channel_suppressions
WHERE id = $1
  AND team_id = $2
  AND channel = 'email'
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type DeleteSuppressionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSuppressionByID(ctx context.Context, arg DeleteSuppressionByIDParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, deleteSuppressionByID, arg.ID, arg.TeamID)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSuppressionsByEmails = `-- name: DeleteSuppressionsByEmails :many
DELETE FROM channel_suppressions
WHERE team_id = $1
  AND channel = 'email'
  AND normalized_address = ANY($2::text[])
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type DeleteSuppressionsByEmailsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Emails []string  `db:"emails" json:"emails"`
}

func (q *Queries) DeleteSuppressionsByEmails(ctx context.Context, arg DeleteSuppressionsByEmailsParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, deleteSuppressionsByEmails, arg.TeamID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSuppressionsByIDs = `-- name: DeleteSuppressionsByIDs :many
DELETE FROM channel_suppressions
WHERE team_id = $1
  AND channel = 'email'
  AND id = ANY($2::uuid[])
RETURNING id, team_id, channel, address, normalized_address, reason, origin, source_id, created_at
`

type DeleteSuppressionsByIDsParams struct {
	TeamID uuid.UUID   `db:"team_id" json:"team_id"`
	Ids    []uuid.UUID `db:"ids" json:"ids"`
}

func (q *Queries) DeleteSuppressionsByIDs(ctx context.Context, arg DeleteSuppressionsByIDsParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, deleteSuppressionsByIDs, arg.TeamID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppressionByEmail = `-- name: GetSuppressionByEmail :one
SELECT s.id, s.team_id, s.channel, s.address, s.normalized_address, s.reason, s.origin, s.source_id, s.created_at
FROM channel_suppressions AS s
WHERE s.team_id = $1
  AND s.channel = 'email'
  AND s.normalized_address = lower(btrim($2))
`

type GetSuppressionByEmailParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  string    `db:"email" json:"email"`
}

func (q *Queries) GetSuppressionByEmail(ctx context.Context, arg GetSuppressionByEmailParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, getSuppressionByEmail, arg.TeamID, arg.Email)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSuppressionByID = `-- name: GetSuppressionByID :one
SELECT s.id, s.team_id, s.channel, s.address, s.normalized_address, s.reason, s.origin, s.source_id, s.created_at
FROM channel_suppressions AS s
WHERE s.id = $1
  AND s.team_id = $2
  AND s.channel = 'email'
`

type GetSuppressionByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSuppressionByID(ctx context.Context, arg GetSuppressionByIDParams) (ChannelSuppression, error) {
	row := q.db.QueryRow(ctx, getSuppressionByID, arg.ID, arg.TeamID)
	var i ChannelSuppression
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Channel,
		&i.Address,
		&i.NormalizedAddress,
		&i.Reason,
		&i.Origin,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const isChannelAddressSuppressed = `-- name: IsChannelAddressSuppressed :one
SELECT EXISTS (
    SELECT 1 FROM channel_suppressions
    WHERE team_id = $1
      AND channel = $2
      AND normalized_address = $3
)
`

type IsChannelAddressSuppressedParams struct {
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
	Channel           string    `db:"channel" json:"channel"`
	NormalizedAddress string    `db:"normalized_address" json:"normalized_address"`
}

func (q *Queries) IsChannelAddressSuppressed(ctx context.Context, arg IsChannelAddressSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelAddressSuppressed, arg.TeamID, arg.Channel, arg.NormalizedAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT s.id, s.team_id, s.channel, s.address, s.normalized_address, s.reason, s.origin, s.source_id, s.created_at
FROM channel_suppressions AS s
WHERE s.team_id = $1
  AND s.channel = 'email'
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
OFFSET $2
`

type ListSuppressionsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, listSuppressions, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsAfter = `-- name: ListSuppressionsAfter :many
SELECT s.id, s.team_id, s.channel, s.address, s.normalized_address, s.reason, s.origin, s.source_id, s.created_at
FROM channel_suppressions AS s
WHERE s.team_id = $1
  AND s.channel = 'email'
  AND ($2::text IS NULL OR s.reason = $2)
  AND (s.created_at, s.id) < (
      SELECT cursor_suppression.created_at, cursor_suppression.id
      FROM channel_suppressions AS cursor_suppression
      WHERE cursor_suppression.id = $3
        AND cursor_suppression.team_id = $1
        AND cursor_suppression.channel = 'email'
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListSuppressionsAfterParams struct {
	ScopeTeamID  uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	FilterOrigin *string   `db:"filter_origin" json:"filter_origin"`
	CursorID     uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit    int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressionsAfter(ctx context.Context, arg ListSuppressionsAfterParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsAfter,
		arg.ScopeTeamID,
		arg.FilterOrigin,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsBefore = `-- name: ListSuppressionsBefore :many
SELECT s.id, s.team_id, s.channel, s.address, s.normalized_address, s.reason, s.origin, s.source_id, s.created_at
FROM channel_suppressions AS s
WHERE s.team_id = $1
  AND s.channel = 'email'
  AND ($2::text IS NULL OR s.reason = $2)
  AND (s.created_at, s.id) > (
      SELECT cursor_suppression.created_at, cursor_suppression.id
      FROM channel_suppressions AS cursor_suppression
      WHERE cursor_suppression.id = $3
        AND cursor_suppression.team_id = $1
        AND cursor_suppression.channel = 'email'
  )
ORDER BY s.created_at ASC, s.id ASC
LIMIT $4
`

type ListSuppressionsBeforeParams struct {
	ScopeTeamID  uuid.UUID `db:"scope_team_id" json:"scope_team_id"`
	FilterOrigin *string   `db:"filter_origin" json:"filter_origin"`
	CursorID     uuid.UUID `db:"cursor_id" json:"cursor_id"`
	PageLimit    int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressionsBefore(ctx context.Context, arg ListSuppressionsBeforeParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsBefore,
		arg.ScopeTeamID,
		arg.FilterOrigin,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsFiltered = `-- name: ListSuppressionsFiltered :many
SELECT s.id, s.team_id, s.channel, s.address, s.normalized_address, s.reason, s.origin, s.source_id, s.created_at
FROM channel_suppressions AS s
WHERE s.team_id = $1
  AND s.channel = 'email'
  AND ($2::text IS NULL OR s.reason = $2)
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
`

type ListSuppressionsFilteredParams struct {
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	FilterOrigin *string   `db:"filter_origin" json:"filter_origin"`
	PageLimit    int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSuppressionsFiltered(ctx context.Context, arg ListSuppressionsFilteredParams) ([]ChannelSuppression, error) {
	rows, err := q.db.Query(ctx, listSuppressionsFiltered, arg.TeamID, arg.FilterOrigin, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSuppression{}
	for rows.Next() {
		var i ChannelSuppression
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Channel,
			&i.Address,
			&i.NormalizedAddress,
			&i.Reason,
			&i.Origin,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suppressionCursorExists = `-- name: SuppressionCursorExists :one
SELECT EXISTS (
    SELECT 1
    FROM channel_suppressions AS s
    WHERE s.id = $1
      AND s.team_id = $2
      AND s.channel = 'email'
)
`

type SuppressionCursorExistsParams struct {
	CursorID uuid.UUID `db:"cursor_id" json:"cursor_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SuppressionCursorExists(ctx context.Context, arg SuppressionCursorExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, suppressionCursorExists, arg.CursorID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
