// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamToken = `-- name: CreateTeamToken :one
INSERT INTO team_tokens (
    team_id,
    name,
    token_hash,
    token_prefix,
    permissions,
    created_by,
    expires_at
)
SELECT
    team.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM teams AS team
WHERE team.id = $7
  AND team.status = 'active'
RETURNING id, team_id, name, token_hash, token_prefix, permissions, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type CreateTeamTokenParams struct {
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Permissions []string           `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID         `db:"created_by" json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateTeamToken(ctx context.Context, arg CreateTeamTokenParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, createTeamToken,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Permissions,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.TeamID,
	)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTeamTokenByHash = `-- name: GetActiveTeamTokenByHash :one
SELECT tt.id, tt.team_id, tt.name, tt.token_hash, tt.token_prefix, tt.permissions, tt.created_by, tt.expires_at, tt.revoked_at, tt.last_used_at, tt.created_at, tt.updated_at
FROM team_tokens tt
JOIN teams t ON t.id = tt.team_id
WHERE tt.token_hash = $1
  AND tt.revoked_at IS NULL
  AND (tt.expires_at IS NULL OR tt.expires_at > now())
  AND t.status = 'active'
`

type GetActiveTeamTokenByHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) GetActiveTeamTokenByHash(ctx context.Context, arg GetActiveTeamTokenByHashParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, getActiveTeamTokenByHash, arg.TokenHash)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamTokens = `-- name: ListTeamTokens :many
SELECT token.id, token.team_id, token.name, token.token_hash, token.token_prefix, token.permissions, token.created_by, token.expires_at, token.revoked_at, token.last_used_at, token.created_at, token.updated_at
FROM team_tokens AS token
JOIN teams AS team ON team.id = token.team_id
WHERE token.team_id = $1
  AND team.status = 'active'
ORDER BY token.created_at DESC
`

type ListTeamTokensParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListTeamTokens(ctx context.Context, arg ListTeamTokensParams) ([]TeamToken, error) {
	rows, err := q.db.Query(ctx, listTeamTokens, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamToken{}
	for rows.Next() {
		var i TeamToken
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Permissions,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTeamToken = `-- name: RevokeTeamToken :one
UPDATE team_tokens AS token
SET revoked_at = now(),
    updated_at = now()
FROM teams AS team
WHERE token.id = $1
  AND token.team_id = $2
  AND team.id = token.team_id
  AND team.status = 'active'
  AND token.revoked_at IS NULL
RETURNING token.id, token.team_id, token.name, token.token_hash, token.token_prefix, token.permissions, token.created_by, token.expires_at, token.revoked_at, token.last_used_at, token.created_at, token.updated_at
`

type RevokeTeamTokenParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RevokeTeamToken(ctx context.Context, arg RevokeTeamTokenParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, revokeTeamToken, arg.ID, arg.TeamID)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTeamToken = `-- name: TouchTeamToken :exec
UPDATE team_tokens
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

type TouchTeamTokenParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchTeamToken(ctx context.Context, arg TouchTeamTokenParams) error {
	_, err := q.db.Exec(ctx, touchTeamToken, arg.ID)
	return err
}

const updateTeamToken = `-- name: UpdateTeamToken :one
UPDATE team_tokens AS token
SET name = $1,
    permissions = $2,
    expires_at = $3,
    updated_at = now()
FROM teams AS team
WHERE token.id = $4
  AND token.team_id = $5
  AND team.id = token.team_id
  AND team.status = 'active'
  AND token.revoked_at IS NULL
RETURNING token.id, token.team_id, token.name, token.token_hash, token.token_prefix, token.permissions, token.created_by, token.expires_at, token.revoked_at, token.last_used_at, token.created_at, token.updated_at
`

type UpdateTeamTokenParams struct {
	Name        string             `db:"name" json:"name"`
	Permissions []string           `db:"permissions" json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateTeamToken(ctx context.Context, arg UpdateTeamTokenParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, updateTeamToken,
		arg.Name,
		arg.Permissions,
		arg.ExpiresAt,
		arg.ID,
		arg.TeamID,
	)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
