// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (
    team_id,
    name,
    description,
    default_subscription,
    visibility
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id,
          team_id,
          name,
          description,
          default_subscription,
          visibility,
          created_at,
          updated_at
`

type CreateTopicParams struct {
	TeamID              uuid.UUID `db:"team_id" json:"team_id"`
	Name                string    `db:"name" json:"name"`
	Description         *string   `db:"description" json:"description"`
	DefaultSubscription string    `db:"default_subscription" json:"default_subscription"`
	Visibility          string    `db:"visibility" json:"visibility"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.DefaultSubscription,
		arg.Visibility,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.DefaultSubscription,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :one
DELETE FROM topics
WHERE id = $1
  AND team_id = $2
RETURNING id,
          team_id,
          name,
          description,
          default_subscription,
          visibility,
          created_at,
          updated_at
`

type DeleteTopicParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteTopic(ctx context.Context, arg DeleteTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, deleteTopic, arg.ID, arg.TeamID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.DefaultSubscription,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
SELECT t.id,
       t.team_id,
       t.name,
       t.description,
       t.default_subscription,
       t.visibility,
       t.created_at,
       t.updated_at
FROM topics AS t
WHERE t.id = $1
  AND t.team_id = $2
`

type GetTopicParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetTopic(ctx context.Context, arg GetTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, arg.ID, arg.TeamID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.DefaultSubscription,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT t.id,
       t.team_id,
       t.name,
       t.description,
       t.default_subscription,
       t.visibility,
       t.created_at,
       t.updated_at
FROM topics AS t
WHERE t.team_id = $1
ORDER BY t.created_at DESC, t.id DESC
LIMIT $3
OFFSET $2
`

type ListTopicsParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, arg.TeamID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.DefaultSubscription,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics
SET name = $1,
    description = $2,
    visibility = $3,
    updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id,
          team_id,
          name,
          description,
          default_subscription,
          visibility,
          created_at,
          updated_at
`

type UpdateTopicParams struct {
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	Visibility  string    `db:"visibility" json:"visibility"`
	ID          uuid.UUID `db:"id" json:"id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.ID,
		arg.TeamID,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.DefaultSubscription,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
