// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWebhookDeliveriesForEndpoint = `-- name: CancelWebhookDeliveriesForEndpoint :execrows
UPDATE webhook_deliveries
SET status = 'canceled',
    last_error = 'Webhook endpoint disabled before delivery',
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE endpoint_id = $1
  AND status IN ('pending', 'retrying')
`

type CancelWebhookDeliveriesForEndpointParams struct {
	EndpointID uuid.UUID `db:"endpoint_id" json:"endpoint_id"`
}

func (q *Queries) CancelWebhookDeliveriesForEndpoint(ctx context.Context, arg CancelWebhookDeliveriesForEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelWebhookDeliveriesForEndpoint, arg.EndpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
WITH candidates AS (
    SELECT delivery.id
    FROM webhook_deliveries AS delivery
    JOIN webhook_endpoints AS endpoint ON endpoint.id = delivery.endpoint_id
    JOIN webhook_events AS event ON event.id = delivery.event_id
    JOIN teams AS team ON team.id = event.team_id
    WHERE delivery.status IN ('pending', 'retrying')
      AND delivery.next_attempt_at <= now()
      AND endpoint.enabled = true
      AND endpoint.disabled_at IS NULL
      AND team.status = 'active'
      AND (
          delivery.locked_at IS NULL
          OR delivery.locked_at < $2
      )
    ORDER BY delivery.next_attempt_at, delivery.created_at
    FOR UPDATE OF delivery SKIP LOCKED
    LIMIT $3
)
UPDATE webhook_deliveries AS delivery
SET locked_at = now(),
    locked_by = $1,
    attempt_count = delivery.attempt_count + 1,
    last_attempt_at = now(),
    updated_at = now()
FROM candidates,
     webhook_events AS event,
     webhook_endpoints AS endpoint
WHERE delivery.id = candidates.id
  AND event.id = delivery.event_id
  AND endpoint.id = delivery.endpoint_id
RETURNING
    delivery.id,
    delivery.event_id,
    delivery.endpoint_id,
    delivery.attempt_count,
    event.team_id,
    event.event_type,
    event.payload,
    event.occurred_at,
    endpoint.url,
    endpoint.signing_secret
`

type ClaimWebhookDeliveriesParams struct {
	WorkerID    *string            `db:"worker_id" json:"worker_id"`
	StaleBefore pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
	LimitCount  int32              `db:"limit_count" json:"limit_count"`
}

type ClaimWebhookDeliveriesRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventID       uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID    uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	AttemptCount  int32              `db:"attempt_count" json:"attempt_count"`
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	Url           string             `db:"url" json:"url"`
	SigningSecret []byte             `db:"signing_secret" json:"signing_secret"`
}

func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]ClaimWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, arg.WorkerID, arg.StaleBefore, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimWebhookDeliveriesRow{}
	for rows.Next() {
		var i ClaimWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptCount,
			&i.TeamID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.Url,
			&i.SigningSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookDeliveriesForEvent = `-- name: CreateWebhookDeliveriesForEvent :execrows
INSERT INTO webhook_deliveries (event_id, endpoint_id, status, next_attempt_at)
SELECT
    $1,
    endpoint.id,
    'pending',
    $2
FROM webhook_endpoints AS endpoint
JOIN webhook_events AS event
  ON event.id = $1
 AND event.team_id = endpoint.team_id
JOIN teams AS team ON team.id = event.team_id
WHERE endpoint.enabled = true
  AND endpoint.disabled_at IS NULL
  AND event.event_type = ANY(endpoint.subscribed_events)
  AND team.status = 'active'
ON CONFLICT (event_id, endpoint_id) DO NOTHING
`

type CreateWebhookDeliveriesForEventParams struct {
	EventID       uuid.UUID          `db:"event_id" json:"event_id"`
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
}

func (q *Queries) CreateWebhookDeliveriesForEvent(ctx context.Context, arg CreateWebhookDeliveriesForEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createWebhookDeliveriesForEvent, arg.EventID, arg.NextAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    event_id,
    endpoint_id,
    status,
    next_attempt_at
)
SELECT
    event.id,
    endpoint.id,
    'pending',
    $1
FROM webhook_events AS event
JOIN webhook_endpoints AS endpoint
  ON endpoint.id = $2
 AND endpoint.team_id = event.team_id
JOIN teams AS team ON team.id = event.team_id
WHERE event.id = $3
  AND endpoint.enabled = true
  AND endpoint.disabled_at IS NULL
  AND team.status = 'active'
ON CONFLICT (event_id, endpoint_id) DO UPDATE
SET event_id = EXCLUDED.event_id
RETURNING id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	EndpointID    uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	EventID       uuid.UUID          `db:"event_id" json:"event_id"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.NextAttemptAt, arg.EndpointID, arg.EventID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
FROM webhook_deliveries AS delivery
JOIN webhook_events AS event ON event.id = delivery.event_id
JOIN teams AS team ON team.id = event.team_id
WHERE delivery.id = $1
  AND event.team_id = $2
  AND team.status = 'active'
`

type GetWebhookDeliveryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.ID, arg.TeamID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveriesForEvent = `-- name: ListWebhookDeliveriesForEvent :many
SELECT delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
FROM webhook_deliveries AS delivery
JOIN webhook_events AS event ON event.id = delivery.event_id
JOIN teams AS team ON team.id = event.team_id
WHERE delivery.event_id = $1
  AND event.team_id = $2
  AND team.status = 'active'
ORDER BY delivery.created_at DESC
LIMIT $4
OFFSET $3
`

type ListWebhookDeliveriesForEventParams struct {
	EventID     uuid.UUID `db:"event_id" json:"event_id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWebhookDeliveriesForEvent(ctx context.Context, arg ListWebhookDeliveriesForEventParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesForEvent,
		arg.EventID,
		arg.TeamID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptCount,
			&i.ReplayCount,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastReplayedAt,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :one
WITH failed AS (
UPDATE webhook_deliveries AS delivery
SET status = 'failed',
    response_status = $1,
    response_body = $2,
    last_error = $3,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE delivery.id = $4
  AND delivery.locked_by = $5
RETURNING delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
), update_endpoint AS (
UPDATE webhook_endpoints
SET consecutive_failures = consecutive_failures + 1,
    last_failure_at = now(),
    enabled = CASE
        WHEN consecutive_failures + 1 >= $6::integer THEN false
        ELSE enabled
    END,
    disabled_at = CASE
        WHEN consecutive_failures + 1 >= $6::integer THEN COALESCE(disabled_at, now())
        ELSE disabled_at
    END,
    disabled_reason = CASE
        WHEN enabled AND consecutive_failures + 1 >= $6::integer THEN 'failure_threshold'
        ELSE disabled_reason
    END,
    updated_at = now()
WHERE id = (SELECT endpoint_id FROM failed)
RETURNING id
)
SELECT id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at FROM failed
`

type MarkWebhookDeliveryFailedParams struct {
	ResponseStatus   *int32    `db:"response_status" json:"response_status"`
	ResponseBody     *string   `db:"response_body" json:"response_body"`
	LastError        *string   `db:"last_error" json:"last_error"`
	ID               uuid.UUID `db:"id" json:"id"`
	WorkerID         *string   `db:"worker_id" json:"worker_id"`
	AutoDisableAfter int32     `db:"auto_disable_after" json:"auto_disable_after"`
}

type MarkWebhookDeliveryFailedRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (MarkWebhookDeliveryFailedRow, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryFailed,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
		arg.AutoDisableAfter,
	)
	var i MarkWebhookDeliveryFailedRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliverySucceeded = `-- name: MarkWebhookDeliverySucceeded :one
WITH succeeded AS (
UPDATE webhook_deliveries AS delivery
SET status = 'succeeded',
    response_status = $1,
    response_body = $2,
    last_error = NULL,
    delivered_at = now(),
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE delivery.id = $3
  AND delivery.locked_by = $4
RETURNING delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
), reset_endpoint AS (
UPDATE webhook_endpoints
SET consecutive_failures = 0,
    last_failure_at = NULL,
    disabled_reason = NULL,
    updated_at = now()
WHERE id = (SELECT endpoint_id FROM succeeded)
  AND enabled = true
  AND consecutive_failures > 0
RETURNING id
)
SELECT id, event_id, endpoint_id, status, attempt_count, replay_count, next_attempt_at, last_attempt_at, last_replayed_at, response_status, response_body, last_error, delivered_at, locked_at, locked_by, created_at, updated_at FROM succeeded
`

type MarkWebhookDeliverySucceededParams struct {
	ResponseStatus *int32    `db:"response_status" json:"response_status"`
	ResponseBody   *string   `db:"response_body" json:"response_body"`
	ID             uuid.UUID `db:"id" json:"id"`
	WorkerID       *string   `db:"worker_id" json:"worker_id"`
}

type MarkWebhookDeliverySucceededRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	ReplayCount    int32              `db:"replay_count" json:"replay_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	LastReplayedAt pgtype.Timestamptz `db:"last_replayed_at" json:"last_replayed_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) MarkWebhookDeliverySucceeded(ctx context.Context, arg MarkWebhookDeliverySucceededParams) (MarkWebhookDeliverySucceededRow, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliverySucceeded,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ID,
		arg.WorkerID,
	)
	var i MarkWebhookDeliverySucceededRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseWebhookDeliveryClaim = `-- name: ReleaseWebhookDeliveryClaim :execrows
UPDATE webhook_deliveries
SET locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE id = $1
  AND locked_by = $2
`

type ReleaseWebhookDeliveryClaimParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WorkerID *string   `db:"worker_id" json:"worker_id"`
}

func (q *Queries) ReleaseWebhookDeliveryClaim(ctx context.Context, arg ReleaseWebhookDeliveryClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseWebhookDeliveryClaim, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replayWebhookDelivery = `-- name: ReplayWebhookDelivery :one
UPDATE webhook_deliveries AS delivery
SET status = 'pending',
    replay_count = delivery.replay_count + 1,
    last_replayed_at = now(),
    next_attempt_at = now(),
    response_status = NULL,
    response_body = NULL,
    last_error = NULL,
    delivered_at = NULL,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
FROM webhook_events AS event,
     webhook_endpoints AS endpoint,
     teams AS team
WHERE delivery.id = $1
  AND event.id = delivery.event_id
  AND endpoint.id = delivery.endpoint_id
  AND team.id = event.team_id
  AND event.team_id = $2
  AND team.status = 'active'
  AND endpoint.enabled = true
  AND endpoint.disabled_at IS NULL
  AND delivery.status IN ('succeeded', 'failed', 'canceled')
RETURNING delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
`

type ReplayWebhookDeliveryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ReplayWebhookDelivery(ctx context.Context, arg ReplayWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, replayWebhookDelivery, arg.ID, arg.TeamID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryWebhookDelivery = `-- name: RetryWebhookDelivery :one
UPDATE webhook_deliveries AS delivery
SET status = 'pending',
    next_attempt_at = now(),
    response_status = NULL,
    response_body = NULL,
    last_error = NULL,
    delivered_at = NULL,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
FROM webhook_events AS event,
     webhook_endpoints AS endpoint,
     teams AS team
WHERE delivery.id = $1
  AND event.id = delivery.event_id
  AND endpoint.id = delivery.endpoint_id
  AND team.id = event.team_id
  AND event.team_id = $2
  AND team.status = 'active'
  AND endpoint.enabled = true
  AND endpoint.disabled_at IS NULL
  AND delivery.status = 'failed'
RETURNING delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
`

type RetryWebhookDeliveryParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RetryWebhookDelivery(ctx context.Context, arg RetryWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, retryWebhookDelivery, arg.ID, arg.TeamID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduleWebhookDeliveryRetry = `-- name: ScheduleWebhookDeliveryRetry :one
UPDATE webhook_deliveries AS delivery
SET status = 'retrying',
    next_attempt_at = $1,
    response_status = $2,
    response_body = $3,
    last_error = $4,
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE delivery.id = $5
  AND delivery.locked_by = $6
RETURNING delivery.id, delivery.event_id, delivery.endpoint_id, delivery.status, delivery.attempt_count, delivery.replay_count, delivery.next_attempt_at, delivery.last_attempt_at, delivery.last_replayed_at, delivery.response_status, delivery.response_body, delivery.last_error, delivery.delivered_at, delivery.locked_at, delivery.locked_by, delivery.created_at, delivery.updated_at
`

type ScheduleWebhookDeliveryRetryParams struct {
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	ID             uuid.UUID          `db:"id" json:"id"`
	WorkerID       *string            `db:"worker_id" json:"worker_id"`
}

func (q *Queries) ScheduleWebhookDeliveryRetry(ctx context.Context, arg ScheduleWebhookDeliveryRetryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, scheduleWebhookDeliveryRetry,
		arg.NextAttemptAt,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.ReplayCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastReplayedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
